// @generated by generate-tokens; do not edit.
// Source: design/tokens.toml (sha256:6441caca51d8b377a20b603a7abf4c8f7c27d18ecfdbd7152159ffe0e6ac13ed)

import SwiftUI

/// The Slate themes a token resolves against.
enum SlateTheme: CaseIterable, Sendable {
    case light
    case dark
    case highContrast
    case recording
}

/// A color as 0xRRGGBBAA.
struct SlateRGBA: Equatable, Sendable {
    let rgba: UInt32

    var red: Double { Double((rgba >> 24) & 0xff) / 255 }
    var green: Double { Double((rgba >> 16) & 0xff) / 255 }
    var blue: Double { Double((rgba >> 8) & 0xff) / 255 }
    var alpha: Double { Double(rgba & 0xff) / 255 }
}

struct SlateTypography: Equatable, Sendable {
    let size: Double
    let lineHeight: Double
    let weight: Int
}

enum SlateTokens {
    /// Emphasized border. Allowed use: Selected and high-attention boundaries.
    static func borderEmphasis(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 2.0
        case .dark: return 2.0
        case .highContrast: return 2.0
        case .recording: return 2.0
        }
    }

    /// Default one-pixel border. Allowed use: Dividers and control outlines.
    static func borderHairline(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 1.0
        case .dark: return 1.0
        case .highContrast: return 2.0
        case .recording: return 1.0
        }
    }

    /// Accent color. Allowed use: Links, the active navigation icon, toggles, and drop zones. Never a button fill.
    static func colorActionPrimary(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x2A64C8FF)
        case .dark: return SlateRGBA(rgba: 0x74A7F2FF)
        case .highContrast: return SlateRGBA(rgba: 0x00FFFFFF)
        case .recording: return SlateRGBA(rgba: 0x8CA8E8FF)
        }
    }

    /// Text shown on the accent color. Allowed use: Accent foreground only.
    static func colorActionPrimaryText(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .dark: return SlateRGBA(rgba: 0x0E1622FF)
        case .highContrast: return SlateRGBA(rgba: 0x000000FF)
        case .recording: return SlateRGBA(rgba: 0x111318FF)
        }
    }

    /// Content pane and window ground. Allowed use: Content panes and the window background.
    static func colorBgCanvas(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xFAFBFCFF)
        case .dark: return SlateRGBA(rgba: 0x17191DFF)
        case .highContrast: return SlateRGBA(rgba: 0x000000FF)
        case .recording: return SlateRGBA(rgba: 0x202328FF)
        }
    }

    /// Window chrome background. Allowed use: The title bar, sidebar, toolbar, and status bar.
    static func colorBgChrome(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xE9ECF0FF)
        case .dark: return SlateRGBA(rgba: 0x111316FF)
        case .highContrast: return SlateRGBA(rgba: 0x000000FF)
        case .recording: return SlateRGBA(rgba: 0x1A1C20FF)
        }
    }

    /// Neutral control fill. Allowed use: Default buttons, inputs, key caps, and segmented tracks.
    static func colorBgControl(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .dark: return SlateRGBA(rgba: 0x23262BFF)
        case .highContrast: return SlateRGBA(rgba: 0x000000FF)
        case .recording: return SlateRGBA(rgba: 0x2C3037FF)
        }
    }

    /// Neutral control fill on hover. Allowed use: Hovered default buttons and controls.
    static func colorBgControlHover(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xF2F4F7FF)
        case .dark: return SlateRGBA(rgba: 0x2A2E34FF)
        case .highContrast: return SlateRGBA(rgba: 0x1A1A1AFF)
        case .recording: return SlateRGBA(rgba: 0x333841FF)
        }
    }

    /// Floating object background. Allowed use: Host cards, menus, the command palette, and dialogs.
    static func colorBgElevated(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .dark: return SlateRGBA(rgba: 0x1B1E23FF)
        case .highContrast: return SlateRGBA(rgba: 0x0A0A0AFF)
        case .recording: return SlateRGBA(rgba: 0x25292FFF)
        }
    }

    /// Row and item hover background. Allowed use: Hovered navigation items, rows, menu items, and tabs.
    static func colorBgHover(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xEDF0F3FF)
        case .dark: return SlateRGBA(rgba: 0x1C1F24FF)
        case .highContrast: return SlateRGBA(rgba: 0x1A1A1AFF)
        case .recording: return SlateRGBA(rgba: 0x2A2E34FF)
        }
    }

    /// Selected row and item background. Allowed use: Selected navigation items, rows, segments, and the active tab.
    static func colorBgSelected(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xE1E6EDFF)
        case .dark: return SlateRGBA(rgba: 0x23272EFF)
        case .highContrast: return SlateRGBA(rgba: 0x0033FFFF)
        case .recording: return SlateRGBA(rgba: 0x30353DFF)
        }
    }

    /// Side pane and header surface. Allowed use: Sidebar, inspector, tab and pane headers, and recessed fields.
    static func colorBgSurface(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xF1F3F6FF)
        case .dark: return SlateRGBA(rgba: 0x14161AFF)
        case .highContrast: return SlateRGBA(rgba: 0x000000FF)
        case .recording: return SlateRGBA(rgba: 0x1D2024FF)
        }
    }

    /// Terminal background, equal to the canvas. Allowed use: Terminal viewport only.
    static func colorBgTerminal(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xFAFBFCFF)
        case .dark: return SlateRGBA(rgba: 0x17191DFF)
        case .highContrast: return SlateRGBA(rgba: 0x000000FF)
        case .recording: return SlateRGBA(rgba: 0x202328FF)
        }
    }

    /// Default pane and divider border. Allowed use: Pane edges, the title bar, cards, and fields.
    static func colorBorderDefault(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xD6DAE0FF)
        case .dark: return SlateRGBA(rgba: 0x2A2E35FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0x3A3F47FF)
        }
    }

    /// Input border while the input holds focus. Allowed use: Focused text inputs, paired with the focus ring.
    static func colorBorderFocus(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x8F99A6FF)
        case .dark: return SlateRGBA(rgba: 0x4A5260FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFF00FF)
        case .recording: return SlateRGBA(rgba: 0x6A7280FF)
        }
    }

    /// Control border. Allowed use: Buttons and form fields.
    static func colorBorderStrong(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xC4CAD2FF)
        case .dark: return SlateRGBA(rgba: 0x363A41FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0x464C55FF)
        }
    }

    /// Quiet hairline between sibling regions. Allowed use: Row dividers, pane separators, and card outlines.
    static func colorBorderSubtle(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xE3E6EAFF)
        case .dark: return SlateRGBA(rgba: 0x22262CFF)
        case .highContrast: return SlateRGBA(rgba: 0x8A8A8AFF)
        case .recording: return SlateRGBA(rgba: 0x30343BFF)
        }
    }

    /// Keyboard focus outline. Allowed use: Visible focus indication.
    static func colorFocus(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x2A64C8FF)
        case .dark: return SlateRGBA(rgba: 0x74A7F2FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFF00FF)
        case .recording: return SlateRGBA(rgba: 0xFFFFFFFF)
        }
    }

    /// Surface-colored separation inside the focus ring. Allowed use: Visible focus indication.
    static func colorFocusSeparation(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xF1F3F6FF)
        case .dark: return SlateRGBA(rgba: 0x14161AFF)
        case .highContrast: return SlateRGBA(rgba: 0x000000FF)
        case .recording: return SlateRGBA(rgba: 0x1D2024FF)
        }
    }

    /// Jump host group identity. Allowed use: Group dots and tile marks, always with the group name.
    static func colorGroupJump(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x4F5661FF)
        case .dark: return SlateRGBA(rgba: 0xB4B9C2FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0xC9CDD3FF)
        }
    }

    /// Lab host group identity. Allowed use: Group dots and tile marks, always with the group name.
    static func colorGroupLab(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x6E48C2FF)
        case .dark: return SlateRGBA(rgba: 0xB69CF0FF)
        case .highContrast: return SlateRGBA(rgba: 0xFF66FFFF)
        case .recording: return SlateRGBA(rgba: 0xB5A6D9FF)
        }
    }

    /// Production host group identity. Allowed use: Group dots and tile marks, always with the group name.
    static func colorGroupProduction(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x2A64C8FF)
        case .dark: return SlateRGBA(rgba: 0x74A7F2FF)
        case .highContrast: return SlateRGBA(rgba: 0x00FFFFFF)
        case .recording: return SlateRGBA(rgba: 0x8CA8E8FF)
        }
    }

    /// Staging host group identity. Allowed use: Group dots and tile marks, always with the group name.
    static func colorGroupStaging(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x1A7A45FF)
        case .dark: return SlateRGBA(rgba: 0x6CCB8FFF)
        case .highContrast: return SlateRGBA(rgba: 0x00FF66FF)
        case .recording: return SlateRGBA(rgba: 0x8BC3A4FF)
        }
    }

    /// Modal overlay scrim. Allowed use: Behind the command palette and dialogs only.
    static func colorOverlayScrim(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x1A1D2266)
        case .dark: return SlateRGBA(rgba: 0x08090B8C)
        case .highContrast: return SlateRGBA(rgba: 0x000000E6)
        case .recording: return SlateRGBA(rgba: 0x000000B3)
        }
    }

    /// Terminal text selection background. Allowed use: Selected terminal text. Row selection uses color.bg.selected.
    static func colorSelection(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xCFE0FAFF)
        case .dark: return SlateRGBA(rgba: 0x2B3B52FF)
        case .highContrast: return SlateRGBA(rgba: 0x0033FFFF)
        case .recording: return SlateRGBA(rgba: 0x39465FFF)
        }
    }

    /// Attention status color. Allowed use: Attention state with icon and text.
    static func colorStatusAttention(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x8F5300FF)
        case .dark: return SlateRGBA(rgba: 0xE9B061FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFF00FF)
        case .recording: return SlateRGBA(rgba: 0xD6B47AFF)
        }
    }

    /// Busy status color. Allowed use: Busy state with icon and text.
    static func colorStatusBusy(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x2A64C8FF)
        case .dark: return SlateRGBA(rgba: 0x74A7F2FF)
        case .highContrast: return SlateRGBA(rgba: 0x00FFFFFF)
        case .recording: return SlateRGBA(rgba: 0x8CA8E8FF)
        }
    }

    /// Done status color. Allowed use: Done state with icon and text.
    static func colorStatusDone(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x1A7A45FF)
        case .dark: return SlateRGBA(rgba: 0x6CCB8FFF)
        case .highContrast: return SlateRGBA(rgba: 0x00FF66FF)
        case .recording: return SlateRGBA(rgba: 0x8BC3A4FF)
        }
    }

    /// Error status color. Allowed use: Error state with icon and text.
    static func colorStatusError(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xB8343AFF)
        case .dark: return SlateRGBA(rgba: 0xE5787AFF)
        case .highContrast: return SlateRGBA(rgba: 0xFF66FFFF)
        case .recording: return SlateRGBA(rgba: 0xD99599FF)
        }
    }

    /// Idle status color. Allowed use: Idle state with icon and text.
    static func colorStatusIdle(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x4F5661FF)
        case .dark: return SlateRGBA(rgba: 0x8C929CFF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0xA3A8B0FF)
        }
    }

    /// Offline status color. Allowed use: Offline state with icon and text.
    static func colorStatusOffline(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x626974FF)
        case .dark: return SlateRGBA(rgba: 0x838993FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0x8E949DFF)
        }
    }

    /// ANSI palette slot 0. Allowed use: Terminal SGR color 0.
    static func colorTerminalAnsiBlack(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x1A1D22FF)
        case .dark: return SlateRGBA(rgba: 0x1B1E23FF)
        case .highContrast: return SlateRGBA(rgba: 0x000000FF)
        case .recording: return SlateRGBA(rgba: 0x25292FFF)
        }
    }

    /// ANSI palette slot 4. Allowed use: Terminal SGR color 4.
    static func colorTerminalAnsiBlue(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x2A64C8FF)
        case .dark: return SlateRGBA(rgba: 0x74A7F2FF)
        case .highContrast: return SlateRGBA(rgba: 0x66B3FFFF)
        case .recording: return SlateRGBA(rgba: 0x8CA8E8FF)
        }
    }

    /// ANSI palette slot 8. Allowed use: Terminal SGR color 8.
    static func colorTerminalAnsiBrightBlack(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x4F5661FF)
        case .dark: return SlateRGBA(rgba: 0x5A6069FF)
        case .highContrast: return SlateRGBA(rgba: 0x9A9A9AFF)
        case .recording: return SlateRGBA(rgba: 0x6A7280FF)
        }
    }

    /// ANSI palette slot 12. Allowed use: Terminal SGR color 12.
    static func colorTerminalAnsiBrightBlue(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x3F76D6FF)
        case .dark: return SlateRGBA(rgba: 0x95BCF6FF)
        case .highContrast: return SlateRGBA(rgba: 0xA6D2FFFF)
        case .recording: return SlateRGBA(rgba: 0xA9BFEEFF)
        }
    }

    /// ANSI palette slot 14. Allowed use: Terminal SGR color 14.
    static func colorTerminalAnsiBrightCyan(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x13879AFF)
        case .dark: return SlateRGBA(rgba: 0x86D6E0FF)
        case .highContrast: return SlateRGBA(rgba: 0x99FFFFFF)
        case .recording: return SlateRGBA(rgba: 0xA8D4DAFF)
        }
    }

    /// ANSI palette slot 10. Allowed use: Terminal SGR color 10.
    static func colorTerminalAnsiBrightGreen(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x228A52FF)
        case .dark: return SlateRGBA(rgba: 0x8ADBA7FF)
        case .highContrast: return SlateRGBA(rgba: 0x7DFFAEFF)
        case .recording: return SlateRGBA(rgba: 0xA6D3BAFF)
        }
    }

    /// ANSI palette slot 13. Allowed use: Terminal SGR color 13.
    static func colorTerminalAnsiBrightMagenta(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x8160CFFF)
        case .dark: return SlateRGBA(rgba: 0xCAB5F5FF)
        case .highContrast: return SlateRGBA(rgba: 0xFF9CFFFF)
        case .recording: return SlateRGBA(rgba: 0xC8BCE3FF)
        }
    }

    /// ANSI palette slot 9. Allowed use: Terminal SGR color 9.
    static func colorTerminalAnsiBrightRed(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xCC4A50FF)
        case .dark: return SlateRGBA(rgba: 0xF09499FF)
        case .highContrast: return SlateRGBA(rgba: 0xFF9C9CFF)
        case .recording: return SlateRGBA(rgba: 0xE3AEB1FF)
        }
    }

    /// ANSI palette slot 15. Allowed use: Terminal SGR color 15.
    static func colorTerminalAnsiBrightWhite(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x8B919BFF)
        case .dark: return SlateRGBA(rgba: 0xF1F3F5FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0xF4F5F6FF)
        }
    }

    /// ANSI palette slot 11. Allowed use: Terminal SGR color 11.
    static func colorTerminalAnsiBrightYellow(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xA15F00FF)
        case .dark: return SlateRGBA(rgba: 0xF2C585FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFF99FF)
        case .recording: return SlateRGBA(rgba: 0xE1C696FF)
        }
    }

    /// ANSI palette slot 6. Allowed use: Terminal SGR color 6.
    static func colorTerminalAnsiCyan(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x0E7282FF)
        case .dark: return SlateRGBA(rgba: 0x62C4D1FF)
        case .highContrast: return SlateRGBA(rgba: 0x00FFFFFF)
        case .recording: return SlateRGBA(rgba: 0x8CC5CCFF)
        }
    }

    /// ANSI palette slot 2. Allowed use: Terminal SGR color 2.
    static func colorTerminalAnsiGreen(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x1A7A45FF)
        case .dark: return SlateRGBA(rgba: 0x6CCB8FFF)
        case .highContrast: return SlateRGBA(rgba: 0x00FF66FF)
        case .recording: return SlateRGBA(rgba: 0x8BC3A4FF)
        }
    }

    /// ANSI palette slot 5. Allowed use: Terminal SGR color 5.
    static func colorTerminalAnsiMagenta(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x6E48C2FF)
        case .dark: return SlateRGBA(rgba: 0xB69CF0FF)
        case .highContrast: return SlateRGBA(rgba: 0xFF66FFFF)
        case .recording: return SlateRGBA(rgba: 0xB5A6D9FF)
        }
    }

    /// ANSI palette slot 1. Allowed use: Terminal SGR color 1.
    static func colorTerminalAnsiRed(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xB8343AFF)
        case .dark: return SlateRGBA(rgba: 0xE5787AFF)
        case .highContrast: return SlateRGBA(rgba: 0xFF6B6BFF)
        case .recording: return SlateRGBA(rgba: 0xD99599FF)
        }
    }

    /// ANSI palette slot 7. Allowed use: Terminal SGR color 7.
    static func colorTerminalAnsiWhite(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x626974FF)
        case .dark: return SlateRGBA(rgba: 0xC9CDD4FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0xC9CDD3FF)
        }
    }

    /// ANSI palette slot 3. Allowed use: Terminal SGR color 3.
    static func colorTerminalAnsiYellow(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x8F5300FF)
        case .dark: return SlateRGBA(rgba: 0xE9B061FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFF00FF)
        case .recording: return SlateRGBA(rgba: 0xD6B47AFF)
        }
    }

    /// Terminal cursor. Allowed use: The terminal block, bar, and underline cursor.
    static func colorTerminalCursor(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x1A1D22FF)
        case .dark: return SlateRGBA(rgba: 0xE6E8EBFF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFF00FF)
        case .recording: return SlateRGBA(rgba: 0xF4F5F6FF)
        }
    }

    /// Default terminal foreground. Allowed use: Terminal cells without an explicit color.
    static func colorTerminalFg(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x2A2E35FF)
        case .dark: return SlateRGBA(rgba: 0xC9CDD4FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0xC9CDD3FF)
        }
    }

    /// Lowest-emphasis readable text. Allowed use: Placeholders, shortcut hints, and metadata. Meets 4.5:1 on chrome.
    static func colorTextFaint(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x626974FF)
        case .dark: return SlateRGBA(rgba: 0x838993FF)
        case .highContrast: return SlateRGBA(rgba: 0xD0D0D0FF)
        case .recording: return SlateRGBA(rgba: 0x8E949DFF)
        }
    }

    /// Muted application text. Allowed use: Secondary columns, captions, and inactive tabs.
    static func colorTextMuted(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x4F5661FF)
        case .dark: return SlateRGBA(rgba: 0x8C929CFF)
        case .highContrast: return SlateRGBA(rgba: 0xE0E0E0FF)
        case .recording: return SlateRGBA(rgba: 0xA3A8B0FF)
        }
    }

    /// Primary application text. Allowed use: Names, values, and body copy.
    static func colorTextPrimary(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x1A1D22FF)
        case .dark: return SlateRGBA(rgba: 0xE6E8EBFF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0xF4F5F6FF)
        }
    }

    /// Secondary application text. Allowed use: Technical values and dialog copy.
    static func colorTextSecondary(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x3A404AFF)
        case .dark: return SlateRGBA(rgba: 0xB4B9C2FF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFFFFFF)
        case .recording: return SlateRGBA(rgba: 0xC9CDD3FF)
        }
    }

    /// macOS-compatible close control indicator. Allowed use: Custom desktop window close control only.
    static func colorWindowClose(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xFF5F57FF)
        case .dark: return SlateRGBA(rgba: 0xFF5F57FF)
        case .highContrast: return SlateRGBA(rgba: 0xFF66FFFF)
        case .recording: return SlateRGBA(rgba: 0xD99599FF)
        }
    }

    /// macOS-compatible minimize control indicator. Allowed use: Custom desktop window minimize control only.
    static func colorWindowMinimize(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0xFEBC2EFF)
        case .dark: return SlateRGBA(rgba: 0xFEBC2EFF)
        case .highContrast: return SlateRGBA(rgba: 0xFFFF00FF)
        case .recording: return SlateRGBA(rgba: 0xD6B47AFF)
        }
    }

    /// macOS-compatible zoom control indicator. Allowed use: Custom desktop window zoom control only.
    static func colorWindowZoom(_ theme: SlateTheme) -> SlateRGBA {
        switch theme {
        case .light: return SlateRGBA(rgba: 0x28C840FF)
        case .dark: return SlateRGBA(rgba: 0x28C840FF)
        case .highContrast: return SlateRGBA(rgba: 0x00FF66FF)
        case .recording: return SlateRGBA(rgba: 0x8BC3A4FF)
        }
    }

    /// Compact desktop control height. Allowed use: Small buttons in rows and cards.
    static func controlHeightCompact(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 22.0
        case .dark: return 22.0
        case .highContrast: return 22.0
        case .recording: return 22.0
        }
    }

    /// Default desktop control height. Allowed use: Buttons, filter fields, and search fields.
    static func controlHeightDefault(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 26.0
        case .dark: return 26.0
        case .highContrast: return 26.0
        case .recording: return 26.0
        }
    }

    /// Large control height. Allowed use: The quick-connect field.
    static func controlHeightLarge(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 36.0
        case .dark: return 36.0
        case .highContrast: return 36.0
        case .recording: return 36.0
        }
    }

    /// Focus ring surface separation. Allowed use: Keyboard focus indication.
    static func focusRingOffset(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 1.0
        case .dark: return 1.0
        case .highContrast: return 2.0
        case .recording: return 1.0
        }
    }

    /// Outer focus ring width. Allowed use: Keyboard focus indication.
    static func focusRingWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 2.0
        case .dark: return 2.0
        case .highContrast: return 3.0
        case .recording: return 2.0
        }
    }

    /// Compact icon size. Allowed use: Close glyphs on tabs and panes.
    static func iconSizeCompact(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 11.0
        case .dark: return 11.0
        case .highContrast: return 11.0
        case .recording: return 11.0
        }
    }

    /// Default icon size. Allowed use: Controls and status icons.
    static func iconSizeDefault(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 14.0
        case .dark: return 14.0
        case .highContrast: return 14.0
        case .recording: return 14.0
        }
    }

    /// Status glyph size. Allowed use: Status glyphs only.
    static func iconSizeIndicator(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 7.0
        case .dark: return 7.0
        case .highContrast: return 7.0
        case .recording: return 7.0
        }
    }

    /// Large icon size. Allowed use: Empty-state glyphs without provider branding.
    static func iconSizeLarge(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 20.0
        case .dark: return 20.0
        case .highContrast: return 20.0
        case .recording: return 20.0
        }
    }

    /// Medium icon size. Allowed use: Host tile glyphs.
    static func iconSizeMedium(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 16.0
        case .dark: return 16.0
        case .highContrast: return 16.0
        case .recording: return 16.0
        }
    }

    /// Small icon size. Allowed use: Compact supplemental icons.
    static func iconSizeSmall(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 12.0
        case .dark: return 12.0
        case .highContrast: return 12.0
        case .recording: return 12.0
        }
    }

    /// Box around a status glyph. Allowed use: Status and activity indicators.
    static func iconSizeStatus(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 12.0
        case .dark: return 12.0
        case .highContrast: return 12.0
        case .recording: return 12.0
        }
    }

    /// Default icon stroke width. Allowed use: Outline icons.
    static func iconStrokeDefault(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 1.4
        case .dark: return 1.4
        case .highContrast: return 2.0
        case .recording: return 1.4
        }
    }

    /// Maximum accessibility laboratory content width. Allowed use: Accessibility laboratory content only.
    static func layoutAccessibilityLabContentMaximum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 960.0
        case .dark: return 960.0
        case .highContrast: return 960.0
        case .recording: return 960.0
        }
    }

    /// Maximum accessibility laboratory dialog width. Allowed use: Accessibility laboratory destructive dialog only.
    static func layoutAccessibilityLabDialogMaximum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 560.0
        case .dark: return 560.0
        case .highContrast: return 560.0
        case .recording: return 560.0
        }
    }

    /// Minimum accessibility laboratory window height. Allowed use: Accessibility laboratory window constraints only.
    static func layoutAccessibilityLabMinimumHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 560.0
        case .dark: return 560.0
        case .highContrast: return 560.0
        case .recording: return 560.0
        }
    }

    /// Minimum accessibility laboratory window width. Allowed use: Accessibility laboratory window constraints only.
    static func layoutAccessibilityLabMinimumWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 680.0
        case .dark: return 680.0
        case .highContrast: return 680.0
        case .recording: return 680.0
        }
    }

    /// Accessibility laboratory progress control height. Allowed use: Accessibility laboratory progress controls only.
    static func layoutAccessibilityLabProgressControlHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 38.0
        case .dark: return 38.0
        case .highContrast: return 38.0
        case .recording: return 38.0
        }
    }

    /// Accessibility laboratory progress track height. Allowed use: Accessibility laboratory progress indicator only.
    static func layoutAccessibilityLabProgressTrackHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 10.0
        case .dark: return 10.0
        case .highContrast: return 10.0
        case .recording: return 10.0
        }
    }

    /// Default accessibility laboratory window height. Allowed use: Accessibility laboratory window geometry only.
    static func layoutAccessibilityLabWindowHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 780.0
        case .dark: return 780.0
        case .highContrast: return 780.0
        case .recording: return 780.0
        }
    }

    /// Default accessibility laboratory window width. Allowed use: Accessibility laboratory window geometry only.
    static func layoutAccessibilityLabWindowWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 920.0
        case .dark: return 920.0
        case .highContrast: return 920.0
        case .recording: return 920.0
        }
    }

    /// Activity Center event icon container size. Allowed use: Activity Center event rows only.
    static func layoutActivityIconContainer(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 34.0
        case .dark: return 34.0
        case .highContrast: return 34.0
        case .recording: return 34.0
        }
    }

    /// Empty artifact preview placeholder height. Allowed use: Artifact preview only.
    static func layoutArtifactEmptyPreviewHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 180.0
        case .dark: return 180.0
        case .highContrast: return 180.0
        case .recording: return 180.0
        }
    }

    /// Maximum artifact index column width. Allowed use: Files and artifacts index only.
    static func layoutArtifactIndexMaximum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 420.0
        case .dark: return 420.0
        case .highContrast: return 420.0
        case .recording: return 420.0
        }
    }

    /// Minimum artifact index column width. Allowed use: Files and artifacts index only.
    static func layoutArtifactIndexMinimum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 280.0
        case .dark: return 280.0
        case .highContrast: return 280.0
        case .recording: return 280.0
        }
    }

    /// Preferred artifact index column width. Allowed use: Files and artifacts index only.
    static func layoutArtifactIndexWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 360.0
        case .dark: return 360.0
        case .highContrast: return 360.0
        case .recording: return 360.0
        }
    }

    /// Maximum textual artifact preview height. Allowed use: Artifact preview only.
    static func layoutArtifactPreviewMaximumHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 240.0
        case .dark: return 240.0
        case .highContrast: return 240.0
        case .recording: return 240.0
        }
    }

    /// Artifact table primary column width. Allowed use: Files and artifacts table only.
    static func layoutArtifactPrimaryColumnWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 260.0
        case .dark: return 260.0
        case .highContrast: return 260.0
        case .recording: return 260.0
        }
    }

    /// Host card height. Allowed use: Host cards in the Home grid.
    static func layoutCardHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 60.0
        case .dark: return 60.0
        case .highContrast: return 60.0
        case .recording: return 60.0
        }
    }

    /// Host card minimum width. Allowed use: Host grid column sizing.
    static func layoutCardMinimumWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 280.0
        case .dark: return 280.0
        case .highContrast: return 280.0
        case .recording: return 280.0
        }
    }

    /// Host card tile size. Allowed use: The square mark at the start of a host card.
    static func layoutCardTile(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 36.0
        case .dark: return 36.0
        case .highContrast: return 36.0
        case .recording: return 36.0
        }
    }

    /// Desktop title bar height. Allowed use: Desktop window chrome.
    static func layoutChromeHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 38.0
        case .dark: return 38.0
        case .highContrast: return 38.0
        case .recording: return 38.0
        }
    }

    /// Connection setup panel width. Allowed use: Connection setup overlays only.
    static func layoutConnectPanelWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 420.0
        case .dark: return 420.0
        case .highContrast: return 420.0
        case .recording: return 420.0
        }
    }

    /// Height of one option inside a segmented control. Allowed use: Segmented control options; the track adds its padding and border.
    static func layoutControlSegmentHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 24.0
        case .dark: return 24.0
        case .highContrast: return 24.0
        case .recording: return 24.0
        }
    }

    /// Wide dialog width. Allowed use: Host-key and multi-field dialogs.
    static func layoutDialogWideWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 460.0
        case .dark: return 460.0
        case .highContrast: return 460.0
        case .recording: return 460.0
        }
    }

    /// Standard dialog width. Allowed use: Confirmation and form dialogs.
    static func layoutDialogWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 420.0
        case .dark: return 420.0
        case .highContrast: return 420.0
        case .recording: return 420.0
        }
    }

    /// Compact form width for network port fields. Allowed use: Network port form fields only.
    static func layoutFormPortWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 150.0
        case .dark: return 150.0
        case .highContrast: return 150.0
        case .recording: return 150.0
        }
    }

    /// Minimum compact host result row height. Allowed use: Compact host search and selection rows.
    static func layoutHostCompactRowHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 56.0
        case .dark: return 56.0
        case .highContrast: return 56.0
        case .recording: return 56.0
        }
    }

    /// Host library sidebar width. Allowed use: Desktop sidebar.
    static func layoutHostSidebarWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 232.0
        case .dark: return 232.0
        case .highContrast: return 232.0
        case .recording: return 232.0
        }
    }

    /// Default inspector width. Allowed use: Resizable desktop inspector.
    static func layoutInspectorDefault(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 290.0
        case .dark: return 290.0
        case .highContrast: return 290.0
        case .recording: return 290.0
        }
    }

    /// Maximum inspector width. Allowed use: Resizable desktop inspector.
    static func layoutInspectorMaximum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 420.0
        case .dark: return 420.0
        case .highContrast: return 420.0
        case .recording: return 420.0
        }
    }

    /// Minimum inspector width. Allowed use: Resizable desktop inspector.
    static func layoutInspectorMinimum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 260.0
        case .dark: return 260.0
        case .highContrast: return 260.0
        case .recording: return 260.0
        }
    }

    /// List row height. Allowed use: Host list rows and palette results.
    static func layoutListRowHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 32.0
        case .dark: return 32.0
        case .highContrast: return 32.0
        case .recording: return 32.0
        }
    }

    /// Primary navigation rail width. Allowed use: Desktop navigation rail.
    static func layoutNavigationWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 52.0
        case .dark: return 52.0
        case .highContrast: return 52.0
        case .recording: return 52.0
        }
    }

    /// Global palette offset from the top of the window. Allowed use: Desktop global palette positioning only.
    static func layoutPaletteOffsetTop(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 50.0
        case .dark: return 50.0
        case .highContrast: return 50.0
        case .recording: return 50.0
        }
    }

    /// Maximum global palette surface width. Allowed use: Desktop global palette only.
    static func layoutPaletteWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 560.0
        case .dark: return 560.0
        case .highContrast: return 560.0
        case .recording: return 560.0
        }
    }

    /// Split pane header height. Allowed use: Pane headers inside split terminals.
    static func layoutPaneHeaderHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 28.0
        case .dark: return 28.0
        case .highContrast: return 28.0
        case .recording: return 28.0
        }
    }

    /// Compact progress track height. Allowed use: Inline progress indicators only.
    static func layoutProgressCompactHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 6.0
        case .dark: return 6.0
        case .highContrast: return 6.0
        case .recording: return 6.0
        }
    }

    /// Quick connect field height. Allowed use: The Home quick connect field.
    static func layoutQuickConnectHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 36.0
        case .dark: return 36.0
        case .highContrast: return 36.0
        case .recording: return 36.0
        }
    }

    /// Maximum security workflow dialog width. Allowed use: Key lifecycle and security dialogs only.
    static func layoutSecurityDialogMaximum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 620.0
        case .dark: return 620.0
        case .highContrast: return 620.0
        case .recording: return 620.0
        }
    }

    /// Maximum security information panel width. Allowed use: Key lifecycle and security information panels only.
    static func layoutSecurityInfoMaximum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 440.0
        case .dark: return 440.0
        case .highContrast: return 440.0
        case .recording: return 440.0
        }
    }

    /// Maximum width of the settings content column. Allowed use: Settings section content, so rows stay readable in wide windows.
    static func layoutSettingsContentMaxWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 760.0
        case .dark: return 760.0
        case .highContrast: return 760.0
        case .recording: return 760.0
        }
    }

    /// Settings category list width. Allowed use: The Settings category sidebar beside the settings content.
    static func layoutSettingsNavWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 216.0
        case .dark: return 216.0
        case .highContrast: return 216.0
        case .recording: return 216.0
        }
    }

    /// Compact shell toolbar and menu-row control height. Allowed use: Desktop shell chrome and shared menu rows.
    static func layoutShellCompactControlHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 26.0
        case .dark: return 26.0
        case .highContrast: return 26.0
        case .recording: return 26.0
        }
    }

    /// Square shell icon-button target size. Allowed use: Desktop shell toolbar icon buttons.
    static func layoutShellIconButtonSize(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 24.0
        case .dark: return 24.0
        case .highContrast: return 24.0
        case .recording: return 24.0
        }
    }

    /// Height for navigation count badges. Allowed use: Desktop navigation count badges only.
    static func layoutShellNavBadgeHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 20.0
        case .dark: return 20.0
        case .highContrast: return 20.0
        case .recording: return 20.0
        }
    }

    /// Minimum width for navigation count badges. Allowed use: Desktop navigation count badges only.
    static func layoutShellNavBadgeWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 22.0
        case .dark: return 22.0
        case .highContrast: return 22.0
        case .recording: return 22.0
        }
    }

    /// Primary navigation row height. Allowed use: Desktop primary navigation rows only.
    static func layoutShellNavigationRowHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 28.0
        case .dark: return 28.0
        case .highContrast: return 28.0
        case .recording: return 28.0
        }
    }

    /// Terminal-pane context-menu width. Allowed use: Desktop pane context menu only.
    static func layoutShellPaneMenuWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 212.0
        case .dark: return 212.0
        case .highContrast: return 212.0
        case .recording: return 212.0
        }
    }

    /// Inline workspace rename field width. Allowed use: Desktop workspace tab rename field only.
    static func layoutShellRenameFieldWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 150.0
        case .dark: return 150.0
        case .highContrast: return 150.0
        case .recording: return 150.0
        }
    }

    /// Minimum trailing workspace-tab drop target width. Allowed use: Desktop workspace tab strip only.
    static func layoutShellTabDropMinimum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 80.0
        case .dark: return 80.0
        case .highContrast: return 80.0
        case .recording: return 80.0
        }
    }

    /// Maximum workspace-tab label width before truncation. Allowed use: Desktop workspace tabs only.
    static func layoutShellTabLabelMaximum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 160.0
        case .dark: return 160.0
        case .highContrast: return 160.0
        case .recording: return 160.0
        }
    }

    /// Toolbar button height. Allowed use: Desktop shell toolbar actions only.
    static func layoutShellToolbarButtonSize(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 24.0
        case .dark: return 24.0
        case .highContrast: return 24.0
        case .recording: return 24.0
        }
    }

    /// Visible macOS traffic-light indicator diameter. Allowed use: Custom desktop window controls only.
    static func layoutShellTrafficLightSize(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 12.0
        case .dark: return 12.0
        case .highContrast: return 12.0
        case .recording: return 12.0
        }
    }

    /// Workspace context-menu width. Allowed use: Desktop workspace context menu only.
    static func layoutShellWorkspaceMenuWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 238.0
        case .dark: return 238.0
        case .highContrast: return 238.0
        case .recording: return 238.0
        }
    }

    /// Default context sidebar width. Allowed use: Resizable desktop context sidebar.
    static func layoutSidebarDefault(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 232.0
        case .dark: return 232.0
        case .highContrast: return 232.0
        case .recording: return 232.0
        }
    }

    /// Maximum context sidebar width. Allowed use: Resizable desktop context sidebar.
    static func layoutSidebarMaximum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 320.0
        case .dark: return 320.0
        case .highContrast: return 320.0
        case .recording: return 320.0
        }
    }

    /// Minimum context sidebar width. Allowed use: Resizable desktop context sidebar.
    static func layoutSidebarMinimum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 200.0
        case .dark: return 200.0
        case .highContrast: return 200.0
        case .recording: return 200.0
        }
    }

    /// Split divider hit area. Allowed use: The draggable area around a one-pixel pane divider.
    static func layoutSplitDividerHit(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 6.0
        case .dark: return 6.0
        case .highContrast: return 6.0
        case .recording: return 6.0
        }
    }

    /// Maximum panes per terminal tab. Allowed use: Split pane limits.
    static func layoutSplitMaxPanes(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 4.0
        case .dark: return 4.0
        case .highContrast: return 4.0
        case .recording: return 4.0
        }
    }

    /// Status bar height. Allowed use: Desktop status bar.
    static func layoutStatusHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 26.0
        case .dark: return 26.0
        case .highContrast: return 26.0
        case .recording: return 26.0
        }
    }

    /// Data table row height. Allowed use: Table rows in SFTP, known hosts, and logs.
    static func layoutTableRowHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 30.0
        case .dark: return 30.0
        case .highContrast: return 30.0
        case .recording: return 30.0
        }
    }

    /// View toolbar height. Allowed use: Toolbars under the title bar.
    static func layoutToolbarHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 40.0
        case .dark: return 40.0
        case .highContrast: return 40.0
        case .recording: return 40.0
        }
    }

    /// Library toolbar menu offset from the top of the library pane. Allowed use: Library toolbar dropdowns and host overlays only. Clears the toolbar row so a menu never covers its trigger.
    static func layoutToolbarMenuOffsetTop(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 88.0
        case .dark: return 88.0
        case .highContrast: return 88.0
        case .recording: return 88.0
        }
    }

    /// Default height for a newly duplicated desktop window. Allowed use: Initial desktop window geometry only.
    static func layoutWindowDefaultHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 840.0
        case .dark: return 840.0
        case .highContrast: return 840.0
        case .recording: return 840.0
        }
    }

    /// Default width for a newly duplicated desktop window. Allowed use: Initial desktop window geometry only.
    static func layoutWindowDefaultWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 1280.0
        case .dark: return 1280.0
        case .highContrast: return 1280.0
        case .recording: return 1280.0
        }
    }

    /// Responsive desktop minimum window height target. Allowed use: Window constraints after responsive migration.
    static func layoutWindowMinimumHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 640.0
        case .dark: return 640.0
        case .highContrast: return 640.0
        case .recording: return 640.0
        }
    }

    /// Responsive desktop minimum window width target. Allowed use: Window constraints after responsive migration.
    static func layoutWindowMinimumWidth(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 960.0
        case .dark: return 960.0
        case .highContrast: return 960.0
        case .recording: return 960.0
        }
    }

    /// Horizontal offset hiding native controls behind custom window chrome. Allowed use: macOS desktop window options only.
    static func layoutWindowNativeControlOffset(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 200.0
        case .dark: return 200.0
        case .highContrast: return 200.0
        case .recording: return 200.0
        }
    }

    /// Terminal tab header height. Allowed use: Desktop terminal tab headers.
    static func layoutWorkspaceHeaderHeight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 36.0
        case .dark: return 36.0
        case .highContrast: return 36.0
        case .recording: return 36.0
        }
    }

    /// Control corner radius. Allowed use: Buttons, inputs, menu items, tooltips, toasts, and callouts.
    static func radiusControl(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 4.0
        case .dark: return 4.0
        case .highContrast: return 4.0
        case .recording: return 4.0
        }
    }

    /// Floating surface corner radius. Allowed use: The command palette, dialogs, and menus.
    static func radiusDialog(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 6.0
        case .dark: return 6.0
        case .highContrast: return 6.0
        case .recording: return 6.0
        }
    }

    /// Card corner radius. Allowed use: Host cards and host tiles.
    static func radiusPanel(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 6.0
        case .dark: return 6.0
        case .highContrast: return 6.0
        case .recording: return 6.0
        }
    }

    /// Pill radius. Allowed use: Toggles and count badges only.
    static func radiusPill(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 999.0
        case .dark: return 999.0
        case .highContrast: return 999.0
        case .recording: return 999.0
        }
    }

    /// Compact progress-track corner radius. Allowed use: Inline progress indicators only.
    static func radiusProgress(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 2.0
        case .dark: return 2.0
        case .highContrast: return 2.0
        case .recording: return 2.0
        }
    }

    /// Segment corner radius inside a segmented control. Allowed use: Segmented control segments only.
    static func radiusSegment(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 3.0
        case .dark: return 3.0
        case .highContrast: return 3.0
        case .recording: return 3.0
        }
    }

    /// Zero spacing. Allowed use: Explicitly remove spacing.
    static func space0(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 0.0
        case .dark: return 0.0
        case .highContrast: return 0.0
        case .recording: return 0.0
        }
    }

    /// Two-pixel spacing step. Allowed use: Global spacing scale.
    static func space1(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 2.0
        case .dark: return 2.0
        case .highContrast: return 2.0
        case .recording: return 2.0
        }
    }

    /// Four-pixel spacing step. Allowed use: Global spacing scale.
    static func space2(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 4.0
        case .dark: return 4.0
        case .highContrast: return 4.0
        case .recording: return 4.0
        }
    }

    /// Eight-pixel spacing step. Allowed use: Global spacing scale.
    static func space3(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 8.0
        case .dark: return 8.0
        case .highContrast: return 8.0
        case .recording: return 8.0
        }
    }

    /// Twelve-pixel spacing step. Allowed use: Global spacing scale.
    static func space4(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 12.0
        case .dark: return 12.0
        case .highContrast: return 12.0
        case .recording: return 12.0
        }
    }

    /// Sixteen-pixel spacing step. Allowed use: Global spacing scale.
    static func space5(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 16.0
        case .dark: return 16.0
        case .highContrast: return 16.0
        case .recording: return 16.0
        }
    }

    /// Twenty-four-pixel spacing step. Allowed use: Global spacing scale.
    static func space6(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 24.0
        case .dark: return 24.0
        case .highContrast: return 24.0
        case .recording: return 24.0
        }
    }

    /// Thirty-two-pixel spacing step. Allowed use: Global spacing scale.
    static func space7(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 32.0
        case .dark: return 32.0
        case .highContrast: return 32.0
        case .recording: return 32.0
        }
    }

    /// Forty-eight-pixel spacing step. Allowed use: Global spacing scale.
    static func space8(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 48.0
        case .dark: return 48.0
        case .highContrast: return 48.0
        case .recording: return 48.0
        }
    }

    /// Sixty-four-pixel spacing step. Allowed use: Global spacing scale.
    static func space9(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 64.0
        case .dark: return 64.0
        case .highContrast: return 64.0
        case .recording: return 64.0
        }
    }

    /// Accessibility laboratory dialog content gap. Allowed use: Accessibility laboratory destructive dialog only.
    static func spaceAccessibilityLabDialogGap(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 14.0
        case .dark: return 14.0
        case .highContrast: return 14.0
        case .recording: return 14.0
        }
    }

    /// Accessibility laboratory dialog padding. Allowed use: Accessibility laboratory destructive dialog only.
    static func spaceAccessibilityLabDialogPadding(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 22.0
        case .dark: return 22.0
        case .highContrast: return 22.0
        case .recording: return 22.0
        }
    }

    /// Accessibility laboratory section content gap. Allowed use: Accessibility laboratory sections only.
    static func spaceAccessibilityLabSectionGap(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 10.0
        case .dark: return 10.0
        case .highContrast: return 10.0
        case .recording: return 10.0
        }
    }

    /// Accessibility laboratory section vertical padding. Allowed use: Accessibility laboratory sections only.
    static func spaceAccessibilityLabSectionVertical(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 18.0
        case .dark: return 18.0
        case .highContrast: return 18.0
        case .recording: return 18.0
        }
    }

    /// Accessibility laboratory status vertical padding. Allowed use: Accessibility laboratory status region only.
    static func spaceAccessibilityLabStatusVertical(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 14.0
        case .dark: return 14.0
        case .highContrast: return 14.0
        case .recording: return 14.0
        }
    }

    /// Compact ten-pixel layout spacing. Allowed use: Dense application controls and panels.
    static func spaceCompact(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 10.0
        case .dark: return 10.0
        case .highContrast: return 10.0
        case .recording: return 10.0
        }
    }

    /// Dense six-pixel layout spacing. Allowed use: Dense application controls and form rows.
    static func spaceDense(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 6.0
        case .dark: return 6.0
        case .highContrast: return 6.0
        case .recording: return 6.0
        }
    }

    /// Fine five-pixel layout spacing. Allowed use: Tightly coupled editor labels and controls.
    static func spaceFine(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 5.0
        case .dark: return 5.0
        case .highContrast: return 5.0
        case .recording: return 5.0
        }
    }

    /// Micro three-pixel layout spacing. Allowed use: Tightly coupled status marks and labels only.
    static func spaceMicro(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 3.0
        case .dark: return 3.0
        case .highContrast: return 3.0
        case .recording: return 3.0
        }
    }

    /// Horizontal padding for full-width shell banners. Allowed use: Desktop shell overlay banners only.
    static func spaceShellBannerHorizontal(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 18.0
        case .dark: return 18.0
        case .highContrast: return 18.0
        case .recording: return 18.0
        }
    }

    /// Compact shell control padding. Allowed use: Desktop shell controls and banners.
    static func spaceShellCompact(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 10.0
        case .dark: return 10.0
        case .highContrast: return 10.0
        case .recording: return 10.0
        }
    }

    /// Dense spacing inside desktop shell controls. Allowed use: Desktop shell controls and menus.
    static func spaceShellDense(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 6.0
        case .dark: return 6.0
        case .highContrast: return 6.0
        case .recording: return 6.0
        }
    }

    /// Tight horizontal spacing for compact shell rows. Allowed use: Desktop shell rows only.
    static func spaceShellTight(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 9.0
        case .dark: return 9.0
        case .highContrast: return 9.0
        case .recording: return 9.0
        }
    }

    /// Terminal viewport horizontal padding. Allowed use: Terminal viewport left and right padding only.
    static func spaceTerminalInline(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 16.0
        case .dark: return 16.0
        case .highContrast: return 16.0
        case .recording: return 16.0
        }
    }

    /// Terminal viewport padding. Allowed use: Terminal viewport padding only.
    static func spaceTerminalPadding(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 10.0
        case .dark: return 10.0
        case .highContrast: return 10.0
        case .recording: return 10.0
        }
    }

    /// Minimum desktop pointer target, WCAG 2.2 target size (minimum). Allowed use: Desktop interactive controls. Smaller glyphs get invisible padding up to this size.
    static func targetPointerMinimum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 24.0
        case .dark: return 24.0
        case .highContrast: return 24.0
        case .recording: return 24.0
        }
    }

    /// Minimum touch target. Allowed use: Touch-capable controls.
    static func targetTouchMinimum(_ theme: SlateTheme) -> Double {
        switch theme {
        case .light: return 44.0
        case .dark: return 44.0
        case .highContrast: return 44.0
        case .recording: return 44.0
        }
    }

    /// Compact Activity Center page title typography. Allowed use: Activity Center title only.
    static func typeActivityTitle(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 16.0, lineHeight: 22.0, weight: 600)
        case .dark: return SlateTypography(size: 16.0, lineHeight: 22.0, weight: 600)
        case .highContrast: return SlateTypography(size: 16.0, lineHeight: 22.0, weight: 600)
        case .recording: return SlateTypography(size: 16.0, lineHeight: 22.0, weight: 600)
        }
    }

    /// Default body typography. Allowed use: Application body copy.
    static func typeBody(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 13.0, lineHeight: 18.0, weight: 400)
        case .dark: return SlateTypography(size: 13.0, lineHeight: 18.0, weight: 400)
        case .highContrast: return SlateTypography(size: 13.0, lineHeight: 18.0, weight: 400)
        case .recording: return SlateTypography(size: 13.0, lineHeight: 18.0, weight: 400)
        }
    }

    /// Large body typography. Allowed use: Palette query input and dialog lead copy.
    static func typeBodyLarge(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 14.0, lineHeight: 20.0, weight: 400)
        case .dark: return SlateTypography(size: 14.0, lineHeight: 20.0, weight: 400)
        case .highContrast: return SlateTypography(size: 14.0, lineHeight: 20.0, weight: 400)
        case .recording: return SlateTypography(size: 14.0, lineHeight: 20.0, weight: 400)
        }
    }

    /// Relaxed body typography. Allowed use: Callout, banner, and empty-state copy.
    static func typeBodyRelaxed(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 13.0, lineHeight: 19.0, weight: 400)
        case .dark: return SlateTypography(size: 13.0, lineHeight: 19.0, weight: 400)
        case .highContrast: return SlateTypography(size: 13.0, lineHeight: 19.0, weight: 400)
        case .recording: return SlateTypography(size: 13.0, lineHeight: 19.0, weight: 400)
        }
    }

    /// Small body typography. Allowed use: Dense supporting copy.
    static func typeBodySmall(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 12.0, lineHeight: 17.0, weight: 400)
        case .dark: return SlateTypography(size: 12.0, lineHeight: 17.0, weight: 400)
        case .highContrast: return SlateTypography(size: 12.0, lineHeight: 17.0, weight: 400)
        case .recording: return SlateTypography(size: 12.0, lineHeight: 17.0, weight: 400)
        }
    }

    /// Caption typography. Allowed use: Compact metadata.
    static func typeCaption(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 12.0, lineHeight: 16.0, weight: 400)
        case .dark: return SlateTypography(size: 12.0, lineHeight: 16.0, weight: 400)
        case .highContrast: return SlateTypography(size: 12.0, lineHeight: 16.0, weight: 400)
        case .recording: return SlateTypography(size: 12.0, lineHeight: 16.0, weight: 400)
        }
    }

    /// Heading typography. Allowed use: Primary section headings.
    static func typeHeading(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 14.0, lineHeight: 20.0, weight: 600)
        case .dark: return SlateTypography(size: 14.0, lineHeight: 20.0, weight: 600)
        case .highContrast: return SlateTypography(size: 14.0, lineHeight: 20.0, weight: 600)
        case .recording: return SlateTypography(size: 14.0, lineHeight: 20.0, weight: 600)
        }
    }

    /// Small heading typography. Allowed use: Section headings.
    static func typeHeadingSmall(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 13.0, lineHeight: 18.0, weight: 600)
        case .dark: return SlateTypography(size: 13.0, lineHeight: 18.0, weight: 600)
        case .highContrast: return SlateTypography(size: 13.0, lineHeight: 18.0, weight: 600)
        case .recording: return SlateTypography(size: 13.0, lineHeight: 18.0, weight: 600)
        }
    }

    /// Control label typography. Allowed use: Control and row labels.
    static func typeLabel(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 12.0, lineHeight: 16.0, weight: 500)
        case .dark: return SlateTypography(size: 12.0, lineHeight: 16.0, weight: 500)
        case .highContrast: return SlateTypography(size: 12.0, lineHeight: 16.0, weight: 500)
        case .recording: return SlateTypography(size: 12.0, lineHeight: 16.0, weight: 500)
        }
    }

    /// Compact numeric metric typography. Allowed use: Prominent compact metrics and pairing codes.
    static func typeMetric(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 20.0, lineHeight: 24.0, weight: 600)
        case .dark: return SlateTypography(size: 20.0, lineHeight: 24.0, weight: 600)
        case .highContrast: return SlateTypography(size: 20.0, lineHeight: 24.0, weight: 600)
        case .recording: return SlateTypography(size: 20.0, lineHeight: 24.0, weight: 600)
        }
    }

    /// Micro metadata typography. Allowed use: Space-constrained secondary metadata only.
    static func typeMicro(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 11.0, lineHeight: 14.0, weight: 400)
        case .dark: return SlateTypography(size: 11.0, lineHeight: 14.0, weight: 400)
        case .highContrast: return SlateTypography(size: 11.0, lineHeight: 14.0, weight: 400)
        case .recording: return SlateTypography(size: 11.0, lineHeight: 14.0, weight: 400)
        }
    }

    /// Smallest supported metadata typography. Allowed use: Exceptional space-constrained metadata only.
    static func typeNano(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 10.0, lineHeight: 14.0, weight: 400)
        case .dark: return SlateTypography(size: 10.0, lineHeight: 14.0, weight: 400)
        case .highContrast: return SlateTypography(size: 10.0, lineHeight: 14.0, weight: 400)
        case .recording: return SlateTypography(size: 10.0, lineHeight: 14.0, weight: 400)
        }
    }

    /// Default terminal typography before user scaling. Allowed use: Terminal viewport only; font size remains user-configurable.
    static func typeTerminal(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 13.0, lineHeight: 18.2, weight: 400)
        case .dark: return SlateTypography(size: 13.0, lineHeight: 18.2, weight: 400)
        case .highContrast: return SlateTypography(size: 13.0, lineHeight: 18.2, weight: 400)
        case .recording: return SlateTypography(size: 13.0, lineHeight: 18.2, weight: 400)
        }
    }

    /// Page title typography. Allowed use: Top-level page titles.
    static func typeTitle(_ theme: SlateTheme) -> SlateTypography {
        switch theme {
        case .light: return SlateTypography(size: 20.0, lineHeight: 28.0, weight: 600)
        case .dark: return SlateTypography(size: 20.0, lineHeight: 28.0, weight: 600)
        case .highContrast: return SlateTypography(size: 20.0, lineHeight: 28.0, weight: 600)
        case .recording: return SlateTypography(size: 20.0, lineHeight: 28.0, weight: 600)
        }
    }
}
