// @generated by generate-tokens; do not edit.
// Source: design/tokens.toml (sha256:83d8003bd4b971e198cb9237643f9f86b75e95d04cf53a6fabdf2896734eff90)

#[rustfmt::skip]
mod token_data {
pub const TOKEN_SCHEMA_VERSION: u16 = 1;
pub const TOKEN_SOURCE_SHA256: &str = "83d8003bd4b971e198cb9237643f9f86b75e95d04cf53a6fabdf2896734eff90";


#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ThemeKind {
    System,
    Light,
    Dark,
    HighContrast,
    RecordingFriendly,
}

impl ThemeKind {
    pub const ALL: [Self; 5] = [
        Self::System,
        Self::Light,
        Self::Dark,
        Self::HighContrast,
        Self::RecordingFriendly,
    ];
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ColorValue {
    pub red: u8,
    pub green: u8,
    pub blue: u8,
    pub alpha: u8,
}

impl ColorValue {
    pub const fn from_rgba(rgba: u32) -> Self {
        Self {
            red: ((rgba >> 24) & 0xff) as u8,
            green: ((rgba >> 16) & 0xff) as u8,
            blue: ((rgba >> 8) & 0xff) as u8,
            alpha: (rgba & 0xff) as u8,
        }
    }

    pub const fn rgba(self) -> u32 {
        ((self.red as u32) << 24)
            | ((self.green as u32) << 16)
            | ((self.blue as u32) << 8)
            | self.alpha as u32
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FontFamilyValue(pub &'static str);
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TypographyValue { pub size: f32, pub line_height: f32, pub weight: u16 }
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpacingValue(pub f32);
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct DimensionValue(pub f32);
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct BorderValue(pub f32);
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct RadiusValue(pub f32);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ElevationValue(pub u16);
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ShadowValue {
    pub x: f32,
    pub y: f32,
    pub blur: f32,
    pub spread: f32,
    pub color: ColorValue,
    pub visible: bool,
}
impl ShadowValue {
    pub const NONE: Self = Self {
        x: 0.0,
        y: 0.0,
        blur: 0.0,
        spread: 0.0,
        color: ColorValue::from_rgba(0),
        visible: false,
    };
}
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct IconValue(pub &'static str);
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TextValue(pub &'static str);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DurationValue(pub u16);
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct EasingValue { pub x1: f32, pub y1: f32, pub x2: f32, pub y2: f32 }
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ZIndexValue(pub i16);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StatusKind { Attention, Busy, Done, Error, Idle, Offline, Orphaned, PermissionDenied }

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct StatusVisual {
    pub color: ColorValue,
    pub icon: IconValue,
    pub text: TextValue,
    pub shape: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DesignTokens { theme: ThemeKind }

impl DesignTokens {
    pub const fn new(theme: ThemeKind) -> Self { Self { theme } }

    pub const fn theme(self) -> ThemeKind { self.theme }

    /// Emphasized border. Allowed use: Selected and high-attention boundaries.
    pub const fn border_emphasis(self) -> BorderValue {
        match self.theme {
            ThemeKind::System => BorderValue(2.0f32),
            ThemeKind::Light => BorderValue(2.0f32),
            ThemeKind::Dark => BorderValue(2.0f32),
            ThemeKind::HighContrast => BorderValue(2.0f32),
            ThemeKind::RecordingFriendly => BorderValue(2.0f32),
        }
    }

    /// Default one-pixel border. Allowed use: Dividers and control outlines.
    pub const fn border_hairline(self) -> BorderValue {
        match self.theme {
            ThemeKind::System => BorderValue(1.0f32),
            ThemeKind::Light => BorderValue(1.0f32),
            ThemeKind::Dark => BorderValue(1.0f32),
            ThemeKind::HighContrast => BorderValue(2.0f32),
            ThemeKind::RecordingFriendly => BorderValue(1.0f32),
        }
    }

    /// Primary action color. Allowed use: Primary actions and links.
    pub const fn color_action_primary(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x7ea2ffff),
            ThemeKind::Light => ColorValue::from_rgba(0x2457d6ff),
            ThemeKind::Dark => ColorValue::from_rgba(0x7ea2ffff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x00ffffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x8ca8e8ff),
        }
    }

    /// Text shown on the primary action color. Allowed use: Primary action foreground only.
    pub const fn color_action_primary_text(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x07132eff),
            ThemeKind::Light => ColorValue::from_rgba(0xffffffff),
            ThemeKind::Dark => ColorValue::from_rgba(0x07132eff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x000000ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x111318ff),
        }
    }

    /// Window and application canvas background. Allowed use: Top-level application backgrounds.
    pub const fn color_bg_canvas(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x101318ff),
            ThemeKind::Light => ColorValue::from_rgba(0xf7f8faff),
            ThemeKind::Dark => ColorValue::from_rgba(0x101318ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x000000ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x17191dff),
        }
    }

    /// Menu, popover, and dialog background. Allowed use: Raised application surfaces.
    pub const fn color_bg_elevated(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x20252dff),
            ThemeKind::Light => ColorValue::from_rgba(0xffffffff),
            ThemeKind::Dark => ColorValue::from_rgba(0x20252dff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x0a0a0aff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x282c33ff),
        }
    }

    /// Panel and card surface background. Allowed use: Unraised application surfaces.
    pub const fn color_bg_surface(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x181c22ff),
            ThemeKind::Light => ColorValue::from_rgba(0xffffffff),
            ThemeKind::Dark => ColorValue::from_rgba(0x181c22ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x000000ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x202329ff),
        }
    }

    /// Default terminal background. Allowed use: Terminal viewport only.
    pub const fn color_bg_terminal(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x0b0d10ff),
            ThemeKind::Light => ColorValue::from_rgba(0x111318ff),
            ThemeKind::Dark => ColorValue::from_rgba(0x0b0d10ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x000000ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x111318ff),
        }
    }

    /// Default control and divider border. Allowed use: Controls and structural dividers.
    pub const fn color_border_default(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x343b46ff),
            ThemeKind::Light => ColorValue::from_rgba(0xd7dce3ff),
            ThemeKind::Dark => ColorValue::from_rgba(0x343b46ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xffffffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x474c55ff),
        }
    }

    /// Strong selected or drop-target border. Allowed use: Selection and drag targets.
    pub const fn color_border_strong(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x657083ff),
            ThemeKind::Light => ColorValue::from_rgba(0x9aa4b2ff),
            ThemeKind::Dark => ColorValue::from_rgba(0x657083ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xffffffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x777d87ff),
        }
    }

    /// Keyboard focus outline. Allowed use: Visible focus indication.
    pub const fn color_focus(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x8fc7ffff),
            ThemeKind::Light => ColorValue::from_rgba(0x005fccff),
            ThemeKind::Dark => ColorValue::from_rgba(0x8fc7ffff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xffff00ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0xffffffff),
        }
    }

    /// Surface-colored separation inside the focus ring. Allowed use: Visible focus indication.
    pub const fn color_focus_separation(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x181c22ff),
            ThemeKind::Light => ColorValue::from_rgba(0xffffffff),
            ThemeKind::Dark => ColorValue::from_rgba(0x181c22ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x000000ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x202329ff),
        }
    }

    /// Modal overlay scrim. Allowed use: Modal separation only.
    pub const fn color_overlay_scrim(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x000000b3),
            ThemeKind::Light => ColorValue::from_rgba(0x11131899),
            ThemeKind::Dark => ColorValue::from_rgba(0x000000b3),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x000000e6),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x000000d9),
        }
    }

    /// Selected row and terminal selection background. Allowed use: Selected content.
    pub const fn color_selection(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x253a69ff),
            ThemeKind::Light => ColorValue::from_rgba(0xdce7ffff),
            ThemeKind::Dark => ColorValue::from_rgba(0x253a69ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x0033ffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x39465fff),
        }
    }

    /// Attention status color. Allowed use: Attention state with icon and text.
    pub const fn color_status_attention(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0xffb35cff),
            ThemeKind::Light => ColorValue::from_rgba(0xa65300ff),
            ThemeKind::Dark => ColorValue::from_rgba(0xffb35cff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xffff00ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0xd6b47aff),
        }
    }

    /// Busy status color. Allowed use: Busy state with icon and text.
    pub const fn color_status_busy(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x7ea2ffff),
            ThemeKind::Light => ColorValue::from_rgba(0x2457d6ff),
            ThemeKind::Dark => ColorValue::from_rgba(0x7ea2ffff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x00ffffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x8ca8e8ff),
        }
    }

    /// Done status color. Allowed use: Done state with icon and text.
    pub const fn color_status_done(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x4ed08aff),
            ThemeKind::Light => ColorValue::from_rgba(0x137a4bff),
            ThemeKind::Dark => ColorValue::from_rgba(0x4ed08aff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0x00ff66ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x8bc3a4ff),
        }
    }

    /// Error status color. Allowed use: Error state with icon and text.
    pub const fn color_status_error(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0xff7b83ff),
            ThemeKind::Light => ColorValue::from_rgba(0xb4232aff),
            ThemeKind::Dark => ColorValue::from_rgba(0xff7b83ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xff66ffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0xd99599ff),
        }
    }

    /// Idle status color. Allowed use: Idle state with icon and text.
    pub const fn color_status_idle(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x98a2b3ff),
            ThemeKind::Light => ColorValue::from_rgba(0x667085ff),
            ThemeKind::Dark => ColorValue::from_rgba(0x98a2b3ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xffffffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0xb7bbc2ff),
        }
    }

    /// Offline status color. Allowed use: Offline state with icon and text.
    pub const fn color_status_offline(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0xa7afbaff),
            ThemeKind::Light => ColorValue::from_rgba(0x5b6472ff),
            ThemeKind::Dark => ColorValue::from_rgba(0xa7afbaff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xffffffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0xa7abb1ff),
        }
    }

    /// Muted application text. Allowed use: Non-critical metadata.
    pub const fn color_text_muted(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0x909aa8ff),
            ThemeKind::Light => ColorValue::from_rgba(0x6c7583ff),
            ThemeKind::Dark => ColorValue::from_rgba(0x909aa8ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xd6d6d6ff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0x9fa5aeff),
        }
    }

    /// Primary application text. Allowed use: Body copy and headings.
    pub const fn color_text_primary(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0xf3f5f7ff),
            ThemeKind::Light => ColorValue::from_rgba(0x171a21ff),
            ThemeKind::Dark => ColorValue::from_rgba(0xf3f5f7ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xffffffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0xf4f5f6ff),
        }
    }

    /// Secondary application text. Allowed use: Supporting labels and copy.
    pub const fn color_text_secondary(self) -> ColorValue {
        match self.theme {
            ThemeKind::System => ColorValue::from_rgba(0xb6bec9ff),
            ThemeKind::Light => ColorValue::from_rgba(0x535b68ff),
            ThemeKind::Dark => ColorValue::from_rgba(0xb6bec9ff),
            ThemeKind::HighContrast => ColorValue::from_rgba(0xffffffff),
            ThemeKind::RecordingFriendly => ColorValue::from_rgba(0xc3c7cdff),
        }
    }

    /// Compact desktop control height. Allowed use: Compact controls that remain keyboard accessible.
    pub const fn control_height_compact(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(28.0f32),
            ThemeKind::Light => DimensionValue(28.0f32),
            ThemeKind::Dark => DimensionValue(28.0f32),
            ThemeKind::HighContrast => DimensionValue(28.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(28.0f32),
        }
    }

    /// Default desktop control height. Allowed use: Standard desktop controls.
    pub const fn control_height_default(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(36.0f32),
            ThemeKind::Light => DimensionValue(36.0f32),
            ThemeKind::Dark => DimensionValue(36.0f32),
            ThemeKind::HighContrast => DimensionValue(36.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(36.0f32),
        }
    }

    /// Large control height. Allowed use: Prominent or touch-compatible controls.
    pub const fn control_height_large(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(44.0f32),
            ThemeKind::Light => DimensionValue(44.0f32),
            ThemeKind::Dark => DimensionValue(44.0f32),
            ThemeKind::HighContrast => DimensionValue(44.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(44.0f32),
        }
    }

    /// Exit transition easing. Allowed use: Exiting transitions.
    pub const fn easing_exit(self) -> EasingValue {
        match self.theme {
            ThemeKind::System => EasingValue { x1: 0.4f32, y1: 0.0f32, x2: 1.0f32, y2: 1.0f32 },
            ThemeKind::Light => EasingValue { x1: 0.4f32, y1: 0.0f32, x2: 1.0f32, y2: 1.0f32 },
            ThemeKind::Dark => EasingValue { x1: 0.4f32, y1: 0.0f32, x2: 1.0f32, y2: 1.0f32 },
            ThemeKind::HighContrast => EasingValue { x1: 0.4f32, y1: 0.0f32, x2: 1.0f32, y2: 1.0f32 },
            ThemeKind::RecordingFriendly => EasingValue { x1: 0.4f32, y1: 0.0f32, x2: 1.0f32, y2: 1.0f32 },
        }
    }

    /// Standard UI transition easing. Allowed use: Entering and state-change transitions.
    pub const fn easing_standard(self) -> EasingValue {
        match self.theme {
            ThemeKind::System => EasingValue { x1: 0.2f32, y1: 0.0f32, x2: 0.0f32, y2: 1.0f32 },
            ThemeKind::Light => EasingValue { x1: 0.2f32, y1: 0.0f32, x2: 0.0f32, y2: 1.0f32 },
            ThemeKind::Dark => EasingValue { x1: 0.2f32, y1: 0.0f32, x2: 0.0f32, y2: 1.0f32 },
            ThemeKind::HighContrast => EasingValue { x1: 0.2f32, y1: 0.0f32, x2: 0.0f32, y2: 1.0f32 },
            ThemeKind::RecordingFriendly => EasingValue { x1: 0.2f32, y1: 0.0f32, x2: 0.0f32, y2: 1.0f32 },
        }
    }

    /// Modal elevation. Allowed use: Modal dialogs.
    pub const fn elevation_modal(self) -> ElevationValue {
        match self.theme {
            ThemeKind::System => ElevationValue(3),
            ThemeKind::Light => ElevationValue(3),
            ThemeKind::Dark => ElevationValue(3),
            ThemeKind::HighContrast => ElevationValue(0),
            ThemeKind::RecordingFriendly => ElevationValue(3),
        }
    }

    /// No elevation. Allowed use: Flat surfaces.
    pub const fn elevation_none(self) -> ElevationValue {
        match self.theme {
            ThemeKind::System => ElevationValue(0),
            ThemeKind::Light => ElevationValue(0),
            ThemeKind::Dark => ElevationValue(0),
            ThemeKind::HighContrast => ElevationValue(0),
            ThemeKind::RecordingFriendly => ElevationValue(0),
        }
    }

    /// Popover elevation. Allowed use: Popovers.
    pub const fn elevation_popover(self) -> ElevationValue {
        match self.theme {
            ThemeKind::System => ElevationValue(2),
            ThemeKind::Light => ElevationValue(2),
            ThemeKind::Dark => ElevationValue(2),
            ThemeKind::HighContrast => ElevationValue(0),
            ThemeKind::RecordingFriendly => ElevationValue(2),
        }
    }

    /// Menu and toolbar separator elevation. Allowed use: Menus and toolbar separators.
    pub const fn elevation_separator(self) -> ElevationValue {
        match self.theme {
            ThemeKind::System => ElevationValue(1),
            ThemeKind::Light => ElevationValue(1),
            ThemeKind::Dark => ElevationValue(1),
            ThemeKind::HighContrast => ElevationValue(0),
            ThemeKind::RecordingFriendly => ElevationValue(1),
        }
    }

    /// Focus ring surface separation. Allowed use: Keyboard focus indication.
    pub const fn focus_ring_offset(self) -> BorderValue {
        match self.theme {
            ThemeKind::System => BorderValue(2.0f32),
            ThemeKind::Light => BorderValue(2.0f32),
            ThemeKind::Dark => BorderValue(2.0f32),
            ThemeKind::HighContrast => BorderValue(2.0f32),
            ThemeKind::RecordingFriendly => BorderValue(2.0f32),
        }
    }

    /// Outer focus ring width. Allowed use: Keyboard focus indication.
    pub const fn focus_ring_width(self) -> BorderValue {
        match self.theme {
            ThemeKind::System => BorderValue(2.0f32),
            ThemeKind::Light => BorderValue(2.0f32),
            ThemeKind::Dark => BorderValue(2.0f32),
            ThemeKind::HighContrast => BorderValue(3.0f32),
            ThemeKind::RecordingFriendly => BorderValue(2.0f32),
        }
    }

    /// User-configurable installed monospace with platform fallback. Allowed use: Terminal and code content.
    pub const fn font_mono_family(self) -> FontFamilyValue {
        match self.theme {
            ThemeKind::System => FontFamilyValue("system-monospace"),
            ThemeKind::Light => FontFamilyValue("system-monospace"),
            ThemeKind::Dark => FontFamilyValue("system-monospace"),
            ThemeKind::HighContrast => FontFamilyValue("system-monospace"),
            ThemeKind::RecordingFriendly => FontFamilyValue("system-monospace"),
        }
    }

    /// Platform system UI font stack. Allowed use: Application chrome.
    pub const fn font_ui_family(self) -> FontFamilyValue {
        match self.theme {
            ThemeKind::System => FontFamilyValue("system-ui"),
            ThemeKind::Light => FontFamilyValue("system-ui"),
            ThemeKind::Dark => FontFamilyValue("system-ui"),
            ThemeKind::HighContrast => FontFamilyValue("system-ui"),
            ThemeKind::RecordingFriendly => FontFamilyValue("system-ui"),
        }
    }

    /// Default icon size. Allowed use: Controls and status icons.
    pub const fn icon_size_default(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(16.0f32),
            ThemeKind::Light => DimensionValue(16.0f32),
            ThemeKind::Dark => DimensionValue(16.0f32),
            ThemeKind::HighContrast => DimensionValue(16.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(16.0f32),
        }
    }

    /// Large icon size. Allowed use: Large state illustrations without provider branding.
    pub const fn icon_size_large(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(24.0f32),
            ThemeKind::Light => DimensionValue(24.0f32),
            ThemeKind::Dark => DimensionValue(24.0f32),
            ThemeKind::HighContrast => DimensionValue(24.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(24.0f32),
        }
    }

    /// Medium icon size. Allowed use: Prominent controls.
    pub const fn icon_size_medium(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(20.0f32),
            ThemeKind::Light => DimensionValue(20.0f32),
            ThemeKind::Dark => DimensionValue(20.0f32),
            ThemeKind::HighContrast => DimensionValue(20.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(20.0f32),
        }
    }

    /// Small icon size. Allowed use: Compact supplemental icons.
    pub const fn icon_size_small(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(12.0f32),
            ThemeKind::Light => DimensionValue(12.0f32),
            ThemeKind::Dark => DimensionValue(12.0f32),
            ThemeKind::HighContrast => DimensionValue(12.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(12.0f32),
        }
    }

    /// Exclamation diamond attention status icon. Allowed use: Attention status with text.
    pub const fn icon_status_attention(self) -> IconValue {
        match self.theme {
            ThemeKind::System => IconValue("exclamation_diamond"),
            ThemeKind::Light => IconValue("exclamation_diamond"),
            ThemeKind::Dark => IconValue("exclamation_diamond"),
            ThemeKind::HighContrast => IconValue("exclamation_diamond"),
            ThemeKind::RecordingFriendly => IconValue("exclamation_diamond"),
        }
    }

    /// Stepped spinner busy status icon. Allowed use: Busy status with text.
    pub const fn icon_status_busy(self) -> IconValue {
        match self.theme {
            ThemeKind::System => IconValue("stepped_spinner"),
            ThemeKind::Light => IconValue("stepped_spinner"),
            ThemeKind::Dark => IconValue("stepped_spinner"),
            ThemeKind::HighContrast => IconValue("stepped_spinner"),
            ThemeKind::RecordingFriendly => IconValue("stepped_spinner"),
        }
    }

    /// Check circle done status icon. Allowed use: Done status with text.
    pub const fn icon_status_done(self) -> IconValue {
        match self.theme {
            ThemeKind::System => IconValue("check_circle"),
            ThemeKind::Light => IconValue("check_circle"),
            ThemeKind::Dark => IconValue("check_circle"),
            ThemeKind::HighContrast => IconValue("check_circle"),
            ThemeKind::RecordingFriendly => IconValue("check_circle"),
        }
    }

    /// Octagon error status icon. Allowed use: Error status with text.
    pub const fn icon_status_error(self) -> IconValue {
        match self.theme {
            ThemeKind::System => IconValue("octagon"),
            ThemeKind::Light => IconValue("octagon"),
            ThemeKind::Dark => IconValue("octagon"),
            ThemeKind::HighContrast => IconValue("octagon"),
            ThemeKind::RecordingFriendly => IconValue("octagon"),
        }
    }

    /// Hollow circle idle status icon. Allowed use: Idle status with text.
    pub const fn icon_status_idle(self) -> IconValue {
        match self.theme {
            ThemeKind::System => IconValue("hollow_circle"),
            ThemeKind::Light => IconValue("hollow_circle"),
            ThemeKind::Dark => IconValue("hollow_circle"),
            ThemeKind::HighContrast => IconValue("hollow_circle"),
            ThemeKind::RecordingFriendly => IconValue("hollow_circle"),
        }
    }

    /// Broken link offline status icon. Allowed use: Offline status with text.
    pub const fn icon_status_offline(self) -> IconValue {
        match self.theme {
            ThemeKind::System => IconValue("broken_link"),
            ThemeKind::Light => IconValue("broken_link"),
            ThemeKind::Dark => IconValue("broken_link"),
            ThemeKind::HighContrast => IconValue("broken_link"),
            ThemeKind::RecordingFriendly => IconValue("broken_link"),
        }
    }

    /// Question diamond orphaned status icon. Allowed use: Unknown ownership status with text.
    pub const fn icon_status_orphaned(self) -> IconValue {
        match self.theme {
            ThemeKind::System => IconValue("question_diamond"),
            ThemeKind::Light => IconValue("question_diamond"),
            ThemeKind::Dark => IconValue("question_diamond"),
            ThemeKind::HighContrast => IconValue("question_diamond"),
            ThemeKind::RecordingFriendly => IconValue("question_diamond"),
        }
    }

    /// Lock permission-denied status icon. Allowed use: Permission denied status with text.
    pub const fn icon_status_permission_denied(self) -> IconValue {
        match self.theme {
            ThemeKind::System => IconValue("lock"),
            ThemeKind::Light => IconValue("lock"),
            ThemeKind::Dark => IconValue("lock"),
            ThemeKind::HighContrast => IconValue("lock"),
            ThemeKind::RecordingFriendly => IconValue("lock"),
        }
    }

    /// Default icon stroke width. Allowed use: Outline icons.
    pub const fn icon_stroke_default(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(1.5f32),
            ThemeKind::Light => DimensionValue(1.5f32),
            ThemeKind::Dark => DimensionValue(1.5f32),
            ThemeKind::HighContrast => DimensionValue(2.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(1.5f32),
        }
    }

    /// Desktop top chrome height. Allowed use: Desktop window chrome.
    pub const fn layout_chrome_height(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(44.0f32),
            ThemeKind::Light => DimensionValue(44.0f32),
            ThemeKind::Dark => DimensionValue(44.0f32),
            ThemeKind::HighContrast => DimensionValue(44.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(44.0f32),
        }
    }

    /// Current host-library sidebar width. Allowed use: Legacy host library until responsive sidebar migration.
    pub const fn layout_host_sidebar_width(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(220.0f32),
            ThemeKind::Light => DimensionValue(220.0f32),
            ThemeKind::Dark => DimensionValue(220.0f32),
            ThemeKind::HighContrast => DimensionValue(220.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(220.0f32),
        }
    }

    /// Default inspector width. Allowed use: Resizable desktop inspector.
    pub const fn layout_inspector_default(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(320.0f32),
            ThemeKind::Light => DimensionValue(320.0f32),
            ThemeKind::Dark => DimensionValue(320.0f32),
            ThemeKind::HighContrast => DimensionValue(320.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(320.0f32),
        }
    }

    /// Maximum inspector width. Allowed use: Resizable desktop inspector.
    pub const fn layout_inspector_maximum(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(480.0f32),
            ThemeKind::Light => DimensionValue(480.0f32),
            ThemeKind::Dark => DimensionValue(480.0f32),
            ThemeKind::HighContrast => DimensionValue(480.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(480.0f32),
        }
    }

    /// Minimum inspector width. Allowed use: Resizable desktop inspector.
    pub const fn layout_inspector_minimum(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(280.0f32),
            ThemeKind::Light => DimensionValue(280.0f32),
            ThemeKind::Dark => DimensionValue(280.0f32),
            ThemeKind::HighContrast => DimensionValue(280.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(280.0f32),
        }
    }

    /// Primary navigation rail width. Allowed use: Desktop navigation rail.
    pub const fn layout_navigation_width(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(52.0f32),
            ThemeKind::Light => DimensionValue(52.0f32),
            ThemeKind::Dark => DimensionValue(52.0f32),
            ThemeKind::HighContrast => DimensionValue(52.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(52.0f32),
        }
    }

    /// Default context sidebar width. Allowed use: Resizable desktop context sidebar.
    pub const fn layout_sidebar_default(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(280.0f32),
            ThemeKind::Light => DimensionValue(280.0f32),
            ThemeKind::Dark => DimensionValue(280.0f32),
            ThemeKind::HighContrast => DimensionValue(280.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(280.0f32),
        }
    }

    /// Maximum context sidebar width. Allowed use: Resizable desktop context sidebar.
    pub const fn layout_sidebar_maximum(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(420.0f32),
            ThemeKind::Light => DimensionValue(420.0f32),
            ThemeKind::Dark => DimensionValue(420.0f32),
            ThemeKind::HighContrast => DimensionValue(420.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(420.0f32),
        }
    }

    /// Minimum context sidebar width. Allowed use: Resizable desktop context sidebar.
    pub const fn layout_sidebar_minimum(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(220.0f32),
            ThemeKind::Light => DimensionValue(220.0f32),
            ThemeKind::Dark => DimensionValue(220.0f32),
            ThemeKind::HighContrast => DimensionValue(220.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(220.0f32),
        }
    }

    /// Compact status surface height. Allowed use: Legacy desktop status surfaces until screen migration.
    pub const fn layout_status_height(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(28.0f32),
            ThemeKind::Light => DimensionValue(28.0f32),
            ThemeKind::Dark => DimensionValue(28.0f32),
            ThemeKind::HighContrast => DimensionValue(28.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(28.0f32),
        }
    }

    /// Responsive desktop minimum window height target. Allowed use: Window constraints after responsive migration.
    pub const fn layout_window_minimum_height(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(640.0f32),
            ThemeKind::Light => DimensionValue(640.0f32),
            ThemeKind::Dark => DimensionValue(640.0f32),
            ThemeKind::HighContrast => DimensionValue(640.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(640.0f32),
        }
    }

    /// Responsive desktop minimum window width target. Allowed use: Window constraints after responsive migration.
    pub const fn layout_window_minimum_width(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(960.0f32),
            ThemeKind::Light => DimensionValue(960.0f32),
            ThemeKind::Dark => DimensionValue(960.0f32),
            ThemeKind::HighContrast => DimensionValue(960.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(960.0f32),
        }
    }

    /// Workspace header height. Allowed use: Desktop workspace headers.
    pub const fn layout_workspace_header_height(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(48.0f32),
            ThemeKind::Light => DimensionValue(48.0f32),
            ThemeKind::Dark => DimensionValue(48.0f32),
            ThemeKind::HighContrast => DimensionValue(48.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(48.0f32),
        }
    }

    /// Fast hover and focus transition. Allowed use: Non-spatial hover and focus feedback.
    pub const fn motion_fast(self, reduced_motion: bool) -> DurationValue {
        if reduced_motion { return self.motion_instant(false); }
        match self.theme {
            ThemeKind::System => DurationValue(100),
            ThemeKind::Light => DurationValue(100),
            ThemeKind::Dark => DurationValue(100),
            ThemeKind::HighContrast => DurationValue(100),
            ThemeKind::RecordingFriendly => DurationValue(100),
        }
    }

    /// Instant reduced-motion replacement. Allowed use: Reduced-motion replacement.
    pub const fn motion_instant(self, reduced_motion: bool) -> DurationValue {
        let _ = reduced_motion;
        match self.theme {
            ThemeKind::System => DurationValue(0),
            ThemeKind::Light => DurationValue(0),
            ThemeKind::Dark => DurationValue(0),
            ThemeKind::HighContrast => DurationValue(0),
            ThemeKind::RecordingFriendly => DurationValue(0),
        }
    }

    /// Menu and popover transition. Allowed use: Menu and popover transitions.
    pub const fn motion_normal(self, reduced_motion: bool) -> DurationValue {
        if reduced_motion { return self.motion_instant(false); }
        match self.theme {
            ThemeKind::System => DurationValue(160),
            ThemeKind::Light => DurationValue(160),
            ThemeKind::Dark => DurationValue(160),
            ThemeKind::HighContrast => DurationValue(160),
            ThemeKind::RecordingFriendly => DurationValue(160),
        }
    }

    /// Unknown-duration progress cycle. Allowed use: Spinner cycle with a discrete reduced-motion replacement.
    pub const fn motion_progress(self, reduced_motion: bool) -> DurationValue {
        if reduced_motion { return self.motion_instant(false); }
        match self.theme {
            ThemeKind::System => DurationValue(900),
            ThemeKind::Light => DurationValue(900),
            ThemeKind::Dark => DurationValue(900),
            ThemeKind::HighContrast => DurationValue(900),
            ThemeKind::RecordingFriendly => DurationValue(900),
        }
    }

    /// Panel transition. Allowed use: Panel transitions without bounce or parallax.
    pub const fn motion_slow(self, reduced_motion: bool) -> DurationValue {
        if reduced_motion { return self.motion_instant(false); }
        match self.theme {
            ThemeKind::System => DurationValue(240),
            ThemeKind::Light => DurationValue(240),
            ThemeKind::Dark => DurationValue(240),
            ThemeKind::HighContrast => DurationValue(240),
            ThemeKind::RecordingFriendly => DurationValue(240),
        }
    }

    /// Control corner radius. Allowed use: Buttons, inputs, and compact controls.
    pub const fn radius_control(self) -> RadiusValue {
        match self.theme {
            ThemeKind::System => RadiusValue(6.0f32),
            ThemeKind::Light => RadiusValue(6.0f32),
            ThemeKind::Dark => RadiusValue(6.0f32),
            ThemeKind::HighContrast => RadiusValue(6.0f32),
            ThemeKind::RecordingFriendly => RadiusValue(6.0f32),
        }
    }

    /// Dialog corner radius. Allowed use: Modal dialogs.
    pub const fn radius_dialog(self) -> RadiusValue {
        match self.theme {
            ThemeKind::System => RadiusValue(12.0f32),
            ThemeKind::Light => RadiusValue(12.0f32),
            ThemeKind::Dark => RadiusValue(12.0f32),
            ThemeKind::HighContrast => RadiusValue(12.0f32),
            ThemeKind::RecordingFriendly => RadiusValue(12.0f32),
        }
    }

    /// Panel corner radius. Allowed use: Individual repeated panels and cards.
    pub const fn radius_panel(self) -> RadiusValue {
        match self.theme {
            ThemeKind::System => RadiusValue(8.0f32),
            ThemeKind::Light => RadiusValue(8.0f32),
            ThemeKind::Dark => RadiusValue(8.0f32),
            ThemeKind::HighContrast => RadiusValue(8.0f32),
            ThemeKind::RecordingFriendly => RadiusValue(8.0f32),
        }
    }

    /// Pill radius reserved for tags and status chips. Allowed use: Tags and status chips only.
    pub const fn radius_pill(self) -> RadiusValue {
        match self.theme {
            ThemeKind::System => RadiusValue(999.0f32),
            ThemeKind::Light => RadiusValue(999.0f32),
            ThemeKind::Dark => RadiusValue(999.0f32),
            ThemeKind::HighContrast => RadiusValue(999.0f32),
            ThemeKind::RecordingFriendly => RadiusValue(999.0f32),
        }
    }

    /// Modal shadow. Allowed use: Modal dialogs.
    pub const fn shadow_modal(self) -> ShadowValue {
        match self.theme {
            ThemeKind::System => ShadowValue { x: 0.0f32, y: 8.0f32, blur: 24.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x00000066), visible: true },
            ThemeKind::Light => ShadowValue { x: 0.0f32, y: 8.0f32, blur: 24.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x11131833), visible: true },
            ThemeKind::Dark => ShadowValue { x: 0.0f32, y: 8.0f32, blur: 24.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x00000066), visible: true },
            ThemeKind::HighContrast => ShadowValue::NONE,
            ThemeKind::RecordingFriendly => ShadowValue { x: 0.0f32, y: 8.0f32, blur: 24.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x00000052), visible: true },
        }
    }

    /// No shadow. Allowed use: Flat and high-contrast surfaces.
    pub const fn shadow_none(self) -> ShadowValue {
        match self.theme {
            ThemeKind::System => ShadowValue::NONE,
            ThemeKind::Light => ShadowValue::NONE,
            ThemeKind::Dark => ShadowValue::NONE,
            ThemeKind::HighContrast => ShadowValue::NONE,
            ThemeKind::RecordingFriendly => ShadowValue::NONE,
        }
    }

    /// Popover shadow. Allowed use: Popovers.
    pub const fn shadow_popover(self) -> ShadowValue {
        match self.theme {
            ThemeKind::System => ShadowValue { x: 0.0f32, y: 4.0f32, blur: 12.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x0000004d), visible: true },
            ThemeKind::Light => ShadowValue { x: 0.0f32, y: 4.0f32, blur: 12.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x11131829), visible: true },
            ThemeKind::Dark => ShadowValue { x: 0.0f32, y: 4.0f32, blur: 12.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x0000004d), visible: true },
            ThemeKind::HighContrast => ShadowValue::NONE,
            ThemeKind::RecordingFriendly => ShadowValue { x: 0.0f32, y: 4.0f32, blur: 12.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x0000003d), visible: true },
        }
    }

    /// Subtle menu and toolbar separator shadow. Allowed use: Menus and toolbar separators.
    pub const fn shadow_separator(self) -> ShadowValue {
        match self.theme {
            ThemeKind::System => ShadowValue { x: 0.0f32, y: 1.0f32, blur: 2.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x00000033), visible: true },
            ThemeKind::Light => ShadowValue { x: 0.0f32, y: 1.0f32, blur: 2.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x1113181f), visible: true },
            ThemeKind::Dark => ShadowValue { x: 0.0f32, y: 1.0f32, blur: 2.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x00000033), visible: true },
            ThemeKind::HighContrast => ShadowValue::NONE,
            ThemeKind::RecordingFriendly => ShadowValue { x: 0.0f32, y: 1.0f32, blur: 2.0f32, spread: 0.0f32, color: ColorValue::from_rgba(0x00000026), visible: true },
        }
    }

    /// Zero spacing. Allowed use: Explicitly remove spacing.
    pub const fn space_0(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(0.0f32),
            ThemeKind::Light => SpacingValue(0.0f32),
            ThemeKind::Dark => SpacingValue(0.0f32),
            ThemeKind::HighContrast => SpacingValue(0.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(0.0f32),
        }
    }

    /// Two-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_1(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(2.0f32),
            ThemeKind::Light => SpacingValue(2.0f32),
            ThemeKind::Dark => SpacingValue(2.0f32),
            ThemeKind::HighContrast => SpacingValue(2.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(2.0f32),
        }
    }

    /// Four-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_2(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(4.0f32),
            ThemeKind::Light => SpacingValue(4.0f32),
            ThemeKind::Dark => SpacingValue(4.0f32),
            ThemeKind::HighContrast => SpacingValue(4.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(4.0f32),
        }
    }

    /// Eight-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_3(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(8.0f32),
            ThemeKind::Light => SpacingValue(8.0f32),
            ThemeKind::Dark => SpacingValue(8.0f32),
            ThemeKind::HighContrast => SpacingValue(8.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(8.0f32),
        }
    }

    /// Twelve-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_4(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(12.0f32),
            ThemeKind::Light => SpacingValue(12.0f32),
            ThemeKind::Dark => SpacingValue(12.0f32),
            ThemeKind::HighContrast => SpacingValue(12.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(12.0f32),
        }
    }

    /// Sixteen-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_5(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(16.0f32),
            ThemeKind::Light => SpacingValue(16.0f32),
            ThemeKind::Dark => SpacingValue(16.0f32),
            ThemeKind::HighContrast => SpacingValue(16.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(16.0f32),
        }
    }

    /// Twenty-four-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_6(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(24.0f32),
            ThemeKind::Light => SpacingValue(24.0f32),
            ThemeKind::Dark => SpacingValue(24.0f32),
            ThemeKind::HighContrast => SpacingValue(24.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(24.0f32),
        }
    }

    /// Thirty-two-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_7(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(32.0f32),
            ThemeKind::Light => SpacingValue(32.0f32),
            ThemeKind::Dark => SpacingValue(32.0f32),
            ThemeKind::HighContrast => SpacingValue(32.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(32.0f32),
        }
    }

    /// Forty-eight-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_8(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(48.0f32),
            ThemeKind::Light => SpacingValue(48.0f32),
            ThemeKind::Dark => SpacingValue(48.0f32),
            ThemeKind::HighContrast => SpacingValue(48.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(48.0f32),
        }
    }

    /// Sixty-four-pixel spacing step. Allowed use: Global spacing scale.
    pub const fn space_9(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(64.0f32),
            ThemeKind::Light => SpacingValue(64.0f32),
            ThemeKind::Dark => SpacingValue(64.0f32),
            ThemeKind::HighContrast => SpacingValue(64.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(64.0f32),
        }
    }

    /// Terminal viewport padding. Allowed use: Terminal viewport padding only.
    pub const fn space_terminal_padding(self) -> SpacingValue {
        match self.theme {
            ThemeKind::System => SpacingValue(8.0f32),
            ThemeKind::Light => SpacingValue(8.0f32),
            ThemeKind::Dark => SpacingValue(8.0f32),
            ThemeKind::HighContrast => SpacingValue(8.0f32),
            ThemeKind::RecordingFriendly => SpacingValue(8.0f32),
        }
    }

    /// Minimum desktop pointer target. Allowed use: Desktop interactive controls.
    pub const fn target_pointer_minimum(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(36.0f32),
            ThemeKind::Light => DimensionValue(36.0f32),
            ThemeKind::Dark => DimensionValue(36.0f32),
            ThemeKind::HighContrast => DimensionValue(36.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(36.0f32),
        }
    }

    /// Minimum touch target. Allowed use: Touch-capable controls.
    pub const fn target_touch_minimum(self) -> DimensionValue {
        match self.theme {
            ThemeKind::System => DimensionValue(44.0f32),
            ThemeKind::Light => DimensionValue(44.0f32),
            ThemeKind::Dark => DimensionValue(44.0f32),
            ThemeKind::HighContrast => DimensionValue(44.0f32),
            ThemeKind::RecordingFriendly => DimensionValue(44.0f32),
        }
    }

    /// Stable developer localization ID for attention status. Allowed use: Localization lookup only.
    pub const fn text_status_attention(self) -> TextValue {
        match self.theme {
            ThemeKind::System => TextValue("status.attention"),
            ThemeKind::Light => TextValue("status.attention"),
            ThemeKind::Dark => TextValue("status.attention"),
            ThemeKind::HighContrast => TextValue("status.attention"),
            ThemeKind::RecordingFriendly => TextValue("status.attention"),
        }
    }

    /// Stable developer localization ID for busy status. Allowed use: Localization lookup only.
    pub const fn text_status_busy(self) -> TextValue {
        match self.theme {
            ThemeKind::System => TextValue("status.busy"),
            ThemeKind::Light => TextValue("status.busy"),
            ThemeKind::Dark => TextValue("status.busy"),
            ThemeKind::HighContrast => TextValue("status.busy"),
            ThemeKind::RecordingFriendly => TextValue("status.busy"),
        }
    }

    /// Stable developer localization ID for done status. Allowed use: Localization lookup only.
    pub const fn text_status_done(self) -> TextValue {
        match self.theme {
            ThemeKind::System => TextValue("status.done"),
            ThemeKind::Light => TextValue("status.done"),
            ThemeKind::Dark => TextValue("status.done"),
            ThemeKind::HighContrast => TextValue("status.done"),
            ThemeKind::RecordingFriendly => TextValue("status.done"),
        }
    }

    /// Stable developer localization ID for error status. Allowed use: Localization lookup only.
    pub const fn text_status_error(self) -> TextValue {
        match self.theme {
            ThemeKind::System => TextValue("status.error"),
            ThemeKind::Light => TextValue("status.error"),
            ThemeKind::Dark => TextValue("status.error"),
            ThemeKind::HighContrast => TextValue("status.error"),
            ThemeKind::RecordingFriendly => TextValue("status.error"),
        }
    }

    /// Stable developer localization ID for idle status. Allowed use: Localization lookup only.
    pub const fn text_status_idle(self) -> TextValue {
        match self.theme {
            ThemeKind::System => TextValue("status.idle"),
            ThemeKind::Light => TextValue("status.idle"),
            ThemeKind::Dark => TextValue("status.idle"),
            ThemeKind::HighContrast => TextValue("status.idle"),
            ThemeKind::RecordingFriendly => TextValue("status.idle"),
        }
    }

    /// Stable developer localization ID for offline status. Allowed use: Localization lookup only.
    pub const fn text_status_offline(self) -> TextValue {
        match self.theme {
            ThemeKind::System => TextValue("status.offline"),
            ThemeKind::Light => TextValue("status.offline"),
            ThemeKind::Dark => TextValue("status.offline"),
            ThemeKind::HighContrast => TextValue("status.offline"),
            ThemeKind::RecordingFriendly => TextValue("status.offline"),
        }
    }

    /// Stable developer localization ID for orphaned status. Allowed use: Localization lookup only.
    pub const fn text_status_orphaned(self) -> TextValue {
        match self.theme {
            ThemeKind::System => TextValue("status.orphaned"),
            ThemeKind::Light => TextValue("status.orphaned"),
            ThemeKind::Dark => TextValue("status.orphaned"),
            ThemeKind::HighContrast => TextValue("status.orphaned"),
            ThemeKind::RecordingFriendly => TextValue("status.orphaned"),
        }
    }

    /// Stable developer localization ID for permission-denied status. Allowed use: Localization lookup only.
    pub const fn text_status_permission_denied(self) -> TextValue {
        match self.theme {
            ThemeKind::System => TextValue("status.permission_denied"),
            ThemeKind::Light => TextValue("status.permission_denied"),
            ThemeKind::Dark => TextValue("status.permission_denied"),
            ThemeKind::HighContrast => TextValue("status.permission_denied"),
            ThemeKind::RecordingFriendly => TextValue("status.permission_denied"),
        }
    }

    /// Default body typography. Allowed use: Application body copy.
    pub const fn type_body(self) -> TypographyValue {
        match self.theme {
            ThemeKind::System => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 400 },
            ThemeKind::Light => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 400 },
            ThemeKind::Dark => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 400 },
            ThemeKind::HighContrast => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 400 },
            ThemeKind::RecordingFriendly => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 400 },
        }
    }

    /// Small body typography. Allowed use: Dense supporting copy.
    pub const fn type_body_small(self) -> TypographyValue {
        match self.theme {
            ThemeKind::System => TypographyValue { size: 13.0f32, line_height: 18.0f32, weight: 400 },
            ThemeKind::Light => TypographyValue { size: 13.0f32, line_height: 18.0f32, weight: 400 },
            ThemeKind::Dark => TypographyValue { size: 13.0f32, line_height: 18.0f32, weight: 400 },
            ThemeKind::HighContrast => TypographyValue { size: 13.0f32, line_height: 18.0f32, weight: 400 },
            ThemeKind::RecordingFriendly => TypographyValue { size: 13.0f32, line_height: 18.0f32, weight: 400 },
        }
    }

    /// Caption typography. Allowed use: Compact metadata.
    pub const fn type_caption(self) -> TypographyValue {
        match self.theme {
            ThemeKind::System => TypographyValue { size: 12.0f32, line_height: 16.0f32, weight: 500 },
            ThemeKind::Light => TypographyValue { size: 12.0f32, line_height: 16.0f32, weight: 500 },
            ThemeKind::Dark => TypographyValue { size: 12.0f32, line_height: 16.0f32, weight: 500 },
            ThemeKind::HighContrast => TypographyValue { size: 12.0f32, line_height: 16.0f32, weight: 500 },
            ThemeKind::RecordingFriendly => TypographyValue { size: 12.0f32, line_height: 16.0f32, weight: 500 },
        }
    }

    /// Heading typography. Allowed use: Primary section headings.
    pub const fn type_heading(self) -> TypographyValue {
        match self.theme {
            ThemeKind::System => TypographyValue { size: 20.0f32, line_height: 28.0f32, weight: 650 },
            ThemeKind::Light => TypographyValue { size: 20.0f32, line_height: 28.0f32, weight: 650 },
            ThemeKind::Dark => TypographyValue { size: 20.0f32, line_height: 28.0f32, weight: 650 },
            ThemeKind::HighContrast => TypographyValue { size: 20.0f32, line_height: 28.0f32, weight: 650 },
            ThemeKind::RecordingFriendly => TypographyValue { size: 20.0f32, line_height: 28.0f32, weight: 650 },
        }
    }

    /// Small heading typography. Allowed use: Section headings.
    pub const fn type_heading_small(self) -> TypographyValue {
        match self.theme {
            ThemeKind::System => TypographyValue { size: 16.0f32, line_height: 22.0f32, weight: 600 },
            ThemeKind::Light => TypographyValue { size: 16.0f32, line_height: 22.0f32, weight: 600 },
            ThemeKind::Dark => TypographyValue { size: 16.0f32, line_height: 22.0f32, weight: 600 },
            ThemeKind::HighContrast => TypographyValue { size: 16.0f32, line_height: 22.0f32, weight: 600 },
            ThemeKind::RecordingFriendly => TypographyValue { size: 16.0f32, line_height: 22.0f32, weight: 600 },
        }
    }

    /// Control label typography. Allowed use: Control and row labels.
    pub const fn type_label(self) -> TypographyValue {
        match self.theme {
            ThemeKind::System => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 600 },
            ThemeKind::Light => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 600 },
            ThemeKind::Dark => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 600 },
            ThemeKind::HighContrast => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 600 },
            ThemeKind::RecordingFriendly => TypographyValue { size: 14.0f32, line_height: 20.0f32, weight: 600 },
        }
    }

    /// Default terminal typography before user scaling. Allowed use: Terminal viewport only; font size remains user-configurable.
    pub const fn type_terminal(self) -> TypographyValue {
        match self.theme {
            ThemeKind::System => TypographyValue { size: 14.0f32, line_height: 18.9f32, weight: 400 },
            ThemeKind::Light => TypographyValue { size: 14.0f32, line_height: 18.9f32, weight: 400 },
            ThemeKind::Dark => TypographyValue { size: 14.0f32, line_height: 18.9f32, weight: 400 },
            ThemeKind::HighContrast => TypographyValue { size: 14.0f32, line_height: 18.9f32, weight: 400 },
            ThemeKind::RecordingFriendly => TypographyValue { size: 14.0f32, line_height: 18.9f32, weight: 400 },
        }
    }

    /// Page title typography. Allowed use: Top-level page titles.
    pub const fn type_title(self) -> TypographyValue {
        match self.theme {
            ThemeKind::System => TypographyValue { size: 28.0f32, line_height: 36.0f32, weight: 700 },
            ThemeKind::Light => TypographyValue { size: 28.0f32, line_height: 36.0f32, weight: 700 },
            ThemeKind::Dark => TypographyValue { size: 28.0f32, line_height: 36.0f32, weight: 700 },
            ThemeKind::HighContrast => TypographyValue { size: 28.0f32, line_height: 36.0f32, weight: 700 },
            ThemeKind::RecordingFriendly => TypographyValue { size: 28.0f32, line_height: 36.0f32, weight: 700 },
        }
    }

    /// Base content layer. Allowed use: Normal application content.
    pub const fn z_base(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(0),
            ThemeKind::Light => ZIndexValue(0),
            ThemeKind::Dark => ZIndexValue(0),
            ThemeKind::HighContrast => ZIndexValue(0),
            ThemeKind::RecordingFriendly => ZIndexValue(0),
        }
    }

    /// Drag preview layer. Allowed use: Drag previews only.
    pub const fn z_drag(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(700),
            ThemeKind::Light => ZIndexValue(700),
            ThemeKind::Dark => ZIndexValue(700),
            ThemeKind::HighContrast => ZIndexValue(700),
            ThemeKind::RecordingFriendly => ZIndexValue(700),
        }
    }

    /// Dropdown layer. Allowed use: Dropdown menus.
    pub const fn z_dropdown(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(100),
            ThemeKind::Light => ZIndexValue(100),
            ThemeKind::Dark => ZIndexValue(100),
            ThemeKind::HighContrast => ZIndexValue(100),
            ThemeKind::RecordingFriendly => ZIndexValue(100),
        }
    }

    /// Modal dialog layer. Allowed use: Modal dialogs.
    pub const fn z_modal(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(410),
            ThemeKind::Light => ZIndexValue(410),
            ThemeKind::Dark => ZIndexValue(410),
            ThemeKind::HighContrast => ZIndexValue(410),
            ThemeKind::RecordingFriendly => ZIndexValue(410),
        }
    }

    /// Modal scrim layer. Allowed use: Modal scrims.
    pub const fn z_modal_scrim(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(400),
            ThemeKind::Light => ZIndexValue(400),
            ThemeKind::Dark => ZIndexValue(400),
            ThemeKind::HighContrast => ZIndexValue(400),
            ThemeKind::RecordingFriendly => ZIndexValue(400),
        }
    }

    /// Popover layer. Allowed use: Popovers.
    pub const fn z_popover(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(200),
            ThemeKind::Light => ZIndexValue(200),
            ThemeKind::Dark => ZIndexValue(200),
            ThemeKind::HighContrast => ZIndexValue(200),
            ThemeKind::RecordingFriendly => ZIndexValue(200),
        }
    }

    /// Security prompt layer. Allowed use: Security and exact approval prompts.
    pub const fn z_security_prompt(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(500),
            ThemeKind::Light => ZIndexValue(500),
            ThemeKind::Dark => ZIndexValue(500),
            ThemeKind::HighContrast => ZIndexValue(500),
            ThemeKind::RecordingFriendly => ZIndexValue(500),
        }
    }

    /// Sticky application chrome layer. Allowed use: Sticky headers and rails.
    pub const fn z_sticky(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(10),
            ThemeKind::Light => ZIndexValue(10),
            ThemeKind::Dark => ZIndexValue(10),
            ThemeKind::HighContrast => ZIndexValue(10),
            ThemeKind::RecordingFriendly => ZIndexValue(10),
        }
    }

    /// Toast layer. Allowed use: In-app notifications.
    pub const fn z_toast(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(300),
            ThemeKind::Light => ZIndexValue(300),
            ThemeKind::Dark => ZIndexValue(300),
            ThemeKind::HighContrast => ZIndexValue(300),
            ThemeKind::RecordingFriendly => ZIndexValue(300),
        }
    }

    /// Tooltip layer. Allowed use: Tooltips.
    pub const fn z_tooltip(self) -> ZIndexValue {
        match self.theme {
            ThemeKind::System => ZIndexValue(600),
            ThemeKind::Light => ZIndexValue(600),
            ThemeKind::Dark => ZIndexValue(600),
            ThemeKind::HighContrast => ZIndexValue(600),
            ThemeKind::RecordingFriendly => ZIndexValue(600),
        }
    }

    pub const fn status(self, kind: StatusKind) -> StatusVisual {
        match kind {
            StatusKind::Attention => StatusVisual { color: self.color_status_attention(), icon: self.icon_status_attention(), text: self.text_status_attention(), shape: "diamond" },
            StatusKind::Busy => StatusVisual { color: self.color_status_busy(), icon: self.icon_status_busy(), text: self.text_status_busy(), shape: "filled_circle" },
            StatusKind::Done => StatusVisual { color: self.color_status_done(), icon: self.icon_status_done(), text: self.text_status_done(), shape: "check_circle" },
            StatusKind::Error => StatusVisual { color: self.color_status_error(), icon: self.icon_status_error(), text: self.text_status_error(), shape: "octagon" },
            StatusKind::Idle => StatusVisual { color: self.color_status_idle(), icon: self.icon_status_idle(), text: self.text_status_idle(), shape: "hollow_circle" },
            StatusKind::Offline => StatusVisual { color: self.color_status_offline(), icon: self.icon_status_offline(), text: self.text_status_offline(), shape: "broken_link" },
            StatusKind::Orphaned => StatusVisual { color: self.color_status_attention(), icon: self.icon_status_orphaned(), text: self.text_status_orphaned(), shape: "question_diamond" },
            StatusKind::PermissionDenied => StatusVisual { color: self.color_status_error(), icon: self.icon_status_permission_denied(), text: self.text_status_permission_denied(), shape: "lock" },
        }
    }
}
}

pub use token_data::*;
