// @generated by generate-messages. Do not edit.
// Source SHA-256: 6a9d7f32c8692081dab914f258219faffafa05411803fe1c7196c5dfdae03708

use super::{
    ArgSpec, Argument, ArgumentType, ArgumentValue, BidiRule, ByteSize, Count, DateTime, KeyName,
    MessageArguments, MessageSpec, Sensitivity, Text, UserData,
};

pub const MESSAGE_SCHEMA_VERSION: u16 = 1;
pub const MESSAGE_SOURCE_SHA256: &str =
    "6a9d7f32c8692081dab914f258219faffafa05411803fe1c7196c5dfdae03708";

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum MessageId {
    CommonCancel,
    CommonClose,
    CommonConnect,
    CommonDelete,
    CommonRetry,
    CommonRun,
    CommonSave,
    DevelopmentLocaleActive,
    DevelopmentLocalizationHint,
    DevelopmentLocalizationTitle,
    FieldError,
    LastUpdated,
    PathUnavailable,
    PresetAcceptAction,
    PresetAcceptedStatus,
    PresetArgumentAdd,
    PresetArgumentCount,
    PresetArgumentRemove,
    PresetArgumentsField,
    PresetDeleteAction,
    PresetDetectedVersion,
    PresetEditAction,
    PresetEnabledField,
    PresetErrorInvalid,
    PresetErrorRiskConfirm,
    PresetErrorStale,
    PresetExecutableField,
    PresetFavoriteField,
    PresetFormTitleEdit,
    PresetFormTitleNew,
    PresetLabelField,
    PresetMoveDownAction,
    PresetMoveUpAction,
    PresetPermissionAsk,
    PresetPermissionField,
    PresetPermissionReadOnly,
    PresetPermissionWorkspaceWrite,
    PresetRemovedStatus,
    PresetRiskConfirmField,
    PresetRiskWarning,
    PresetSafeCopy,
    PresetSaveAction,
    PresetSavedStatus,
    PresetStatusDisabled,
    PresetStatusFailed,
    PresetStatusMissing,
    PresetStatusPermission,
    PresetStatusRisky,
    PresetStatusSupported,
    PresetStatusTimeout,
    PresetStatusUnknown,
    PresetStatusUnsupported,
    PresetStoreCorrupt,
    PresetStoreNewer,
    PresetStoreRecovered,
    PresetStoreUnavailable,
    PresetSubdirectoryField,
    PresetWorkingDirectoryField,
    PresetWorkingHome,
    PresetWorkingProjectRoot,
    PresetWorkingSubdirectory,
    PresetsAddAction,
    PresetsDetectedTitle,
    PresetsEmptyDescription,
    PresetsEmptyTitle,
    PresetsNavLabel,
    PresetsReadyStatus,
    PresetsScanAction,
    PresetsScanCancelled,
    PresetsScanNone,
    PresetsScanPartial,
    PresetsScanning,
    PresetsSubtitle,
    PresetsTitle,
    ProjectAddConfirm,
    ProjectAddedStatus,
    ProjectDuplicateStatus,
    ProjectErrorEmptyPath,
    ProjectErrorGeneric,
    ProjectErrorInvalidLabel,
    ProjectErrorNotDirectory,
    ProjectErrorPathTooLong,
    ProjectErrorPermissionDenied,
    ProjectErrorStale,
    ProjectErrorUnavailable,
    ProjectFilesStay,
    ProjectLabelField,
    ProjectRemoveAction,
    ProjectRemovedStatus,
    ProjectRestoredStatus,
    ProjectReviewDescription,
    ProjectReviewTitle,
    ProjectStatusAvailable,
    ProjectStatusPermissionDenied,
    ProjectStatusUnavailable,
    ProjectStoreCorrupt,
    ProjectStoreNewer,
    ProjectStoreRecovered,
    ProjectStoreUnavailable,
    ProjectUndoAction,
    ProjectUndoExpired,
    ProjectValidating,
    ProjectsAddAction,
    ProjectsEmptyDescription,
    ProjectsEmptyTitle,
    ProjectsFolderSafety,
    ProjectsLoading,
    ProjectsLocalOnly,
    ProjectsNavLabel,
    ProjectsReadyStatus,
    ProjectsShortcutDescription,
    ProjectsSubtitle,
    ProjectsTitle,
    RuntimeLabelClaude,
    RuntimeLabelCodex,
    RuntimeLabelGemini,
    SessionCount,
    ShortcutHint,
    StatusConnecting,
    StatusReady,
    TransferSummary,
}

impl MessageId {
    pub const ALL: &'static [Self] = &[
        Self::CommonCancel,
        Self::CommonClose,
        Self::CommonConnect,
        Self::CommonDelete,
        Self::CommonRetry,
        Self::CommonRun,
        Self::CommonSave,
        Self::DevelopmentLocaleActive,
        Self::DevelopmentLocalizationHint,
        Self::DevelopmentLocalizationTitle,
        Self::FieldError,
        Self::LastUpdated,
        Self::PathUnavailable,
        Self::PresetAcceptAction,
        Self::PresetAcceptedStatus,
        Self::PresetArgumentAdd,
        Self::PresetArgumentCount,
        Self::PresetArgumentRemove,
        Self::PresetArgumentsField,
        Self::PresetDeleteAction,
        Self::PresetDetectedVersion,
        Self::PresetEditAction,
        Self::PresetEnabledField,
        Self::PresetErrorInvalid,
        Self::PresetErrorRiskConfirm,
        Self::PresetErrorStale,
        Self::PresetExecutableField,
        Self::PresetFavoriteField,
        Self::PresetFormTitleEdit,
        Self::PresetFormTitleNew,
        Self::PresetLabelField,
        Self::PresetMoveDownAction,
        Self::PresetMoveUpAction,
        Self::PresetPermissionAsk,
        Self::PresetPermissionField,
        Self::PresetPermissionReadOnly,
        Self::PresetPermissionWorkspaceWrite,
        Self::PresetRemovedStatus,
        Self::PresetRiskConfirmField,
        Self::PresetRiskWarning,
        Self::PresetSafeCopy,
        Self::PresetSaveAction,
        Self::PresetSavedStatus,
        Self::PresetStatusDisabled,
        Self::PresetStatusFailed,
        Self::PresetStatusMissing,
        Self::PresetStatusPermission,
        Self::PresetStatusRisky,
        Self::PresetStatusSupported,
        Self::PresetStatusTimeout,
        Self::PresetStatusUnknown,
        Self::PresetStatusUnsupported,
        Self::PresetStoreCorrupt,
        Self::PresetStoreNewer,
        Self::PresetStoreRecovered,
        Self::PresetStoreUnavailable,
        Self::PresetSubdirectoryField,
        Self::PresetWorkingDirectoryField,
        Self::PresetWorkingHome,
        Self::PresetWorkingProjectRoot,
        Self::PresetWorkingSubdirectory,
        Self::PresetsAddAction,
        Self::PresetsDetectedTitle,
        Self::PresetsEmptyDescription,
        Self::PresetsEmptyTitle,
        Self::PresetsNavLabel,
        Self::PresetsReadyStatus,
        Self::PresetsScanAction,
        Self::PresetsScanCancelled,
        Self::PresetsScanNone,
        Self::PresetsScanPartial,
        Self::PresetsScanning,
        Self::PresetsSubtitle,
        Self::PresetsTitle,
        Self::ProjectAddConfirm,
        Self::ProjectAddedStatus,
        Self::ProjectDuplicateStatus,
        Self::ProjectErrorEmptyPath,
        Self::ProjectErrorGeneric,
        Self::ProjectErrorInvalidLabel,
        Self::ProjectErrorNotDirectory,
        Self::ProjectErrorPathTooLong,
        Self::ProjectErrorPermissionDenied,
        Self::ProjectErrorStale,
        Self::ProjectErrorUnavailable,
        Self::ProjectFilesStay,
        Self::ProjectLabelField,
        Self::ProjectRemoveAction,
        Self::ProjectRemovedStatus,
        Self::ProjectRestoredStatus,
        Self::ProjectReviewDescription,
        Self::ProjectReviewTitle,
        Self::ProjectStatusAvailable,
        Self::ProjectStatusPermissionDenied,
        Self::ProjectStatusUnavailable,
        Self::ProjectStoreCorrupt,
        Self::ProjectStoreNewer,
        Self::ProjectStoreRecovered,
        Self::ProjectStoreUnavailable,
        Self::ProjectUndoAction,
        Self::ProjectUndoExpired,
        Self::ProjectValidating,
        Self::ProjectsAddAction,
        Self::ProjectsEmptyDescription,
        Self::ProjectsEmptyTitle,
        Self::ProjectsFolderSafety,
        Self::ProjectsLoading,
        Self::ProjectsLocalOnly,
        Self::ProjectsNavLabel,
        Self::ProjectsReadyStatus,
        Self::ProjectsShortcutDescription,
        Self::ProjectsSubtitle,
        Self::ProjectsTitle,
        Self::RuntimeLabelClaude,
        Self::RuntimeLabelCodex,
        Self::RuntimeLabelGemini,
        Self::SessionCount,
        Self::ShortcutHint,
        Self::StatusConnecting,
        Self::StatusReady,
        Self::TransferSummary,
    ];

    pub const fn key(self) -> &'static str {
        match self {
            Self::CommonCancel => "common-cancel",
            Self::CommonClose => "common-close",
            Self::CommonConnect => "common-connect",
            Self::CommonDelete => "common-delete",
            Self::CommonRetry => "common-retry",
            Self::CommonRun => "common-run",
            Self::CommonSave => "common-save",
            Self::DevelopmentLocaleActive => "development-locale-active",
            Self::DevelopmentLocalizationHint => "development-localization-hint",
            Self::DevelopmentLocalizationTitle => "development-localization-title",
            Self::FieldError => "field-error",
            Self::LastUpdated => "last-updated",
            Self::PathUnavailable => "path-unavailable",
            Self::PresetAcceptAction => "preset-accept-action",
            Self::PresetAcceptedStatus => "preset-accepted-status",
            Self::PresetArgumentAdd => "preset-argument-add",
            Self::PresetArgumentCount => "preset-argument-count",
            Self::PresetArgumentRemove => "preset-argument-remove",
            Self::PresetArgumentsField => "preset-arguments-field",
            Self::PresetDeleteAction => "preset-delete-action",
            Self::PresetDetectedVersion => "preset-detected-version",
            Self::PresetEditAction => "preset-edit-action",
            Self::PresetEnabledField => "preset-enabled-field",
            Self::PresetErrorInvalid => "preset-error-invalid",
            Self::PresetErrorRiskConfirm => "preset-error-risk-confirm",
            Self::PresetErrorStale => "preset-error-stale",
            Self::PresetExecutableField => "preset-executable-field",
            Self::PresetFavoriteField => "preset-favorite-field",
            Self::PresetFormTitleEdit => "preset-form-title-edit",
            Self::PresetFormTitleNew => "preset-form-title-new",
            Self::PresetLabelField => "preset-label-field",
            Self::PresetMoveDownAction => "preset-move-down-action",
            Self::PresetMoveUpAction => "preset-move-up-action",
            Self::PresetPermissionAsk => "preset-permission-ask",
            Self::PresetPermissionField => "preset-permission-field",
            Self::PresetPermissionReadOnly => "preset-permission-read-only",
            Self::PresetPermissionWorkspaceWrite => "preset-permission-workspace-write",
            Self::PresetRemovedStatus => "preset-removed-status",
            Self::PresetRiskConfirmField => "preset-risk-confirm-field",
            Self::PresetRiskWarning => "preset-risk-warning",
            Self::PresetSafeCopy => "preset-safe-copy",
            Self::PresetSaveAction => "preset-save-action",
            Self::PresetSavedStatus => "preset-saved-status",
            Self::PresetStatusDisabled => "preset-status-disabled",
            Self::PresetStatusFailed => "preset-status-failed",
            Self::PresetStatusMissing => "preset-status-missing",
            Self::PresetStatusPermission => "preset-status-permission",
            Self::PresetStatusRisky => "preset-status-risky",
            Self::PresetStatusSupported => "preset-status-supported",
            Self::PresetStatusTimeout => "preset-status-timeout",
            Self::PresetStatusUnknown => "preset-status-unknown",
            Self::PresetStatusUnsupported => "preset-status-unsupported",
            Self::PresetStoreCorrupt => "preset-store-corrupt",
            Self::PresetStoreNewer => "preset-store-newer",
            Self::PresetStoreRecovered => "preset-store-recovered",
            Self::PresetStoreUnavailable => "preset-store-unavailable",
            Self::PresetSubdirectoryField => "preset-subdirectory-field",
            Self::PresetWorkingDirectoryField => "preset-working-directory-field",
            Self::PresetWorkingHome => "preset-working-home",
            Self::PresetWorkingProjectRoot => "preset-working-project-root",
            Self::PresetWorkingSubdirectory => "preset-working-subdirectory",
            Self::PresetsAddAction => "presets-add-action",
            Self::PresetsDetectedTitle => "presets-detected-title",
            Self::PresetsEmptyDescription => "presets-empty-description",
            Self::PresetsEmptyTitle => "presets-empty-title",
            Self::PresetsNavLabel => "presets-nav-label",
            Self::PresetsReadyStatus => "presets-ready-status",
            Self::PresetsScanAction => "presets-scan-action",
            Self::PresetsScanCancelled => "presets-scan-cancelled",
            Self::PresetsScanNone => "presets-scan-none",
            Self::PresetsScanPartial => "presets-scan-partial",
            Self::PresetsScanning => "presets-scanning",
            Self::PresetsSubtitle => "presets-subtitle",
            Self::PresetsTitle => "presets-title",
            Self::ProjectAddConfirm => "project-add-confirm",
            Self::ProjectAddedStatus => "project-added-status",
            Self::ProjectDuplicateStatus => "project-duplicate-status",
            Self::ProjectErrorEmptyPath => "project-error-empty-path",
            Self::ProjectErrorGeneric => "project-error-generic",
            Self::ProjectErrorInvalidLabel => "project-error-invalid-label",
            Self::ProjectErrorNotDirectory => "project-error-not-directory",
            Self::ProjectErrorPathTooLong => "project-error-path-too-long",
            Self::ProjectErrorPermissionDenied => "project-error-permission-denied",
            Self::ProjectErrorStale => "project-error-stale",
            Self::ProjectErrorUnavailable => "project-error-unavailable",
            Self::ProjectFilesStay => "project-files-stay",
            Self::ProjectLabelField => "project-label-field",
            Self::ProjectRemoveAction => "project-remove-action",
            Self::ProjectRemovedStatus => "project-removed-status",
            Self::ProjectRestoredStatus => "project-restored-status",
            Self::ProjectReviewDescription => "project-review-description",
            Self::ProjectReviewTitle => "project-review-title",
            Self::ProjectStatusAvailable => "project-status-available",
            Self::ProjectStatusPermissionDenied => "project-status-permission-denied",
            Self::ProjectStatusUnavailable => "project-status-unavailable",
            Self::ProjectStoreCorrupt => "project-store-corrupt",
            Self::ProjectStoreNewer => "project-store-newer",
            Self::ProjectStoreRecovered => "project-store-recovered",
            Self::ProjectStoreUnavailable => "project-store-unavailable",
            Self::ProjectUndoAction => "project-undo-action",
            Self::ProjectUndoExpired => "project-undo-expired",
            Self::ProjectValidating => "project-validating",
            Self::ProjectsAddAction => "projects-add-action",
            Self::ProjectsEmptyDescription => "projects-empty-description",
            Self::ProjectsEmptyTitle => "projects-empty-title",
            Self::ProjectsFolderSafety => "projects-folder-safety",
            Self::ProjectsLoading => "projects-loading",
            Self::ProjectsLocalOnly => "projects-local-only",
            Self::ProjectsNavLabel => "projects-nav-label",
            Self::ProjectsReadyStatus => "projects-ready-status",
            Self::ProjectsShortcutDescription => "projects-shortcut-description",
            Self::ProjectsSubtitle => "projects-subtitle",
            Self::ProjectsTitle => "projects-title",
            Self::RuntimeLabelClaude => "runtime-label-claude",
            Self::RuntimeLabelCodex => "runtime-label-codex",
            Self::RuntimeLabelGemini => "runtime-label-gemini",
            Self::SessionCount => "session-count",
            Self::ShortcutHint => "shortcut-hint",
            Self::StatusConnecting => "status-connecting",
            Self::StatusReady => "status-ready",
            Self::TransferSummary => "transfer-summary",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonCancelArgs;

impl CommonCancelArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for CommonCancelArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for CommonCancelArgs {
    const ID: MessageId = MessageId::CommonCancel;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonCloseArgs;

impl CommonCloseArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for CommonCloseArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for CommonCloseArgs {
    const ID: MessageId = MessageId::CommonClose;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonConnectArgs;

impl CommonConnectArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for CommonConnectArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for CommonConnectArgs {
    const ID: MessageId = MessageId::CommonConnect;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonDeleteArgs;

impl CommonDeleteArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for CommonDeleteArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for CommonDeleteArgs {
    const ID: MessageId = MessageId::CommonDelete;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonRetryArgs;

impl CommonRetryArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for CommonRetryArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for CommonRetryArgs {
    const ID: MessageId = MessageId::CommonRetry;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonRunArgs;

impl CommonRunArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for CommonRunArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for CommonRunArgs {
    const ID: MessageId = MessageId::CommonRun;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonSaveArgs;

impl CommonSaveArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for CommonSaveArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for CommonSaveArgs {
    const ID: MessageId = MessageId::CommonSave;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DevelopmentLocaleActiveArgs {
    locale: KeyName,
}

impl DevelopmentLocaleActiveArgs {
    pub fn new(locale: KeyName) -> Self {
        Self { locale }
    }
}

impl MessageArguments for DevelopmentLocaleActiveArgs {
    const ID: MessageId = MessageId::DevelopmentLocaleActive;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "locale",
            ArgumentValue::KeyName(self.locale.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DevelopmentLocalizationHintArgs;

impl DevelopmentLocalizationHintArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for DevelopmentLocalizationHintArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for DevelopmentLocalizationHintArgs {
    const ID: MessageId = MessageId::DevelopmentLocalizationHint;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DevelopmentLocalizationTitleArgs;

impl DevelopmentLocalizationTitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for DevelopmentLocalizationTitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for DevelopmentLocalizationTitleArgs {
    const ID: MessageId = MessageId::DevelopmentLocalizationTitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FieldErrorArgs {
    reason: Text,
}

impl FieldErrorArgs {
    pub fn new(reason: Text) -> Self {
        Self { reason }
    }
}

impl MessageArguments for FieldErrorArgs {
    const ID: MessageId = MessageId::FieldError;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "reason",
            ArgumentValue::Text(self.reason.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LastUpdatedArgs {
    when: DateTime,
}

impl LastUpdatedArgs {
    pub fn new(when: DateTime) -> Self {
        Self { when }
    }
}

impl MessageArguments for LastUpdatedArgs {
    const ID: MessageId = MessageId::LastUpdated;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new("when", ArgumentValue::DateTime(self.when.0))]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PathUnavailableArgs {
    path: UserData,
}

impl PathUnavailableArgs {
    pub fn new(path: UserData) -> Self {
        Self { path }
    }
}

impl MessageArguments for PathUnavailableArgs {
    const ID: MessageId = MessageId::PathUnavailable;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "path",
            ArgumentValue::UserData(self.path.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetAcceptActionArgs;

impl PresetAcceptActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetAcceptActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetAcceptActionArgs {
    const ID: MessageId = MessageId::PresetAcceptAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetAcceptedStatusArgs {
    name: UserData,
}

impl PresetAcceptedStatusArgs {
    pub fn new(name: UserData) -> Self {
        Self { name }
    }
}

impl MessageArguments for PresetAcceptedStatusArgs {
    const ID: MessageId = MessageId::PresetAcceptedStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "name",
            ArgumentValue::UserData(self.name.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetArgumentAddArgs;

impl PresetArgumentAddArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetArgumentAddArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetArgumentAddArgs {
    const ID: MessageId = MessageId::PresetArgumentAdd;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetArgumentCountArgs {
    count: Count,
}

impl PresetArgumentCountArgs {
    pub fn new(count: Count) -> Self {
        Self { count }
    }
}

impl MessageArguments for PresetArgumentCountArgs {
    const ID: MessageId = MessageId::PresetArgumentCount;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new("count", ArgumentValue::Count(self.count.0))]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetArgumentRemoveArgs;

impl PresetArgumentRemoveArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetArgumentRemoveArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetArgumentRemoveArgs {
    const ID: MessageId = MessageId::PresetArgumentRemove;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetArgumentsFieldArgs;

impl PresetArgumentsFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetArgumentsFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetArgumentsFieldArgs {
    const ID: MessageId = MessageId::PresetArgumentsField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetDeleteActionArgs;

impl PresetDeleteActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetDeleteActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetDeleteActionArgs {
    const ID: MessageId = MessageId::PresetDeleteAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetDetectedVersionArgs {
    version: UserData,
}

impl PresetDetectedVersionArgs {
    pub fn new(version: UserData) -> Self {
        Self { version }
    }
}

impl MessageArguments for PresetDetectedVersionArgs {
    const ID: MessageId = MessageId::PresetDetectedVersion;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "version",
            ArgumentValue::UserData(self.version.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetEditActionArgs;

impl PresetEditActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetEditActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetEditActionArgs {
    const ID: MessageId = MessageId::PresetEditAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetEnabledFieldArgs;

impl PresetEnabledFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetEnabledFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetEnabledFieldArgs {
    const ID: MessageId = MessageId::PresetEnabledField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetErrorInvalidArgs;

impl PresetErrorInvalidArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetErrorInvalidArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetErrorInvalidArgs {
    const ID: MessageId = MessageId::PresetErrorInvalid;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetErrorRiskConfirmArgs;

impl PresetErrorRiskConfirmArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetErrorRiskConfirmArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetErrorRiskConfirmArgs {
    const ID: MessageId = MessageId::PresetErrorRiskConfirm;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetErrorStaleArgs;

impl PresetErrorStaleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetErrorStaleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetErrorStaleArgs {
    const ID: MessageId = MessageId::PresetErrorStale;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetExecutableFieldArgs;

impl PresetExecutableFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetExecutableFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetExecutableFieldArgs {
    const ID: MessageId = MessageId::PresetExecutableField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetFavoriteFieldArgs;

impl PresetFavoriteFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetFavoriteFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetFavoriteFieldArgs {
    const ID: MessageId = MessageId::PresetFavoriteField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetFormTitleEditArgs;

impl PresetFormTitleEditArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetFormTitleEditArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetFormTitleEditArgs {
    const ID: MessageId = MessageId::PresetFormTitleEdit;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetFormTitleNewArgs;

impl PresetFormTitleNewArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetFormTitleNewArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetFormTitleNewArgs {
    const ID: MessageId = MessageId::PresetFormTitleNew;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetLabelFieldArgs;

impl PresetLabelFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetLabelFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetLabelFieldArgs {
    const ID: MessageId = MessageId::PresetLabelField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetMoveDownActionArgs;

impl PresetMoveDownActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetMoveDownActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetMoveDownActionArgs {
    const ID: MessageId = MessageId::PresetMoveDownAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetMoveUpActionArgs;

impl PresetMoveUpActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetMoveUpActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetMoveUpActionArgs {
    const ID: MessageId = MessageId::PresetMoveUpAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetPermissionAskArgs;

impl PresetPermissionAskArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetPermissionAskArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetPermissionAskArgs {
    const ID: MessageId = MessageId::PresetPermissionAsk;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetPermissionFieldArgs;

impl PresetPermissionFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetPermissionFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetPermissionFieldArgs {
    const ID: MessageId = MessageId::PresetPermissionField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetPermissionReadOnlyArgs;

impl PresetPermissionReadOnlyArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetPermissionReadOnlyArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetPermissionReadOnlyArgs {
    const ID: MessageId = MessageId::PresetPermissionReadOnly;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetPermissionWorkspaceWriteArgs;

impl PresetPermissionWorkspaceWriteArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetPermissionWorkspaceWriteArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetPermissionWorkspaceWriteArgs {
    const ID: MessageId = MessageId::PresetPermissionWorkspaceWrite;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetRemovedStatusArgs {
    name: UserData,
}

impl PresetRemovedStatusArgs {
    pub fn new(name: UserData) -> Self {
        Self { name }
    }
}

impl MessageArguments for PresetRemovedStatusArgs {
    const ID: MessageId = MessageId::PresetRemovedStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "name",
            ArgumentValue::UserData(self.name.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetRiskConfirmFieldArgs;

impl PresetRiskConfirmFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetRiskConfirmFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetRiskConfirmFieldArgs {
    const ID: MessageId = MessageId::PresetRiskConfirmField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetRiskWarningArgs;

impl PresetRiskWarningArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetRiskWarningArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetRiskWarningArgs {
    const ID: MessageId = MessageId::PresetRiskWarning;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetSafeCopyArgs;

impl PresetSafeCopyArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetSafeCopyArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetSafeCopyArgs {
    const ID: MessageId = MessageId::PresetSafeCopy;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetSaveActionArgs;

impl PresetSaveActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetSaveActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetSaveActionArgs {
    const ID: MessageId = MessageId::PresetSaveAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetSavedStatusArgs {
    name: UserData,
}

impl PresetSavedStatusArgs {
    pub fn new(name: UserData) -> Self {
        Self { name }
    }
}

impl MessageArguments for PresetSavedStatusArgs {
    const ID: MessageId = MessageId::PresetSavedStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "name",
            ArgumentValue::UserData(self.name.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusDisabledArgs;

impl PresetStatusDisabledArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusDisabledArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusDisabledArgs {
    const ID: MessageId = MessageId::PresetStatusDisabled;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusFailedArgs;

impl PresetStatusFailedArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusFailedArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusFailedArgs {
    const ID: MessageId = MessageId::PresetStatusFailed;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusMissingArgs;

impl PresetStatusMissingArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusMissingArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusMissingArgs {
    const ID: MessageId = MessageId::PresetStatusMissing;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusPermissionArgs;

impl PresetStatusPermissionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusPermissionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusPermissionArgs {
    const ID: MessageId = MessageId::PresetStatusPermission;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusRiskyArgs;

impl PresetStatusRiskyArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusRiskyArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusRiskyArgs {
    const ID: MessageId = MessageId::PresetStatusRisky;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusSupportedArgs;

impl PresetStatusSupportedArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusSupportedArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusSupportedArgs {
    const ID: MessageId = MessageId::PresetStatusSupported;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusTimeoutArgs;

impl PresetStatusTimeoutArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusTimeoutArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusTimeoutArgs {
    const ID: MessageId = MessageId::PresetStatusTimeout;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusUnknownArgs;

impl PresetStatusUnknownArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusUnknownArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusUnknownArgs {
    const ID: MessageId = MessageId::PresetStatusUnknown;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStatusUnsupportedArgs;

impl PresetStatusUnsupportedArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStatusUnsupportedArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStatusUnsupportedArgs {
    const ID: MessageId = MessageId::PresetStatusUnsupported;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStoreCorruptArgs;

impl PresetStoreCorruptArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStoreCorruptArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStoreCorruptArgs {
    const ID: MessageId = MessageId::PresetStoreCorrupt;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStoreNewerArgs;

impl PresetStoreNewerArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStoreNewerArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStoreNewerArgs {
    const ID: MessageId = MessageId::PresetStoreNewer;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStoreRecoveredArgs;

impl PresetStoreRecoveredArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStoreRecoveredArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStoreRecoveredArgs {
    const ID: MessageId = MessageId::PresetStoreRecovered;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetStoreUnavailableArgs;

impl PresetStoreUnavailableArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetStoreUnavailableArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetStoreUnavailableArgs {
    const ID: MessageId = MessageId::PresetStoreUnavailable;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetSubdirectoryFieldArgs;

impl PresetSubdirectoryFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetSubdirectoryFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetSubdirectoryFieldArgs {
    const ID: MessageId = MessageId::PresetSubdirectoryField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetWorkingDirectoryFieldArgs;

impl PresetWorkingDirectoryFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetWorkingDirectoryFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetWorkingDirectoryFieldArgs {
    const ID: MessageId = MessageId::PresetWorkingDirectoryField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetWorkingHomeArgs;

impl PresetWorkingHomeArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetWorkingHomeArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetWorkingHomeArgs {
    const ID: MessageId = MessageId::PresetWorkingHome;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetWorkingProjectRootArgs;

impl PresetWorkingProjectRootArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetWorkingProjectRootArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetWorkingProjectRootArgs {
    const ID: MessageId = MessageId::PresetWorkingProjectRoot;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetWorkingSubdirectoryArgs;

impl PresetWorkingSubdirectoryArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetWorkingSubdirectoryArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetWorkingSubdirectoryArgs {
    const ID: MessageId = MessageId::PresetWorkingSubdirectory;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsAddActionArgs;

impl PresetsAddActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsAddActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsAddActionArgs {
    const ID: MessageId = MessageId::PresetsAddAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsDetectedTitleArgs;

impl PresetsDetectedTitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsDetectedTitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsDetectedTitleArgs {
    const ID: MessageId = MessageId::PresetsDetectedTitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsEmptyDescriptionArgs;

impl PresetsEmptyDescriptionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsEmptyDescriptionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsEmptyDescriptionArgs {
    const ID: MessageId = MessageId::PresetsEmptyDescription;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsEmptyTitleArgs;

impl PresetsEmptyTitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsEmptyTitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsEmptyTitleArgs {
    const ID: MessageId = MessageId::PresetsEmptyTitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsNavLabelArgs;

impl PresetsNavLabelArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsNavLabelArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsNavLabelArgs {
    const ID: MessageId = MessageId::PresetsNavLabel;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsReadyStatusArgs;

impl PresetsReadyStatusArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsReadyStatusArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsReadyStatusArgs {
    const ID: MessageId = MessageId::PresetsReadyStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsScanActionArgs;

impl PresetsScanActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsScanActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsScanActionArgs {
    const ID: MessageId = MessageId::PresetsScanAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsScanCancelledArgs;

impl PresetsScanCancelledArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsScanCancelledArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsScanCancelledArgs {
    const ID: MessageId = MessageId::PresetsScanCancelled;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsScanNoneArgs;

impl PresetsScanNoneArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsScanNoneArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsScanNoneArgs {
    const ID: MessageId = MessageId::PresetsScanNone;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsScanPartialArgs;

impl PresetsScanPartialArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsScanPartialArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsScanPartialArgs {
    const ID: MessageId = MessageId::PresetsScanPartial;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsScanningArgs;

impl PresetsScanningArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsScanningArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsScanningArgs {
    const ID: MessageId = MessageId::PresetsScanning;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsSubtitleArgs;

impl PresetsSubtitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsSubtitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsSubtitleArgs {
    const ID: MessageId = MessageId::PresetsSubtitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PresetsTitleArgs;

impl PresetsTitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for PresetsTitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for PresetsTitleArgs {
    const ID: MessageId = MessageId::PresetsTitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectAddConfirmArgs;

impl ProjectAddConfirmArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectAddConfirmArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectAddConfirmArgs {
    const ID: MessageId = MessageId::ProjectAddConfirm;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectAddedStatusArgs {
    name: UserData,
}

impl ProjectAddedStatusArgs {
    pub fn new(name: UserData) -> Self {
        Self { name }
    }
}

impl MessageArguments for ProjectAddedStatusArgs {
    const ID: MessageId = MessageId::ProjectAddedStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "name",
            ArgumentValue::UserData(self.name.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectDuplicateStatusArgs {
    name: UserData,
}

impl ProjectDuplicateStatusArgs {
    pub fn new(name: UserData) -> Self {
        Self { name }
    }
}

impl MessageArguments for ProjectDuplicateStatusArgs {
    const ID: MessageId = MessageId::ProjectDuplicateStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "name",
            ArgumentValue::UserData(self.name.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectErrorEmptyPathArgs;

impl ProjectErrorEmptyPathArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectErrorEmptyPathArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectErrorEmptyPathArgs {
    const ID: MessageId = MessageId::ProjectErrorEmptyPath;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectErrorGenericArgs;

impl ProjectErrorGenericArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectErrorGenericArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectErrorGenericArgs {
    const ID: MessageId = MessageId::ProjectErrorGeneric;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectErrorInvalidLabelArgs;

impl ProjectErrorInvalidLabelArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectErrorInvalidLabelArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectErrorInvalidLabelArgs {
    const ID: MessageId = MessageId::ProjectErrorInvalidLabel;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectErrorNotDirectoryArgs;

impl ProjectErrorNotDirectoryArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectErrorNotDirectoryArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectErrorNotDirectoryArgs {
    const ID: MessageId = MessageId::ProjectErrorNotDirectory;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectErrorPathTooLongArgs;

impl ProjectErrorPathTooLongArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectErrorPathTooLongArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectErrorPathTooLongArgs {
    const ID: MessageId = MessageId::ProjectErrorPathTooLong;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectErrorPermissionDeniedArgs;

impl ProjectErrorPermissionDeniedArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectErrorPermissionDeniedArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectErrorPermissionDeniedArgs {
    const ID: MessageId = MessageId::ProjectErrorPermissionDenied;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectErrorStaleArgs;

impl ProjectErrorStaleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectErrorStaleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectErrorStaleArgs {
    const ID: MessageId = MessageId::ProjectErrorStale;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectErrorUnavailableArgs;

impl ProjectErrorUnavailableArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectErrorUnavailableArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectErrorUnavailableArgs {
    const ID: MessageId = MessageId::ProjectErrorUnavailable;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectFilesStayArgs;

impl ProjectFilesStayArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectFilesStayArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectFilesStayArgs {
    const ID: MessageId = MessageId::ProjectFilesStay;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectLabelFieldArgs;

impl ProjectLabelFieldArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectLabelFieldArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectLabelFieldArgs {
    const ID: MessageId = MessageId::ProjectLabelField;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectRemoveActionArgs;

impl ProjectRemoveActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectRemoveActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectRemoveActionArgs {
    const ID: MessageId = MessageId::ProjectRemoveAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectRemovedStatusArgs {
    name: UserData,
}

impl ProjectRemovedStatusArgs {
    pub fn new(name: UserData) -> Self {
        Self { name }
    }
}

impl MessageArguments for ProjectRemovedStatusArgs {
    const ID: MessageId = MessageId::ProjectRemovedStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "name",
            ArgumentValue::UserData(self.name.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectRestoredStatusArgs {
    name: UserData,
}

impl ProjectRestoredStatusArgs {
    pub fn new(name: UserData) -> Self {
        Self { name }
    }
}

impl MessageArguments for ProjectRestoredStatusArgs {
    const ID: MessageId = MessageId::ProjectRestoredStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "name",
            ArgumentValue::UserData(self.name.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectReviewDescriptionArgs {
    path: UserData,
}

impl ProjectReviewDescriptionArgs {
    pub fn new(path: UserData) -> Self {
        Self { path }
    }
}

impl MessageArguments for ProjectReviewDescriptionArgs {
    const ID: MessageId = MessageId::ProjectReviewDescription;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "path",
            ArgumentValue::UserData(self.path.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectReviewTitleArgs;

impl ProjectReviewTitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectReviewTitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectReviewTitleArgs {
    const ID: MessageId = MessageId::ProjectReviewTitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectStatusAvailableArgs;

impl ProjectStatusAvailableArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectStatusAvailableArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectStatusAvailableArgs {
    const ID: MessageId = MessageId::ProjectStatusAvailable;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectStatusPermissionDeniedArgs;

impl ProjectStatusPermissionDeniedArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectStatusPermissionDeniedArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectStatusPermissionDeniedArgs {
    const ID: MessageId = MessageId::ProjectStatusPermissionDenied;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectStatusUnavailableArgs;

impl ProjectStatusUnavailableArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectStatusUnavailableArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectStatusUnavailableArgs {
    const ID: MessageId = MessageId::ProjectStatusUnavailable;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectStoreCorruptArgs;

impl ProjectStoreCorruptArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectStoreCorruptArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectStoreCorruptArgs {
    const ID: MessageId = MessageId::ProjectStoreCorrupt;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectStoreNewerArgs;

impl ProjectStoreNewerArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectStoreNewerArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectStoreNewerArgs {
    const ID: MessageId = MessageId::ProjectStoreNewer;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectStoreRecoveredArgs;

impl ProjectStoreRecoveredArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectStoreRecoveredArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectStoreRecoveredArgs {
    const ID: MessageId = MessageId::ProjectStoreRecovered;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectStoreUnavailableArgs;

impl ProjectStoreUnavailableArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectStoreUnavailableArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectStoreUnavailableArgs {
    const ID: MessageId = MessageId::ProjectStoreUnavailable;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectUndoActionArgs;

impl ProjectUndoActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectUndoActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectUndoActionArgs {
    const ID: MessageId = MessageId::ProjectUndoAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectUndoExpiredArgs;

impl ProjectUndoExpiredArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectUndoExpiredArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectUndoExpiredArgs {
    const ID: MessageId = MessageId::ProjectUndoExpired;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectValidatingArgs;

impl ProjectValidatingArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectValidatingArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectValidatingArgs {
    const ID: MessageId = MessageId::ProjectValidating;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsAddActionArgs;

impl ProjectsAddActionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsAddActionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsAddActionArgs {
    const ID: MessageId = MessageId::ProjectsAddAction;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsEmptyDescriptionArgs;

impl ProjectsEmptyDescriptionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsEmptyDescriptionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsEmptyDescriptionArgs {
    const ID: MessageId = MessageId::ProjectsEmptyDescription;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsEmptyTitleArgs;

impl ProjectsEmptyTitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsEmptyTitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsEmptyTitleArgs {
    const ID: MessageId = MessageId::ProjectsEmptyTitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsFolderSafetyArgs;

impl ProjectsFolderSafetyArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsFolderSafetyArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsFolderSafetyArgs {
    const ID: MessageId = MessageId::ProjectsFolderSafety;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsLoadingArgs;

impl ProjectsLoadingArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsLoadingArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsLoadingArgs {
    const ID: MessageId = MessageId::ProjectsLoading;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsLocalOnlyArgs;

impl ProjectsLocalOnlyArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsLocalOnlyArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsLocalOnlyArgs {
    const ID: MessageId = MessageId::ProjectsLocalOnly;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsNavLabelArgs;

impl ProjectsNavLabelArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsNavLabelArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsNavLabelArgs {
    const ID: MessageId = MessageId::ProjectsNavLabel;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsReadyStatusArgs;

impl ProjectsReadyStatusArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsReadyStatusArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsReadyStatusArgs {
    const ID: MessageId = MessageId::ProjectsReadyStatus;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsShortcutDescriptionArgs;

impl ProjectsShortcutDescriptionArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsShortcutDescriptionArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsShortcutDescriptionArgs {
    const ID: MessageId = MessageId::ProjectsShortcutDescription;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsSubtitleArgs;

impl ProjectsSubtitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsSubtitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsSubtitleArgs {
    const ID: MessageId = MessageId::ProjectsSubtitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectsTitleArgs;

impl ProjectsTitleArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for ProjectsTitleArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for ProjectsTitleArgs {
    const ID: MessageId = MessageId::ProjectsTitle;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RuntimeLabelClaudeArgs;

impl RuntimeLabelClaudeArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for RuntimeLabelClaudeArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for RuntimeLabelClaudeArgs {
    const ID: MessageId = MessageId::RuntimeLabelClaude;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RuntimeLabelCodexArgs;

impl RuntimeLabelCodexArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for RuntimeLabelCodexArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for RuntimeLabelCodexArgs {
    const ID: MessageId = MessageId::RuntimeLabelCodex;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RuntimeLabelGeminiArgs;

impl RuntimeLabelGeminiArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for RuntimeLabelGeminiArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for RuntimeLabelGeminiArgs {
    const ID: MessageId = MessageId::RuntimeLabelGemini;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SessionCountArgs {
    count: Count,
}

impl SessionCountArgs {
    pub fn new(count: Count) -> Self {
        Self { count }
    }
}

impl MessageArguments for SessionCountArgs {
    const ID: MessageId = MessageId::SessionCount;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new("count", ArgumentValue::Count(self.count.0))]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ShortcutHintArgs {
    key: KeyName,
}

impl ShortcutHintArgs {
    pub fn new(key: KeyName) -> Self {
        Self { key }
    }
}

impl MessageArguments for ShortcutHintArgs {
    const ID: MessageId = MessageId::ShortcutHint;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "key",
            ArgumentValue::KeyName(self.key.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StatusConnectingArgs {
    host: UserData,
}

impl StatusConnectingArgs {
    pub fn new(host: UserData) -> Self {
        Self { host }
    }
}

impl MessageArguments for StatusConnectingArgs {
    const ID: MessageId = MessageId::StatusConnecting;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![Argument::new(
            "host",
            ArgumentValue::UserData(self.host.as_str()),
        )]
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StatusReadyArgs;

impl StatusReadyArgs {
    pub const fn new() -> Self {
        Self
    }
}

impl Default for StatusReadyArgs {
    fn default() -> Self {
        Self::new()
    }
}

impl MessageArguments for StatusReadyArgs {
    const ID: MessageId = MessageId::StatusReady;

    fn arguments(&self) -> Vec<Argument<'_>> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TransferSummaryArgs {
    count: Count,
    bytes: ByteSize,
}

impl TransferSummaryArgs {
    pub fn new(count: Count, bytes: ByteSize) -> Self {
        Self { count, bytes }
    }
}

impl MessageArguments for TransferSummaryArgs {
    const ID: MessageId = MessageId::TransferSummary;

    fn arguments(&self) -> Vec<Argument<'_>> {
        vec![
            Argument::new("count", ArgumentValue::Count(self.count.0)),
            Argument::new("bytes", ArgumentValue::ByteSize(self.bytes.0)),
        ]
    }
}

pub const MESSAGE_SPECS: &[MessageSpec] = &[
    MessageSpec {
        id: MessageId::CommonCancel,
        key: "common-cancel",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::CommonClose,
        key: "common-close",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::CommonConnect,
        key: "common-connect",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::CommonDelete,
        key: "common-delete",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::CommonRetry,
        key: "common-retry",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::CommonRun,
        key: "common-run",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::CommonSave,
        key: "common-save",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::DevelopmentLocaleActive,
        key: "development-locale-active",
        args: &[ArgSpec {
            name: "locale",
            kind: ArgumentType::KeyName,
            sensitivity: Sensitivity::Public,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::DevelopmentLocalizationHint,
        key: "development-localization-hint",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::DevelopmentLocalizationTitle,
        key: "development-localization-title",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::FieldError,
        key: "field-error",
        args: &[ArgSpec {
            name: "reason",
            kind: ArgumentType::Text,
            sensitivity: Sensitivity::Public,
            bidi: BidiRule::None,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::LastUpdated,
        key: "last-updated",
        args: &[ArgSpec {
            name: "when",
            kind: ArgumentType::DateTime,
            sensitivity: Sensitivity::Public,
            bidi: BidiRule::None,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PathUnavailable,
        key: "path-unavailable",
        args: &[ArgSpec {
            name: "path",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetAcceptAction,
        key: "preset-accept-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetAcceptedStatus,
        key: "preset-accepted-status",
        args: &[ArgSpec {
            name: "name",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetArgumentAdd,
        key: "preset-argument-add",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetArgumentCount,
        key: "preset-argument-count",
        args: &[ArgSpec {
            name: "count",
            kind: ArgumentType::Count,
            sensitivity: Sensitivity::Public,
            bidi: BidiRule::None,
        }],
        plural_arg: Some("count"),
    },
    MessageSpec {
        id: MessageId::PresetArgumentRemove,
        key: "preset-argument-remove",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetArgumentsField,
        key: "preset-arguments-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetDeleteAction,
        key: "preset-delete-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetDetectedVersion,
        key: "preset-detected-version",
        args: &[ArgSpec {
            name: "version",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetEditAction,
        key: "preset-edit-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetEnabledField,
        key: "preset-enabled-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetErrorInvalid,
        key: "preset-error-invalid",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetErrorRiskConfirm,
        key: "preset-error-risk-confirm",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetErrorStale,
        key: "preset-error-stale",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetExecutableField,
        key: "preset-executable-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetFavoriteField,
        key: "preset-favorite-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetFormTitleEdit,
        key: "preset-form-title-edit",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetFormTitleNew,
        key: "preset-form-title-new",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetLabelField,
        key: "preset-label-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetMoveDownAction,
        key: "preset-move-down-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetMoveUpAction,
        key: "preset-move-up-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetPermissionAsk,
        key: "preset-permission-ask",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetPermissionField,
        key: "preset-permission-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetPermissionReadOnly,
        key: "preset-permission-read-only",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetPermissionWorkspaceWrite,
        key: "preset-permission-workspace-write",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetRemovedStatus,
        key: "preset-removed-status",
        args: &[ArgSpec {
            name: "name",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetRiskConfirmField,
        key: "preset-risk-confirm-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetRiskWarning,
        key: "preset-risk-warning",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetSafeCopy,
        key: "preset-safe-copy",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetSaveAction,
        key: "preset-save-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetSavedStatus,
        key: "preset-saved-status",
        args: &[ArgSpec {
            name: "name",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusDisabled,
        key: "preset-status-disabled",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusFailed,
        key: "preset-status-failed",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusMissing,
        key: "preset-status-missing",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusPermission,
        key: "preset-status-permission",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusRisky,
        key: "preset-status-risky",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusSupported,
        key: "preset-status-supported",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusTimeout,
        key: "preset-status-timeout",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusUnknown,
        key: "preset-status-unknown",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStatusUnsupported,
        key: "preset-status-unsupported",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStoreCorrupt,
        key: "preset-store-corrupt",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStoreNewer,
        key: "preset-store-newer",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStoreRecovered,
        key: "preset-store-recovered",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetStoreUnavailable,
        key: "preset-store-unavailable",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetSubdirectoryField,
        key: "preset-subdirectory-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetWorkingDirectoryField,
        key: "preset-working-directory-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetWorkingHome,
        key: "preset-working-home",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetWorkingProjectRoot,
        key: "preset-working-project-root",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetWorkingSubdirectory,
        key: "preset-working-subdirectory",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsAddAction,
        key: "presets-add-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsDetectedTitle,
        key: "presets-detected-title",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsEmptyDescription,
        key: "presets-empty-description",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsEmptyTitle,
        key: "presets-empty-title",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsNavLabel,
        key: "presets-nav-label",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsReadyStatus,
        key: "presets-ready-status",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsScanAction,
        key: "presets-scan-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsScanCancelled,
        key: "presets-scan-cancelled",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsScanNone,
        key: "presets-scan-none",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsScanPartial,
        key: "presets-scan-partial",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsScanning,
        key: "presets-scanning",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsSubtitle,
        key: "presets-subtitle",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::PresetsTitle,
        key: "presets-title",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectAddConfirm,
        key: "project-add-confirm",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectAddedStatus,
        key: "project-added-status",
        args: &[ArgSpec {
            name: "name",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectDuplicateStatus,
        key: "project-duplicate-status",
        args: &[ArgSpec {
            name: "name",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectErrorEmptyPath,
        key: "project-error-empty-path",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectErrorGeneric,
        key: "project-error-generic",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectErrorInvalidLabel,
        key: "project-error-invalid-label",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectErrorNotDirectory,
        key: "project-error-not-directory",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectErrorPathTooLong,
        key: "project-error-path-too-long",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectErrorPermissionDenied,
        key: "project-error-permission-denied",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectErrorStale,
        key: "project-error-stale",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectErrorUnavailable,
        key: "project-error-unavailable",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectFilesStay,
        key: "project-files-stay",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectLabelField,
        key: "project-label-field",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectRemoveAction,
        key: "project-remove-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectRemovedStatus,
        key: "project-removed-status",
        args: &[ArgSpec {
            name: "name",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectRestoredStatus,
        key: "project-restored-status",
        args: &[ArgSpec {
            name: "name",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectReviewDescription,
        key: "project-review-description",
        args: &[ArgSpec {
            name: "path",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectReviewTitle,
        key: "project-review-title",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectStatusAvailable,
        key: "project-status-available",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectStatusPermissionDenied,
        key: "project-status-permission-denied",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectStatusUnavailable,
        key: "project-status-unavailable",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectStoreCorrupt,
        key: "project-store-corrupt",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectStoreNewer,
        key: "project-store-newer",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectStoreRecovered,
        key: "project-store-recovered",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectStoreUnavailable,
        key: "project-store-unavailable",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectUndoAction,
        key: "project-undo-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectUndoExpired,
        key: "project-undo-expired",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectValidating,
        key: "project-validating",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsAddAction,
        key: "projects-add-action",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsEmptyDescription,
        key: "projects-empty-description",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsEmptyTitle,
        key: "projects-empty-title",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsFolderSafety,
        key: "projects-folder-safety",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsLoading,
        key: "projects-loading",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsLocalOnly,
        key: "projects-local-only",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsNavLabel,
        key: "projects-nav-label",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsReadyStatus,
        key: "projects-ready-status",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsShortcutDescription,
        key: "projects-shortcut-description",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsSubtitle,
        key: "projects-subtitle",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::ProjectsTitle,
        key: "projects-title",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::RuntimeLabelClaude,
        key: "runtime-label-claude",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::RuntimeLabelCodex,
        key: "runtime-label-codex",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::RuntimeLabelGemini,
        key: "runtime-label-gemini",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::SessionCount,
        key: "session-count",
        args: &[ArgSpec {
            name: "count",
            kind: ArgumentType::Count,
            sensitivity: Sensitivity::Public,
            bidi: BidiRule::None,
        }],
        plural_arg: Some("count"),
    },
    MessageSpec {
        id: MessageId::ShortcutHint,
        key: "shortcut-hint",
        args: &[ArgSpec {
            name: "key",
            kind: ArgumentType::KeyName,
            sensitivity: Sensitivity::Public,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::StatusConnecting,
        key: "status-connecting",
        args: &[ArgSpec {
            name: "host",
            kind: ArgumentType::UserData,
            sensitivity: Sensitivity::Sensitive,
            bidi: BidiRule::Isolate,
        }],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::StatusReady,
        key: "status-ready",
        args: &[],
        plural_arg: None,
    },
    MessageSpec {
        id: MessageId::TransferSummary,
        key: "transfer-summary",
        args: &[
            ArgSpec {
                name: "count",
                kind: ArgumentType::Count,
                sensitivity: Sensitivity::Public,
                bidi: BidiRule::None,
            },
            ArgSpec {
                name: "bytes",
                kind: ArgumentType::ByteSize,
                sensitivity: Sensitivity::Public,
                bidi: BidiRule::None,
            },
        ],
        plural_arg: Some("count"),
    },
];
