use std::{env, fmt::Write as _, fs, path::PathBuf};

use unicode_width::UnicodeWidthChar as _;

const UNICODE_WIDTH_VERSION: &str = "0.2.2";

#[derive(Clone, Copy)]
struct ScalarRange {
    start: u32,
    end: u32,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let check = match env::args().nth(1).as_deref() {
        None => false,
        Some("--check") => true,
        Some(_) => return Err("usage: generate_terminal_width_tables [--check]".into()),
    };
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output = root.join("tests/fixtures/terminal/generated");
    let zero = collect_ranges(0);
    let wide = collect_ranges(2);
    let generated = [
        (
            output.join("GeneratedTerminalCellWidth.swift"),
            render_swift(&zero, &wide),
        ),
        (
            output.join("GeneratedTerminalCellWidth.kt"),
            render_kotlin(&zero, &wide),
        ),
    ];

    if check {
        for (path, expected) in generated {
            let actual = fs::read_to_string(&path)?;
            if actual != expected {
                return Err(format!(
                    "generated terminal width table is stale: {}",
                    path.display()
                )
                .into());
            }
        }
        println!("Terminal width tables match unicode-width {UNICODE_WIDTH_VERSION}.");
        return Ok(());
    }

    fs::create_dir_all(&output)?;
    for (path, contents) in generated {
        fs::write(path, contents)?;
    }
    println!("Generated terminal width tables from unicode-width {UNICODE_WIDTH_VERSION}.");
    Ok(())
}

fn collect_ranges(target_width: usize) -> Vec<ScalarRange> {
    let mut ranges = Vec::new();
    let mut open: Option<ScalarRange> = None;
    for value in 0..=0x10_FFFF {
        let matches = char::from_u32(value).and_then(char::width) == Some(target_width);
        match (open.as_mut(), matches) {
            (None, true) => {
                open = Some(ScalarRange {
                    start: value,
                    end: value,
                });
            }
            (Some(range), true) => range.end = value,
            (Some(_), false) => ranges.push(open.take().expect("open range exists")),
            (None, false) => {}
        }
    }
    if let Some(range) = open {
        ranges.push(range);
    }
    ranges
}

fn render_swift(zero: &[ScalarRange], wide: &[ScalarRange]) -> String {
    let mut output = String::new();
    writeln!(
        output,
        "// Generated by `cargo run --example generate_terminal_width_tables`."
    )
    .unwrap();
    writeln!(
        output,
        "// Source: unicode-width {UNICODE_WIDTH_VERSION}. Do not edit manually.\n"
    )
    .unwrap();
    writeln!(output, "enum GeneratedTerminalCellWidth {{").unwrap();
    writeln!(
        output,
        "    static let unicodeWidthVersion = \"{UNICODE_WIDTH_VERSION}\"\n"
    )
    .unwrap();
    writeln!(
        output,
        "    static func width(of scalar: Unicode.Scalar) -> Int {{"
    )
    .unwrap();
    writeln!(output, "        let value = scalar.value").unwrap();
    writeln!(
        output,
        "        if contains(value, in: zeroWidthRanges) {{ return 0 }}"
    )
    .unwrap();
    writeln!(
        output,
        "        if contains(value, in: wideRanges) {{ return 2 }}"
    )
    .unwrap();
    writeln!(output, "        return 1").unwrap();
    writeln!(output, "    }}\n").unwrap();
    writeln!(output, "    private static func contains(").unwrap();
    writeln!(output, "        _ value: UInt32,").unwrap();
    writeln!(output, "        in ranges: [(UInt32, UInt32)]").unwrap();
    writeln!(output, "    ) -> Bool {{").unwrap();
    writeln!(output, "        var lower = 0").unwrap();
    writeln!(output, "        var upper = ranges.count").unwrap();
    writeln!(output, "        while lower < upper {{").unwrap();
    writeln!(
        output,
        "            let middle = lower + (upper - lower) / 2"
    )
    .unwrap();
    writeln!(output, "            let range = ranges[middle]").unwrap();
    writeln!(
        output,
        "            if value < range.0 {{ upper = middle }}"
    )
    .unwrap();
    writeln!(
        output,
        "            else if value > range.1 {{ lower = middle + 1 }}"
    )
    .unwrap();
    writeln!(output, "            else {{ return true }}").unwrap();
    writeln!(output, "        }}").unwrap();
    writeln!(output, "        return false").unwrap();
    writeln!(output, "    }}\n").unwrap();
    writeln!(
        output,
        "    private static let zeroWidthRanges: [(UInt32, UInt32)] = ["
    )
    .unwrap();
    output.push_str(&render_swift_ranges(zero));
    output.push_str("\n    ]\n\n    private static let wideRanges: [(UInt32, UInt32)] = [\n");
    output.push_str(&render_swift_ranges(wide));
    output.push_str("\n    ]\n}\n");
    output
}

fn render_swift_ranges(ranges: &[ScalarRange]) -> String {
    ranges
        .iter()
        .map(|range| format!("        (0x{:X}, 0x{:X}),", range.start, range.end))
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_kotlin(zero: &[ScalarRange], wide: &[ScalarRange]) -> String {
    let mut output = String::new();
    writeln!(
        output,
        "// Generated by `cargo run --example generate_terminal_width_tables`."
    )
    .unwrap();
    writeln!(
        output,
        "// Source: unicode-width {UNICODE_WIDTH_VERSION}. Do not edit manually.\n"
    )
    .unwrap();
    writeln!(output, "package com.termirust.mobile.controller\n").unwrap();
    writeln!(output, "internal object GeneratedTerminalCellWidth {{").unwrap();
    writeln!(
        output,
        "    const val UNICODE_WIDTH_VERSION = \"{UNICODE_WIDTH_VERSION}\"\n"
    )
    .unwrap();
    writeln!(output, "    fun width(codePoint: Int): Int = when {{").unwrap();
    writeln!(
        output,
        "        contains(codePoint, ZERO_WIDTH_RANGES) -> 0"
    )
    .unwrap();
    writeln!(output, "        contains(codePoint, WIDE_RANGES) -> 2").unwrap();
    writeln!(output, "        else -> 1").unwrap();
    writeln!(output, "    }}\n").unwrap();
    writeln!(
        output,
        "    private fun contains(value: Int, ranges: IntArray): Boolean {{"
    )
    .unwrap();
    writeln!(output, "        var lower = 0").unwrap();
    writeln!(output, "        var upper = ranges.size / 2").unwrap();
    writeln!(output, "        while (lower < upper) {{").unwrap();
    writeln!(
        output,
        "            val middle = lower + (upper - lower) / 2"
    )
    .unwrap();
    writeln!(output, "            val start = ranges[middle * 2]").unwrap();
    writeln!(output, "            val end = ranges[middle * 2 + 1]").unwrap();
    writeln!(output, "            when {{").unwrap();
    writeln!(output, "                value < start -> upper = middle").unwrap();
    writeln!(output, "                value > end -> lower = middle + 1").unwrap();
    writeln!(output, "                else -> return true").unwrap();
    writeln!(output, "            }}").unwrap();
    writeln!(output, "        }}").unwrap();
    writeln!(output, "        return false").unwrap();
    writeln!(output, "    }}\n").unwrap();
    writeln!(output, "    private val ZERO_WIDTH_RANGES = intArrayOf(").unwrap();
    output.push_str(&render_kotlin_ranges(zero));
    output.push_str("\n    )\n\n    private val WIDE_RANGES = intArrayOf(\n");
    output.push_str(&render_kotlin_ranges(wide));
    output.push_str("\n    )\n}\n");
    output
}

fn render_kotlin_ranges(ranges: &[ScalarRange]) -> String {
    ranges
        .chunks(4)
        .map(|chunk| {
            let values = chunk
                .iter()
                .map(|range| format!("0x{:X}, 0x{:X}", range.start, range.end))
                .collect::<Vec<_>>()
                .join(", ");
            format!("        {values},")
        })
        .collect::<Vec<_>>()
        .join("\n")
}
