// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(TermiRustReplicationSecurityFFI)
import TermiRustReplicationSecurityFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_termirust_replication_bindings_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_termirust_replication_bindings_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTermirustReplicationBindingsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol MobileReplicationProductProtocol: AnyObject, Sendable {

    func cancelPendingEnrollment(expectedRequest: Data) throws  -> Bool

    /**
     * None means no enrollment root, not a corrupt profile or unavailable secret.
     */
    func pendingEnrollment() throws  -> MobileEnrollmentRequest?

    /**
     * Requires a real existing local exchange directory, not a provider URI.
     * Preparation does not enroll, accept remote data, or synchronize anything.
     */
    func prepareEnrollment(localExchangeDirectory: String) throws  -> MobileEnrollmentRequest

}
open class MobileReplicationProduct: MobileReplicationProductProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_termirust_replication_bindings_fn_clone_mobilereplicationproduct(self.handle, $0) }
    }
    /**
     * An existing, app-private, no-backup directory dedicated to replication.
     * Run all methods on a worker thread; these are synchronous filesystem calls.
     */
public convenience init(privateDirectory: String, store: ReplicationSecureStore)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeMobileReplicationError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_constructor_mobilereplicationproduct_new(
        FfiConverterString.lower(privateDirectory),
        FfiConverterTypeReplicationSecureStore_lower(store),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_termirust_replication_bindings_fn_free_mobilereplicationproduct(handle, $0) }
    }




open func cancelPendingEnrollment(expectedRequest: Data)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMobileReplicationError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_mobilereplicationproduct_cancel_pending_enrollment(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(expectedRequest),uniffiCallStatus
    )
})
}

    /**
     * None means no enrollment root, not a corrupt profile or unavailable secret.
     */
open func pendingEnrollment()throws  -> MobileEnrollmentRequest?  {
    return try  FfiConverterOptionTypeMobileEnrollmentRequest.lift(try rustCallWithError(FfiConverterTypeMobileReplicationError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_mobilereplicationproduct_pending_enrollment(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

    /**
     * Requires a real existing local exchange directory, not a provider URI.
     * Preparation does not enroll, accept remote data, or synchronize anything.
     */
open func prepareEnrollment(localExchangeDirectory: String)throws  -> MobileEnrollmentRequest  {
    return try  FfiConverterTypeMobileEnrollmentRequest_lift(try rustCallWithError(FfiConverterTypeMobileReplicationError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_mobilereplicationproduct_prepare_enrollment(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(localExchangeDirectory),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileReplicationProduct: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MobileReplicationProduct

    public static func lift(_ handle: UInt64) throws -> MobileReplicationProduct {
        return MobileReplicationProduct(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MobileReplicationProduct) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileReplicationProduct {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MobileReplicationProduct, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileReplicationProduct_lift(_ handle: UInt64) throws -> MobileReplicationProduct {
    return try FfiConverterTypeMobileReplicationProduct.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileReplicationProduct_lower(_ value: MobileReplicationProduct) -> UInt64 {
    return FfiConverterTypeMobileReplicationProduct.lower(value)
}






public protocol ReplicationCustodyProtocol: AnyObject, Sendable {

    func createDeviceIdentity() throws  -> ReplicationDeviceIdentity

    func deleteDeviceIdentity(secretReference: Data) throws  -> Bool

    func devicePublicKey(secretReference: Data) throws  -> Data

}
open class ReplicationCustody: ReplicationCustodyProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_termirust_replication_bindings_fn_clone_replicationcustody(self.handle, $0) }
    }
public convenience init(store: ReplicationSecureStore) {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_constructor_replicationcustody_new(
        FfiConverterTypeReplicationSecureStore_lower(store),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_termirust_replication_bindings_fn_free_replicationcustody(handle, $0) }
    }




open func createDeviceIdentity()throws  -> ReplicationDeviceIdentity  {
    return try  FfiConverterTypeReplicationDeviceIdentity_lift(try rustCallWithError(FfiConverterTypeReplicationStorageError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_replicationcustody_create_device_identity(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func deleteDeviceIdentity(secretReference: Data)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeReplicationStorageError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_replicationcustody_delete_device_identity(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(secretReference),uniffiCallStatus
    )
})
}

open func devicePublicKey(secretReference: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeReplicationStorageError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_replicationcustody_device_public_key(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(secretReference),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReplicationCustody: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ReplicationCustody

    public static func lift(_ handle: UInt64) throws -> ReplicationCustody {
        return ReplicationCustody(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ReplicationCustody) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReplicationCustody {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ReplicationCustody, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReplicationCustody_lift(_ handle: UInt64) throws -> ReplicationCustody {
    return try FfiConverterTypeReplicationCustody.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReplicationCustody_lower(_ value: ReplicationCustody) -> UInt64 {
    return FfiConverterTypeReplicationCustody.lower(value)
}






/**
 * Use a replication-only namespace, excluded from backup and cloud key sync.
 * Callbacks may run on worker threads and must be thread-safe. Never log account
 * identifiers or secret buffers. Native code must clear owned mutable buffers.
 */
public protocol ReplicationSecureStore: AnyObject, Sendable {

    /**
     * Atomically create; return Collision without changing an existing value.
     * Success means the value is durably stored, not queued for a later write.
     */
    func create(account: String, value: Data) throws

    /**
     * Missing is distinct from locked, denied, corrupt, or unavailable storage.
     */
    func load(account: String) throws  -> Data

    /**
     * Delete exactly this account; return false only when it was already absent.
     */
    func delete(account: String) throws  -> Bool

}
/**
 * Use a replication-only namespace, excluded from backup and cloud key sync.
 * Callbacks may run on worker threads and must be thread-safe. Never log account
 * identifiers or secret buffers. Native code must clear owned mutable buffers.
 */
open class ReplicationSecureStoreImpl: ReplicationSecureStore, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_termirust_replication_bindings_fn_clone_replicationsecurestore(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_termirust_replication_bindings_fn_free_replicationsecurestore(handle, $0) }
    }




    /**
     * Atomically create; return Collision without changing an existing value.
     * Success means the value is durably stored, not queued for a later write.
     */
open func create(account: String, value: Data)throws   {try rustCallWithError(FfiConverterTypeReplicationStorageError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_replicationsecurestore_create(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(account),
        FfiConverterData.lower(value),uniffiCallStatus
    )
}
}

    /**
     * Missing is distinct from locked, denied, corrupt, or unavailable storage.
     */
open func load(account: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeReplicationStorageError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_replicationsecurestore_load(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(account),uniffiCallStatus
    )
})
}

    /**
     * Delete exactly this account; return false only when it was already absent.
     */
open func delete(account: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeReplicationStorageError_lift) {
        uniffiCallStatus in
    uniffi_termirust_replication_bindings_fn_method_replicationsecurestore_delete(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(account),uniffiCallStatus
    )
})
}



}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceReplicationSecureStore {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceReplicationSecureStore = UniffiVTableCallbackInterfaceReplicationSecureStore(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeReplicationSecureStore.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ReplicationSecureStore: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeReplicationSecureStore.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ReplicationSecureStore: handle missing in uniffiClone")
            }
        },
        create: { (
            uniffiHandle: UInt64,
            account: RustBuffer,
            value: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeReplicationSecureStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.create(
                     account: try FfiConverterString.lift(account),
                     value: try FfiConverterData.lift(value)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeReplicationStorageError_lower
            )
        },
        load: { (
            uniffiHandle: UInt64,
            account: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data in
                guard let uniffiObj = try? FfiConverterTypeReplicationSecureStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.load(
                     account: try FfiConverterString.lift(account)
                )
            }


            let writeReturn = { uniffiOutReturn.pointee = FfiConverterData.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeReplicationStorageError_lower
            )
        },
        delete: { (
            uniffiHandle: UInt64,
            account: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterTypeReplicationSecureStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.delete(
                     account: try FfiConverterString.lift(account)
                )
            }


            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeReplicationStorageError_lower
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceReplicationSecureStore> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceReplicationSecureStore>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitReplicationSecureStore() {
    uniffi_termirust_replication_bindings_fn_init_callback_vtable_replicationsecurestore(UniffiCallbackInterfaceReplicationSecureStore.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReplicationSecureStore: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<ReplicationSecureStore>()

    typealias FfiType = UInt64
    typealias SwiftType = ReplicationSecureStore

    public static func lift(_ handle: UInt64) throws -> ReplicationSecureStore {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return ReplicationSecureStoreImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: ReplicationSecureStore) -> UInt64 {
         if let rustImpl = value as? ReplicationSecureStoreImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReplicationSecureStore {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ReplicationSecureStore, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReplicationSecureStore_lift(_ handle: UInt64) throws -> ReplicationSecureStore {
    return try FfiConverterTypeReplicationSecureStore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReplicationSecureStore_lower(_ value: ReplicationSecureStore) -> UInt64 {
    return FfiConverterTypeReplicationSecureStore.lower(value)
}




public struct MobileEnrollmentRequest: Equatable, Hashable {
    /**
     * Inert canonical public request bytes, never private key or custody reference.
     */
    public var canonicalRequest: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Inert canonical public request bytes, never private key or custody reference.
         */canonicalRequest: Data) {
        self.canonicalRequest = canonicalRequest
    }




}

#if compiler(>=6)
extension MobileEnrollmentRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileEnrollmentRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileEnrollmentRequest {
        return
            try MobileEnrollmentRequest(
                canonicalRequest: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: MobileEnrollmentRequest, into buf: inout [UInt8]) {
        FfiConverterData.write(value.canonicalRequest, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileEnrollmentRequest_lift(_ buf: RustBuffer) throws -> MobileEnrollmentRequest {
    return try FfiConverterTypeMobileEnrollmentRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileEnrollmentRequest_lower(_ value: MobileEnrollmentRequest) -> RustBuffer {
    return FfiConverterTypeMobileEnrollmentRequest.lower(value)
}


public struct ReplicationDeviceIdentity: Equatable, Hashable {
    public var secretReference: Data
    public var publicKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secretReference: Data, publicKey: Data) {
        self.secretReference = secretReference
        self.publicKey = publicKey
    }




}

#if compiler(>=6)
extension ReplicationDeviceIdentity: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReplicationDeviceIdentity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReplicationDeviceIdentity {
        return
            try ReplicationDeviceIdentity(
                secretReference: FfiConverterData.read(from: &buf),
                publicKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ReplicationDeviceIdentity, into buf: inout [UInt8]) {
        FfiConverterData.write(value.secretReference, into: &buf)
        FfiConverterData.write(value.publicKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReplicationDeviceIdentity_lift(_ buf: RustBuffer) throws -> ReplicationDeviceIdentity {
    return try FfiConverterTypeReplicationDeviceIdentity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReplicationDeviceIdentity_lower(_ value: ReplicationDeviceIdentity) -> RustBuffer {
    return FfiConverterTypeReplicationDeviceIdentity.lower(value)
}


public
enum MobileReplicationError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Busy
    case Invalid
    case AlreadyConfigured
    case RecoveryRequired
    case StaleRequest
    case Locked
    case MissingSecret
    case Collision
    case Unavailable






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension MobileReplicationError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileReplicationError: FfiConverterRustBuffer {
    typealias SwiftType = MobileReplicationError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileReplicationError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Busy
        case 2: return .Invalid
        case 3: return .AlreadyConfigured
        case 4: return .RecoveryRequired
        case 5: return .StaleRequest
        case 6: return .Locked
        case 7: return .MissingSecret
        case 8: return .Collision
        case 9: return .Unavailable

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MobileReplicationError, into buf: inout [UInt8]) {
        switch value {





        case .Busy:
            writeInt(&buf, Int32(1))


        case .Invalid:
            writeInt(&buf, Int32(2))


        case .AlreadyConfigured:
            writeInt(&buf, Int32(3))


        case .RecoveryRequired:
            writeInt(&buf, Int32(4))


        case .StaleRequest:
            writeInt(&buf, Int32(5))


        case .Locked:
            writeInt(&buf, Int32(6))


        case .MissingSecret:
            writeInt(&buf, Int32(7))


        case .Collision:
            writeInt(&buf, Int32(8))


        case .Unavailable:
            writeInt(&buf, Int32(9))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileReplicationError_lift(_ buf: RustBuffer) throws -> MobileReplicationError {
    return try FfiConverterTypeMobileReplicationError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileReplicationError_lower(_ value: MobileReplicationError) -> RustBuffer {
    return FfiConverterTypeMobileReplicationError.lower(value)
}


public
enum ReplicationStorageError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Missing
    case Locked
    case Invalid
    case Collision
    case Unavailable






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension ReplicationStorageError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReplicationStorageError: FfiConverterRustBuffer {
    typealias SwiftType = ReplicationStorageError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReplicationStorageError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Missing
        case 2: return .Locked
        case 3: return .Invalid
        case 4: return .Collision
        case 5: return .Unavailable

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ReplicationStorageError, into buf: inout [UInt8]) {
        switch value {





        case .Missing:
            writeInt(&buf, Int32(1))


        case .Locked:
            writeInt(&buf, Int32(2))


        case .Invalid:
            writeInt(&buf, Int32(3))


        case .Collision:
            writeInt(&buf, Int32(4))


        case .Unavailable:
            writeInt(&buf, Int32(5))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReplicationStorageError_lift(_ buf: RustBuffer) throws -> ReplicationStorageError {
    return try FfiConverterTypeReplicationStorageError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReplicationStorageError_lower(_ value: ReplicationStorageError) -> RustBuffer {
    return FfiConverterTypeReplicationStorageError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMobileEnrollmentRequest: FfiConverterRustBuffer {
    typealias SwiftType = MobileEnrollmentRequest?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMobileEnrollmentRequest.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMobileEnrollmentRequest.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_termirust_replication_bindings_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_replicationcustody_create_device_identity() != 9581) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_replicationcustody_delete_device_identity() != 32775) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_replicationcustody_device_public_key() != 49669) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_replicationsecurestore_create() != 27019) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_replicationsecurestore_load() != 65303) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_replicationsecurestore_delete() != 25442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_mobilereplicationproduct_cancel_pending_enrollment() != 50529) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_mobilereplicationproduct_pending_enrollment() != 38968) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_method_mobilereplicationproduct_prepare_enrollment() != 49728) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_constructor_replicationcustody_new() != 58569) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_termirust_replication_bindings_checksum_constructor_mobilereplicationproduct_new() != 30991) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitReplicationSecureStore()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTermirustReplicationBindingsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
