// @generated by generate-tokens; do not edit.
// Source: design/tokens.toml (sha256:6441caca51d8b377a20b603a7abf4c8f7c27d18ecfdbd7152159ffe0e6ac13ed)

package com.termirust.mobile.ui

/** The Slate themes a token resolves against. */
enum class SlateTheme {
    Light,
    Dark,
    HighContrast,
    Recording,
}

data class SlateTypography(val size: Float, val lineHeight: Float, val weight: Int)

/** Colors are 0xAARRGGBB, ready for `androidx.compose.ui.graphics.Color(Long)`. */
object SlateTokens {
    /** Emphasized border. Allowed use: Selected and high-attention boundaries. */
    fun borderEmphasis(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 2.0f
        SlateTheme.Dark -> 2.0f
        SlateTheme.HighContrast -> 2.0f
        SlateTheme.Recording -> 2.0f
    }

    /** Default one-pixel border. Allowed use: Dividers and control outlines. */
    fun borderHairline(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 1.0f
        SlateTheme.Dark -> 1.0f
        SlateTheme.HighContrast -> 2.0f
        SlateTheme.Recording -> 1.0f
    }

    /** Accent color. Allowed use: Links, the active navigation icon, toggles, and drop zones. Never a button fill. */
    fun colorActionPrimary(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF2A64C8L
        SlateTheme.Dark -> 0xFF74A7F2L
        SlateTheme.HighContrast -> 0xFF00FFFFL
        SlateTheme.Recording -> 0xFF8CA8E8L
    }

    /** Text shown on the accent color. Allowed use: Accent foreground only. */
    fun colorActionPrimaryText(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFFFFFFFL
        SlateTheme.Dark -> 0xFF0E1622L
        SlateTheme.HighContrast -> 0xFF000000L
        SlateTheme.Recording -> 0xFF111318L
    }

    /** Content pane and window ground. Allowed use: Content panes and the window background. */
    fun colorBgCanvas(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFFAFBFCL
        SlateTheme.Dark -> 0xFF17191DL
        SlateTheme.HighContrast -> 0xFF000000L
        SlateTheme.Recording -> 0xFF202328L
    }

    /** Window chrome background. Allowed use: The title bar, sidebar, toolbar, and status bar. */
    fun colorBgChrome(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFE9ECF0L
        SlateTheme.Dark -> 0xFF111316L
        SlateTheme.HighContrast -> 0xFF000000L
        SlateTheme.Recording -> 0xFF1A1C20L
    }

    /** Neutral control fill. Allowed use: Default buttons, inputs, key caps, and segmented tracks. */
    fun colorBgControl(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFFFFFFFL
        SlateTheme.Dark -> 0xFF23262BL
        SlateTheme.HighContrast -> 0xFF000000L
        SlateTheme.Recording -> 0xFF2C3037L
    }

    /** Neutral control fill on hover. Allowed use: Hovered default buttons and controls. */
    fun colorBgControlHover(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFF2F4F7L
        SlateTheme.Dark -> 0xFF2A2E34L
        SlateTheme.HighContrast -> 0xFF1A1A1AL
        SlateTheme.Recording -> 0xFF333841L
    }

    /** Floating object background. Allowed use: Host cards, menus, the command palette, and dialogs. */
    fun colorBgElevated(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFFFFFFFL
        SlateTheme.Dark -> 0xFF1B1E23L
        SlateTheme.HighContrast -> 0xFF0A0A0AL
        SlateTheme.Recording -> 0xFF25292FL
    }

    /** Row and item hover background. Allowed use: Hovered navigation items, rows, menu items, and tabs. */
    fun colorBgHover(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFEDF0F3L
        SlateTheme.Dark -> 0xFF1C1F24L
        SlateTheme.HighContrast -> 0xFF1A1A1AL
        SlateTheme.Recording -> 0xFF2A2E34L
    }

    /** Selected row and item background. Allowed use: Selected navigation items, rows, segments, and the active tab. */
    fun colorBgSelected(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFE1E6EDL
        SlateTheme.Dark -> 0xFF23272EL
        SlateTheme.HighContrast -> 0xFF0033FFL
        SlateTheme.Recording -> 0xFF30353DL
    }

    /** Side pane and header surface. Allowed use: Sidebar, inspector, tab and pane headers, and recessed fields. */
    fun colorBgSurface(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFF1F3F6L
        SlateTheme.Dark -> 0xFF14161AL
        SlateTheme.HighContrast -> 0xFF000000L
        SlateTheme.Recording -> 0xFF1D2024L
    }

    /** Terminal background, equal to the canvas. Allowed use: Terminal viewport only. */
    fun colorBgTerminal(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFFAFBFCL
        SlateTheme.Dark -> 0xFF17191DL
        SlateTheme.HighContrast -> 0xFF000000L
        SlateTheme.Recording -> 0xFF202328L
    }

    /** Default pane and divider border. Allowed use: Pane edges, the title bar, cards, and fields. */
    fun colorBorderDefault(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFD6DAE0L
        SlateTheme.Dark -> 0xFF2A2E35L
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFF3A3F47L
    }

    /** Input border while the input holds focus. Allowed use: Focused text inputs, paired with the focus ring. */
    fun colorBorderFocus(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF8F99A6L
        SlateTheme.Dark -> 0xFF4A5260L
        SlateTheme.HighContrast -> 0xFFFFFF00L
        SlateTheme.Recording -> 0xFF6A7280L
    }

    /** Control border. Allowed use: Buttons and form fields. */
    fun colorBorderStrong(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFC4CAD2L
        SlateTheme.Dark -> 0xFF363A41L
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFF464C55L
    }

    /** Quiet hairline between sibling regions. Allowed use: Row dividers, pane separators, and card outlines. */
    fun colorBorderSubtle(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFE3E6EAL
        SlateTheme.Dark -> 0xFF22262CL
        SlateTheme.HighContrast -> 0xFF8A8A8AL
        SlateTheme.Recording -> 0xFF30343BL
    }

    /** Keyboard focus outline. Allowed use: Visible focus indication. */
    fun colorFocus(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF2A64C8L
        SlateTheme.Dark -> 0xFF74A7F2L
        SlateTheme.HighContrast -> 0xFFFFFF00L
        SlateTheme.Recording -> 0xFFFFFFFFL
    }

    /** Surface-colored separation inside the focus ring. Allowed use: Visible focus indication. */
    fun colorFocusSeparation(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFF1F3F6L
        SlateTheme.Dark -> 0xFF14161AL
        SlateTheme.HighContrast -> 0xFF000000L
        SlateTheme.Recording -> 0xFF1D2024L
    }

    /** Jump host group identity. Allowed use: Group dots and tile marks, always with the group name. */
    fun colorGroupJump(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF4F5661L
        SlateTheme.Dark -> 0xFFB4B9C2L
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFFC9CDD3L
    }

    /** Lab host group identity. Allowed use: Group dots and tile marks, always with the group name. */
    fun colorGroupLab(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF6E48C2L
        SlateTheme.Dark -> 0xFFB69CF0L
        SlateTheme.HighContrast -> 0xFFFF66FFL
        SlateTheme.Recording -> 0xFFB5A6D9L
    }

    /** Production host group identity. Allowed use: Group dots and tile marks, always with the group name. */
    fun colorGroupProduction(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF2A64C8L
        SlateTheme.Dark -> 0xFF74A7F2L
        SlateTheme.HighContrast -> 0xFF00FFFFL
        SlateTheme.Recording -> 0xFF8CA8E8L
    }

    /** Staging host group identity. Allowed use: Group dots and tile marks, always with the group name. */
    fun colorGroupStaging(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF1A7A45L
        SlateTheme.Dark -> 0xFF6CCB8FL
        SlateTheme.HighContrast -> 0xFF00FF66L
        SlateTheme.Recording -> 0xFF8BC3A4L
    }

    /** Modal overlay scrim. Allowed use: Behind the command palette and dialogs only. */
    fun colorOverlayScrim(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0x661A1D22L
        SlateTheme.Dark -> 0x8C08090BL
        SlateTheme.HighContrast -> 0xE6000000L
        SlateTheme.Recording -> 0xB3000000L
    }

    /** Terminal text selection background. Allowed use: Selected terminal text. Row selection uses color.bg.selected. */
    fun colorSelection(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFCFE0FAL
        SlateTheme.Dark -> 0xFF2B3B52L
        SlateTheme.HighContrast -> 0xFF0033FFL
        SlateTheme.Recording -> 0xFF39465FL
    }

    /** Attention status color. Allowed use: Attention state with icon and text. */
    fun colorStatusAttention(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF8F5300L
        SlateTheme.Dark -> 0xFFE9B061L
        SlateTheme.HighContrast -> 0xFFFFFF00L
        SlateTheme.Recording -> 0xFFD6B47AL
    }

    /** Busy status color. Allowed use: Busy state with icon and text. */
    fun colorStatusBusy(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF2A64C8L
        SlateTheme.Dark -> 0xFF74A7F2L
        SlateTheme.HighContrast -> 0xFF00FFFFL
        SlateTheme.Recording -> 0xFF8CA8E8L
    }

    /** Done status color. Allowed use: Done state with icon and text. */
    fun colorStatusDone(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF1A7A45L
        SlateTheme.Dark -> 0xFF6CCB8FL
        SlateTheme.HighContrast -> 0xFF00FF66L
        SlateTheme.Recording -> 0xFF8BC3A4L
    }

    /** Error status color. Allowed use: Error state with icon and text. */
    fun colorStatusError(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFB8343AL
        SlateTheme.Dark -> 0xFFE5787AL
        SlateTheme.HighContrast -> 0xFFFF66FFL
        SlateTheme.Recording -> 0xFFD99599L
    }

    /** Idle status color. Allowed use: Idle state with icon and text. */
    fun colorStatusIdle(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF4F5661L
        SlateTheme.Dark -> 0xFF8C929CL
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFFA3A8B0L
    }

    /** Offline status color. Allowed use: Offline state with icon and text. */
    fun colorStatusOffline(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF626974L
        SlateTheme.Dark -> 0xFF838993L
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFF8E949DL
    }

    /** ANSI palette slot 0. Allowed use: Terminal SGR color 0. */
    fun colorTerminalAnsiBlack(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF1A1D22L
        SlateTheme.Dark -> 0xFF1B1E23L
        SlateTheme.HighContrast -> 0xFF000000L
        SlateTheme.Recording -> 0xFF25292FL
    }

    /** ANSI palette slot 4. Allowed use: Terminal SGR color 4. */
    fun colorTerminalAnsiBlue(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF2A64C8L
        SlateTheme.Dark -> 0xFF74A7F2L
        SlateTheme.HighContrast -> 0xFF66B3FFL
        SlateTheme.Recording -> 0xFF8CA8E8L
    }

    /** ANSI palette slot 8. Allowed use: Terminal SGR color 8. */
    fun colorTerminalAnsiBrightBlack(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF4F5661L
        SlateTheme.Dark -> 0xFF5A6069L
        SlateTheme.HighContrast -> 0xFF9A9A9AL
        SlateTheme.Recording -> 0xFF6A7280L
    }

    /** ANSI palette slot 12. Allowed use: Terminal SGR color 12. */
    fun colorTerminalAnsiBrightBlue(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF3F76D6L
        SlateTheme.Dark -> 0xFF95BCF6L
        SlateTheme.HighContrast -> 0xFFA6D2FFL
        SlateTheme.Recording -> 0xFFA9BFEEL
    }

    /** ANSI palette slot 14. Allowed use: Terminal SGR color 14. */
    fun colorTerminalAnsiBrightCyan(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF13879AL
        SlateTheme.Dark -> 0xFF86D6E0L
        SlateTheme.HighContrast -> 0xFF99FFFFL
        SlateTheme.Recording -> 0xFFA8D4DAL
    }

    /** ANSI palette slot 10. Allowed use: Terminal SGR color 10. */
    fun colorTerminalAnsiBrightGreen(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF228A52L
        SlateTheme.Dark -> 0xFF8ADBA7L
        SlateTheme.HighContrast -> 0xFF7DFFAEL
        SlateTheme.Recording -> 0xFFA6D3BAL
    }

    /** ANSI palette slot 13. Allowed use: Terminal SGR color 13. */
    fun colorTerminalAnsiBrightMagenta(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF8160CFL
        SlateTheme.Dark -> 0xFFCAB5F5L
        SlateTheme.HighContrast -> 0xFFFF9CFFL
        SlateTheme.Recording -> 0xFFC8BCE3L
    }

    /** ANSI palette slot 9. Allowed use: Terminal SGR color 9. */
    fun colorTerminalAnsiBrightRed(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFCC4A50L
        SlateTheme.Dark -> 0xFFF09499L
        SlateTheme.HighContrast -> 0xFFFF9C9CL
        SlateTheme.Recording -> 0xFFE3AEB1L
    }

    /** ANSI palette slot 15. Allowed use: Terminal SGR color 15. */
    fun colorTerminalAnsiBrightWhite(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF8B919BL
        SlateTheme.Dark -> 0xFFF1F3F5L
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFFF4F5F6L
    }

    /** ANSI palette slot 11. Allowed use: Terminal SGR color 11. */
    fun colorTerminalAnsiBrightYellow(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFA15F00L
        SlateTheme.Dark -> 0xFFF2C585L
        SlateTheme.HighContrast -> 0xFFFFFF99L
        SlateTheme.Recording -> 0xFFE1C696L
    }

    /** ANSI palette slot 6. Allowed use: Terminal SGR color 6. */
    fun colorTerminalAnsiCyan(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF0E7282L
        SlateTheme.Dark -> 0xFF62C4D1L
        SlateTheme.HighContrast -> 0xFF00FFFFL
        SlateTheme.Recording -> 0xFF8CC5CCL
    }

    /** ANSI palette slot 2. Allowed use: Terminal SGR color 2. */
    fun colorTerminalAnsiGreen(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF1A7A45L
        SlateTheme.Dark -> 0xFF6CCB8FL
        SlateTheme.HighContrast -> 0xFF00FF66L
        SlateTheme.Recording -> 0xFF8BC3A4L
    }

    /** ANSI palette slot 5. Allowed use: Terminal SGR color 5. */
    fun colorTerminalAnsiMagenta(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF6E48C2L
        SlateTheme.Dark -> 0xFFB69CF0L
        SlateTheme.HighContrast -> 0xFFFF66FFL
        SlateTheme.Recording -> 0xFFB5A6D9L
    }

    /** ANSI palette slot 1. Allowed use: Terminal SGR color 1. */
    fun colorTerminalAnsiRed(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFB8343AL
        SlateTheme.Dark -> 0xFFE5787AL
        SlateTheme.HighContrast -> 0xFFFF6B6BL
        SlateTheme.Recording -> 0xFFD99599L
    }

    /** ANSI palette slot 7. Allowed use: Terminal SGR color 7. */
    fun colorTerminalAnsiWhite(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF626974L
        SlateTheme.Dark -> 0xFFC9CDD4L
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFFC9CDD3L
    }

    /** ANSI palette slot 3. Allowed use: Terminal SGR color 3. */
    fun colorTerminalAnsiYellow(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF8F5300L
        SlateTheme.Dark -> 0xFFE9B061L
        SlateTheme.HighContrast -> 0xFFFFFF00L
        SlateTheme.Recording -> 0xFFD6B47AL
    }

    /** Terminal cursor. Allowed use: The terminal block, bar, and underline cursor. */
    fun colorTerminalCursor(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF1A1D22L
        SlateTheme.Dark -> 0xFFE6E8EBL
        SlateTheme.HighContrast -> 0xFFFFFF00L
        SlateTheme.Recording -> 0xFFF4F5F6L
    }

    /** Default terminal foreground. Allowed use: Terminal cells without an explicit color. */
    fun colorTerminalFg(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF2A2E35L
        SlateTheme.Dark -> 0xFFC9CDD4L
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFFC9CDD3L
    }

    /** Lowest-emphasis readable text. Allowed use: Placeholders, shortcut hints, and metadata. Meets 4.5:1 on chrome. */
    fun colorTextFaint(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF626974L
        SlateTheme.Dark -> 0xFF838993L
        SlateTheme.HighContrast -> 0xFFD0D0D0L
        SlateTheme.Recording -> 0xFF8E949DL
    }

    /** Muted application text. Allowed use: Secondary columns, captions, and inactive tabs. */
    fun colorTextMuted(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF4F5661L
        SlateTheme.Dark -> 0xFF8C929CL
        SlateTheme.HighContrast -> 0xFFE0E0E0L
        SlateTheme.Recording -> 0xFFA3A8B0L
    }

    /** Primary application text. Allowed use: Names, values, and body copy. */
    fun colorTextPrimary(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF1A1D22L
        SlateTheme.Dark -> 0xFFE6E8EBL
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFFF4F5F6L
    }

    /** Secondary application text. Allowed use: Technical values and dialog copy. */
    fun colorTextSecondary(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF3A404AL
        SlateTheme.Dark -> 0xFFB4B9C2L
        SlateTheme.HighContrast -> 0xFFFFFFFFL
        SlateTheme.Recording -> 0xFFC9CDD3L
    }

    /** macOS-compatible close control indicator. Allowed use: Custom desktop window close control only. */
    fun colorWindowClose(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFFF5F57L
        SlateTheme.Dark -> 0xFFFF5F57L
        SlateTheme.HighContrast -> 0xFFFF66FFL
        SlateTheme.Recording -> 0xFFD99599L
    }

    /** macOS-compatible minimize control indicator. Allowed use: Custom desktop window minimize control only. */
    fun colorWindowMinimize(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFFFEBC2EL
        SlateTheme.Dark -> 0xFFFEBC2EL
        SlateTheme.HighContrast -> 0xFFFFFF00L
        SlateTheme.Recording -> 0xFFD6B47AL
    }

    /** macOS-compatible zoom control indicator. Allowed use: Custom desktop window zoom control only. */
    fun colorWindowZoom(theme: SlateTheme): Long = when (theme) {
        SlateTheme.Light -> 0xFF28C840L
        SlateTheme.Dark -> 0xFF28C840L
        SlateTheme.HighContrast -> 0xFF00FF66L
        SlateTheme.Recording -> 0xFF8BC3A4L
    }

    /** Compact desktop control height. Allowed use: Small buttons in rows and cards. */
    fun controlHeightCompact(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 22.0f
        SlateTheme.Dark -> 22.0f
        SlateTheme.HighContrast -> 22.0f
        SlateTheme.Recording -> 22.0f
    }

    /** Default desktop control height. Allowed use: Buttons, filter fields, and search fields. */
    fun controlHeightDefault(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 26.0f
        SlateTheme.Dark -> 26.0f
        SlateTheme.HighContrast -> 26.0f
        SlateTheme.Recording -> 26.0f
    }

    /** Large control height. Allowed use: The quick-connect field. */
    fun controlHeightLarge(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 36.0f
        SlateTheme.Dark -> 36.0f
        SlateTheme.HighContrast -> 36.0f
        SlateTheme.Recording -> 36.0f
    }

    /** Focus ring surface separation. Allowed use: Keyboard focus indication. */
    fun focusRingOffset(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 1.0f
        SlateTheme.Dark -> 1.0f
        SlateTheme.HighContrast -> 2.0f
        SlateTheme.Recording -> 1.0f
    }

    /** Outer focus ring width. Allowed use: Keyboard focus indication. */
    fun focusRingWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 2.0f
        SlateTheme.Dark -> 2.0f
        SlateTheme.HighContrast -> 3.0f
        SlateTheme.Recording -> 2.0f
    }

    /** Compact icon size. Allowed use: Close glyphs on tabs and panes. */
    fun iconSizeCompact(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 11.0f
        SlateTheme.Dark -> 11.0f
        SlateTheme.HighContrast -> 11.0f
        SlateTheme.Recording -> 11.0f
    }

    /** Default icon size. Allowed use: Controls and status icons. */
    fun iconSizeDefault(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 14.0f
        SlateTheme.Dark -> 14.0f
        SlateTheme.HighContrast -> 14.0f
        SlateTheme.Recording -> 14.0f
    }

    /** Status glyph size. Allowed use: Status glyphs only. */
    fun iconSizeIndicator(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 7.0f
        SlateTheme.Dark -> 7.0f
        SlateTheme.HighContrast -> 7.0f
        SlateTheme.Recording -> 7.0f
    }

    /** Large icon size. Allowed use: Empty-state glyphs without provider branding. */
    fun iconSizeLarge(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 20.0f
        SlateTheme.Dark -> 20.0f
        SlateTheme.HighContrast -> 20.0f
        SlateTheme.Recording -> 20.0f
    }

    /** Medium icon size. Allowed use: Host tile glyphs. */
    fun iconSizeMedium(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 16.0f
        SlateTheme.Dark -> 16.0f
        SlateTheme.HighContrast -> 16.0f
        SlateTheme.Recording -> 16.0f
    }

    /** Small icon size. Allowed use: Compact supplemental icons. */
    fun iconSizeSmall(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 12.0f
        SlateTheme.Dark -> 12.0f
        SlateTheme.HighContrast -> 12.0f
        SlateTheme.Recording -> 12.0f
    }

    /** Box around a status glyph. Allowed use: Status and activity indicators. */
    fun iconSizeStatus(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 12.0f
        SlateTheme.Dark -> 12.0f
        SlateTheme.HighContrast -> 12.0f
        SlateTheme.Recording -> 12.0f
    }

    /** Default icon stroke width. Allowed use: Outline icons. */
    fun iconStrokeDefault(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 1.4f
        SlateTheme.Dark -> 1.4f
        SlateTheme.HighContrast -> 2.0f
        SlateTheme.Recording -> 1.4f
    }

    /** Maximum accessibility laboratory content width. Allowed use: Accessibility laboratory content only. */
    fun layoutAccessibilityLabContentMaximum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 960.0f
        SlateTheme.Dark -> 960.0f
        SlateTheme.HighContrast -> 960.0f
        SlateTheme.Recording -> 960.0f
    }

    /** Maximum accessibility laboratory dialog width. Allowed use: Accessibility laboratory destructive dialog only. */
    fun layoutAccessibilityLabDialogMaximum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 560.0f
        SlateTheme.Dark -> 560.0f
        SlateTheme.HighContrast -> 560.0f
        SlateTheme.Recording -> 560.0f
    }

    /** Minimum accessibility laboratory window height. Allowed use: Accessibility laboratory window constraints only. */
    fun layoutAccessibilityLabMinimumHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 560.0f
        SlateTheme.Dark -> 560.0f
        SlateTheme.HighContrast -> 560.0f
        SlateTheme.Recording -> 560.0f
    }

    /** Minimum accessibility laboratory window width. Allowed use: Accessibility laboratory window constraints only. */
    fun layoutAccessibilityLabMinimumWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 680.0f
        SlateTheme.Dark -> 680.0f
        SlateTheme.HighContrast -> 680.0f
        SlateTheme.Recording -> 680.0f
    }

    /** Accessibility laboratory progress control height. Allowed use: Accessibility laboratory progress controls only. */
    fun layoutAccessibilityLabProgressControlHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 38.0f
        SlateTheme.Dark -> 38.0f
        SlateTheme.HighContrast -> 38.0f
        SlateTheme.Recording -> 38.0f
    }

    /** Accessibility laboratory progress track height. Allowed use: Accessibility laboratory progress indicator only. */
    fun layoutAccessibilityLabProgressTrackHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 10.0f
        SlateTheme.Dark -> 10.0f
        SlateTheme.HighContrast -> 10.0f
        SlateTheme.Recording -> 10.0f
    }

    /** Default accessibility laboratory window height. Allowed use: Accessibility laboratory window geometry only. */
    fun layoutAccessibilityLabWindowHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 780.0f
        SlateTheme.Dark -> 780.0f
        SlateTheme.HighContrast -> 780.0f
        SlateTheme.Recording -> 780.0f
    }

    /** Default accessibility laboratory window width. Allowed use: Accessibility laboratory window geometry only. */
    fun layoutAccessibilityLabWindowWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 920.0f
        SlateTheme.Dark -> 920.0f
        SlateTheme.HighContrast -> 920.0f
        SlateTheme.Recording -> 920.0f
    }

    /** Activity Center event icon container size. Allowed use: Activity Center event rows only. */
    fun layoutActivityIconContainer(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 34.0f
        SlateTheme.Dark -> 34.0f
        SlateTheme.HighContrast -> 34.0f
        SlateTheme.Recording -> 34.0f
    }

    /** Empty artifact preview placeholder height. Allowed use: Artifact preview only. */
    fun layoutArtifactEmptyPreviewHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 180.0f
        SlateTheme.Dark -> 180.0f
        SlateTheme.HighContrast -> 180.0f
        SlateTheme.Recording -> 180.0f
    }

    /** Maximum artifact index column width. Allowed use: Files and artifacts index only. */
    fun layoutArtifactIndexMaximum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 420.0f
        SlateTheme.Dark -> 420.0f
        SlateTheme.HighContrast -> 420.0f
        SlateTheme.Recording -> 420.0f
    }

    /** Minimum artifact index column width. Allowed use: Files and artifacts index only. */
    fun layoutArtifactIndexMinimum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 280.0f
        SlateTheme.Dark -> 280.0f
        SlateTheme.HighContrast -> 280.0f
        SlateTheme.Recording -> 280.0f
    }

    /** Preferred artifact index column width. Allowed use: Files and artifacts index only. */
    fun layoutArtifactIndexWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 360.0f
        SlateTheme.Dark -> 360.0f
        SlateTheme.HighContrast -> 360.0f
        SlateTheme.Recording -> 360.0f
    }

    /** Maximum textual artifact preview height. Allowed use: Artifact preview only. */
    fun layoutArtifactPreviewMaximumHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 240.0f
        SlateTheme.Dark -> 240.0f
        SlateTheme.HighContrast -> 240.0f
        SlateTheme.Recording -> 240.0f
    }

    /** Artifact table primary column width. Allowed use: Files and artifacts table only. */
    fun layoutArtifactPrimaryColumnWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 260.0f
        SlateTheme.Dark -> 260.0f
        SlateTheme.HighContrast -> 260.0f
        SlateTheme.Recording -> 260.0f
    }

    /** Host card height. Allowed use: Host cards in the Home grid. */
    fun layoutCardHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 60.0f
        SlateTheme.Dark -> 60.0f
        SlateTheme.HighContrast -> 60.0f
        SlateTheme.Recording -> 60.0f
    }

    /** Host card minimum width. Allowed use: Host grid column sizing. */
    fun layoutCardMinimumWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 280.0f
        SlateTheme.Dark -> 280.0f
        SlateTheme.HighContrast -> 280.0f
        SlateTheme.Recording -> 280.0f
    }

    /** Host card tile size. Allowed use: The square mark at the start of a host card. */
    fun layoutCardTile(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 36.0f
        SlateTheme.Dark -> 36.0f
        SlateTheme.HighContrast -> 36.0f
        SlateTheme.Recording -> 36.0f
    }

    /** Desktop title bar height. Allowed use: Desktop window chrome. */
    fun layoutChromeHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 38.0f
        SlateTheme.Dark -> 38.0f
        SlateTheme.HighContrast -> 38.0f
        SlateTheme.Recording -> 38.0f
    }

    /** Connection setup panel width. Allowed use: Connection setup overlays only. */
    fun layoutConnectPanelWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 420.0f
        SlateTheme.Dark -> 420.0f
        SlateTheme.HighContrast -> 420.0f
        SlateTheme.Recording -> 420.0f
    }

    /** Height of one option inside a segmented control. Allowed use: Segmented control options; the track adds its padding and border. */
    fun layoutControlSegmentHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 24.0f
        SlateTheme.Dark -> 24.0f
        SlateTheme.HighContrast -> 24.0f
        SlateTheme.Recording -> 24.0f
    }

    /** Wide dialog width. Allowed use: Host-key and multi-field dialogs. */
    fun layoutDialogWideWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 460.0f
        SlateTheme.Dark -> 460.0f
        SlateTheme.HighContrast -> 460.0f
        SlateTheme.Recording -> 460.0f
    }

    /** Standard dialog width. Allowed use: Confirmation and form dialogs. */
    fun layoutDialogWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 420.0f
        SlateTheme.Dark -> 420.0f
        SlateTheme.HighContrast -> 420.0f
        SlateTheme.Recording -> 420.0f
    }

    /** Compact form width for network port fields. Allowed use: Network port form fields only. */
    fun layoutFormPortWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 150.0f
        SlateTheme.Dark -> 150.0f
        SlateTheme.HighContrast -> 150.0f
        SlateTheme.Recording -> 150.0f
    }

    /** Minimum compact host result row height. Allowed use: Compact host search and selection rows. */
    fun layoutHostCompactRowHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 56.0f
        SlateTheme.Dark -> 56.0f
        SlateTheme.HighContrast -> 56.0f
        SlateTheme.Recording -> 56.0f
    }

    /** Host library sidebar width. Allowed use: Desktop sidebar. */
    fun layoutHostSidebarWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 232.0f
        SlateTheme.Dark -> 232.0f
        SlateTheme.HighContrast -> 232.0f
        SlateTheme.Recording -> 232.0f
    }

    /** Default inspector width. Allowed use: Resizable desktop inspector. */
    fun layoutInspectorDefault(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 290.0f
        SlateTheme.Dark -> 290.0f
        SlateTheme.HighContrast -> 290.0f
        SlateTheme.Recording -> 290.0f
    }

    /** Maximum inspector width. Allowed use: Resizable desktop inspector. */
    fun layoutInspectorMaximum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 420.0f
        SlateTheme.Dark -> 420.0f
        SlateTheme.HighContrast -> 420.0f
        SlateTheme.Recording -> 420.0f
    }

    /** Minimum inspector width. Allowed use: Resizable desktop inspector. */
    fun layoutInspectorMinimum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 260.0f
        SlateTheme.Dark -> 260.0f
        SlateTheme.HighContrast -> 260.0f
        SlateTheme.Recording -> 260.0f
    }

    /** List row height. Allowed use: Host list rows and palette results. */
    fun layoutListRowHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 32.0f
        SlateTheme.Dark -> 32.0f
        SlateTheme.HighContrast -> 32.0f
        SlateTheme.Recording -> 32.0f
    }

    /** Primary navigation rail width. Allowed use: Desktop navigation rail. */
    fun layoutNavigationWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 52.0f
        SlateTheme.Dark -> 52.0f
        SlateTheme.HighContrast -> 52.0f
        SlateTheme.Recording -> 52.0f
    }

    /** Global palette offset from the top of the window. Allowed use: Desktop global palette positioning only. */
    fun layoutPaletteOffsetTop(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 50.0f
        SlateTheme.Dark -> 50.0f
        SlateTheme.HighContrast -> 50.0f
        SlateTheme.Recording -> 50.0f
    }

    /** Maximum global palette surface width. Allowed use: Desktop global palette only. */
    fun layoutPaletteWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 560.0f
        SlateTheme.Dark -> 560.0f
        SlateTheme.HighContrast -> 560.0f
        SlateTheme.Recording -> 560.0f
    }

    /** Split pane header height. Allowed use: Pane headers inside split terminals. */
    fun layoutPaneHeaderHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 28.0f
        SlateTheme.Dark -> 28.0f
        SlateTheme.HighContrast -> 28.0f
        SlateTheme.Recording -> 28.0f
    }

    /** Compact progress track height. Allowed use: Inline progress indicators only. */
    fun layoutProgressCompactHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 6.0f
        SlateTheme.Dark -> 6.0f
        SlateTheme.HighContrast -> 6.0f
        SlateTheme.Recording -> 6.0f
    }

    /** Quick connect field height. Allowed use: The Home quick connect field. */
    fun layoutQuickConnectHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 36.0f
        SlateTheme.Dark -> 36.0f
        SlateTheme.HighContrast -> 36.0f
        SlateTheme.Recording -> 36.0f
    }

    /** Maximum security workflow dialog width. Allowed use: Key lifecycle and security dialogs only. */
    fun layoutSecurityDialogMaximum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 620.0f
        SlateTheme.Dark -> 620.0f
        SlateTheme.HighContrast -> 620.0f
        SlateTheme.Recording -> 620.0f
    }

    /** Maximum security information panel width. Allowed use: Key lifecycle and security information panels only. */
    fun layoutSecurityInfoMaximum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 440.0f
        SlateTheme.Dark -> 440.0f
        SlateTheme.HighContrast -> 440.0f
        SlateTheme.Recording -> 440.0f
    }

    /** Maximum width of the settings content column. Allowed use: Settings section content, so rows stay readable in wide windows. */
    fun layoutSettingsContentMaxWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 760.0f
        SlateTheme.Dark -> 760.0f
        SlateTheme.HighContrast -> 760.0f
        SlateTheme.Recording -> 760.0f
    }

    /** Settings category list width. Allowed use: The Settings category sidebar beside the settings content. */
    fun layoutSettingsNavWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 216.0f
        SlateTheme.Dark -> 216.0f
        SlateTheme.HighContrast -> 216.0f
        SlateTheme.Recording -> 216.0f
    }

    /** Compact shell toolbar and menu-row control height. Allowed use: Desktop shell chrome and shared menu rows. */
    fun layoutShellCompactControlHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 26.0f
        SlateTheme.Dark -> 26.0f
        SlateTheme.HighContrast -> 26.0f
        SlateTheme.Recording -> 26.0f
    }

    /** Square shell icon-button target size. Allowed use: Desktop shell toolbar icon buttons. */
    fun layoutShellIconButtonSize(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 24.0f
        SlateTheme.Dark -> 24.0f
        SlateTheme.HighContrast -> 24.0f
        SlateTheme.Recording -> 24.0f
    }

    /** Height for navigation count badges. Allowed use: Desktop navigation count badges only. */
    fun layoutShellNavBadgeHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 20.0f
        SlateTheme.Dark -> 20.0f
        SlateTheme.HighContrast -> 20.0f
        SlateTheme.Recording -> 20.0f
    }

    /** Minimum width for navigation count badges. Allowed use: Desktop navigation count badges only. */
    fun layoutShellNavBadgeWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 22.0f
        SlateTheme.Dark -> 22.0f
        SlateTheme.HighContrast -> 22.0f
        SlateTheme.Recording -> 22.0f
    }

    /** Primary navigation row height. Allowed use: Desktop primary navigation rows only. */
    fun layoutShellNavigationRowHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 28.0f
        SlateTheme.Dark -> 28.0f
        SlateTheme.HighContrast -> 28.0f
        SlateTheme.Recording -> 28.0f
    }

    /** Terminal-pane context-menu width. Allowed use: Desktop pane context menu only. */
    fun layoutShellPaneMenuWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 212.0f
        SlateTheme.Dark -> 212.0f
        SlateTheme.HighContrast -> 212.0f
        SlateTheme.Recording -> 212.0f
    }

    /** Inline workspace rename field width. Allowed use: Desktop workspace tab rename field only. */
    fun layoutShellRenameFieldWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 150.0f
        SlateTheme.Dark -> 150.0f
        SlateTheme.HighContrast -> 150.0f
        SlateTheme.Recording -> 150.0f
    }

    /** Minimum trailing workspace-tab drop target width. Allowed use: Desktop workspace tab strip only. */
    fun layoutShellTabDropMinimum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 80.0f
        SlateTheme.Dark -> 80.0f
        SlateTheme.HighContrast -> 80.0f
        SlateTheme.Recording -> 80.0f
    }

    /** Maximum workspace-tab label width before truncation. Allowed use: Desktop workspace tabs only. */
    fun layoutShellTabLabelMaximum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 160.0f
        SlateTheme.Dark -> 160.0f
        SlateTheme.HighContrast -> 160.0f
        SlateTheme.Recording -> 160.0f
    }

    /** Toolbar button height. Allowed use: Desktop shell toolbar actions only. */
    fun layoutShellToolbarButtonSize(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 24.0f
        SlateTheme.Dark -> 24.0f
        SlateTheme.HighContrast -> 24.0f
        SlateTheme.Recording -> 24.0f
    }

    /** Visible macOS traffic-light indicator diameter. Allowed use: Custom desktop window controls only. */
    fun layoutShellTrafficLightSize(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 12.0f
        SlateTheme.Dark -> 12.0f
        SlateTheme.HighContrast -> 12.0f
        SlateTheme.Recording -> 12.0f
    }

    /** Workspace context-menu width. Allowed use: Desktop workspace context menu only. */
    fun layoutShellWorkspaceMenuWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 238.0f
        SlateTheme.Dark -> 238.0f
        SlateTheme.HighContrast -> 238.0f
        SlateTheme.Recording -> 238.0f
    }

    /** Default context sidebar width. Allowed use: Resizable desktop context sidebar. */
    fun layoutSidebarDefault(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 232.0f
        SlateTheme.Dark -> 232.0f
        SlateTheme.HighContrast -> 232.0f
        SlateTheme.Recording -> 232.0f
    }

    /** Maximum context sidebar width. Allowed use: Resizable desktop context sidebar. */
    fun layoutSidebarMaximum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 320.0f
        SlateTheme.Dark -> 320.0f
        SlateTheme.HighContrast -> 320.0f
        SlateTheme.Recording -> 320.0f
    }

    /** Minimum context sidebar width. Allowed use: Resizable desktop context sidebar. */
    fun layoutSidebarMinimum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 200.0f
        SlateTheme.Dark -> 200.0f
        SlateTheme.HighContrast -> 200.0f
        SlateTheme.Recording -> 200.0f
    }

    /** Split divider hit area. Allowed use: The draggable area around a one-pixel pane divider. */
    fun layoutSplitDividerHit(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 6.0f
        SlateTheme.Dark -> 6.0f
        SlateTheme.HighContrast -> 6.0f
        SlateTheme.Recording -> 6.0f
    }

    /** Maximum panes per terminal tab. Allowed use: Split pane limits. */
    fun layoutSplitMaxPanes(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 4.0f
        SlateTheme.Dark -> 4.0f
        SlateTheme.HighContrast -> 4.0f
        SlateTheme.Recording -> 4.0f
    }

    /** Status bar height. Allowed use: Desktop status bar. */
    fun layoutStatusHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 26.0f
        SlateTheme.Dark -> 26.0f
        SlateTheme.HighContrast -> 26.0f
        SlateTheme.Recording -> 26.0f
    }

    /** Data table row height. Allowed use: Table rows in SFTP, known hosts, and logs. */
    fun layoutTableRowHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 30.0f
        SlateTheme.Dark -> 30.0f
        SlateTheme.HighContrast -> 30.0f
        SlateTheme.Recording -> 30.0f
    }

    /** View toolbar height. Allowed use: Toolbars under the title bar. */
    fun layoutToolbarHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 40.0f
        SlateTheme.Dark -> 40.0f
        SlateTheme.HighContrast -> 40.0f
        SlateTheme.Recording -> 40.0f
    }

    /** Library toolbar menu offset from the top of the library pane. Allowed use: Library toolbar dropdowns and host overlays only. Clears the toolbar row so a menu never covers its trigger. */
    fun layoutToolbarMenuOffsetTop(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 88.0f
        SlateTheme.Dark -> 88.0f
        SlateTheme.HighContrast -> 88.0f
        SlateTheme.Recording -> 88.0f
    }

    /** Default height for a newly duplicated desktop window. Allowed use: Initial desktop window geometry only. */
    fun layoutWindowDefaultHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 840.0f
        SlateTheme.Dark -> 840.0f
        SlateTheme.HighContrast -> 840.0f
        SlateTheme.Recording -> 840.0f
    }

    /** Default width for a newly duplicated desktop window. Allowed use: Initial desktop window geometry only. */
    fun layoutWindowDefaultWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 1280.0f
        SlateTheme.Dark -> 1280.0f
        SlateTheme.HighContrast -> 1280.0f
        SlateTheme.Recording -> 1280.0f
    }

    /** Responsive desktop minimum window height target. Allowed use: Window constraints after responsive migration. */
    fun layoutWindowMinimumHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 640.0f
        SlateTheme.Dark -> 640.0f
        SlateTheme.HighContrast -> 640.0f
        SlateTheme.Recording -> 640.0f
    }

    /** Responsive desktop minimum window width target. Allowed use: Window constraints after responsive migration. */
    fun layoutWindowMinimumWidth(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 960.0f
        SlateTheme.Dark -> 960.0f
        SlateTheme.HighContrast -> 960.0f
        SlateTheme.Recording -> 960.0f
    }

    /** Horizontal offset hiding native controls behind custom window chrome. Allowed use: macOS desktop window options only. */
    fun layoutWindowNativeControlOffset(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 200.0f
        SlateTheme.Dark -> 200.0f
        SlateTheme.HighContrast -> 200.0f
        SlateTheme.Recording -> 200.0f
    }

    /** Terminal tab header height. Allowed use: Desktop terminal tab headers. */
    fun layoutWorkspaceHeaderHeight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 36.0f
        SlateTheme.Dark -> 36.0f
        SlateTheme.HighContrast -> 36.0f
        SlateTheme.Recording -> 36.0f
    }

    /** Control corner radius. Allowed use: Buttons, inputs, menu items, tooltips, toasts, and callouts. */
    fun radiusControl(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 4.0f
        SlateTheme.Dark -> 4.0f
        SlateTheme.HighContrast -> 4.0f
        SlateTheme.Recording -> 4.0f
    }

    /** Floating surface corner radius. Allowed use: The command palette, dialogs, and menus. */
    fun radiusDialog(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 6.0f
        SlateTheme.Dark -> 6.0f
        SlateTheme.HighContrast -> 6.0f
        SlateTheme.Recording -> 6.0f
    }

    /** Card corner radius. Allowed use: Host cards and host tiles. */
    fun radiusPanel(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 6.0f
        SlateTheme.Dark -> 6.0f
        SlateTheme.HighContrast -> 6.0f
        SlateTheme.Recording -> 6.0f
    }

    /** Pill radius. Allowed use: Toggles and count badges only. */
    fun radiusPill(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 999.0f
        SlateTheme.Dark -> 999.0f
        SlateTheme.HighContrast -> 999.0f
        SlateTheme.Recording -> 999.0f
    }

    /** Compact progress-track corner radius. Allowed use: Inline progress indicators only. */
    fun radiusProgress(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 2.0f
        SlateTheme.Dark -> 2.0f
        SlateTheme.HighContrast -> 2.0f
        SlateTheme.Recording -> 2.0f
    }

    /** Segment corner radius inside a segmented control. Allowed use: Segmented control segments only. */
    fun radiusSegment(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 3.0f
        SlateTheme.Dark -> 3.0f
        SlateTheme.HighContrast -> 3.0f
        SlateTheme.Recording -> 3.0f
    }

    /** Zero spacing. Allowed use: Explicitly remove spacing. */
    fun space0(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 0.0f
        SlateTheme.Dark -> 0.0f
        SlateTheme.HighContrast -> 0.0f
        SlateTheme.Recording -> 0.0f
    }

    /** Two-pixel spacing step. Allowed use: Global spacing scale. */
    fun space1(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 2.0f
        SlateTheme.Dark -> 2.0f
        SlateTheme.HighContrast -> 2.0f
        SlateTheme.Recording -> 2.0f
    }

    /** Four-pixel spacing step. Allowed use: Global spacing scale. */
    fun space2(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 4.0f
        SlateTheme.Dark -> 4.0f
        SlateTheme.HighContrast -> 4.0f
        SlateTheme.Recording -> 4.0f
    }

    /** Eight-pixel spacing step. Allowed use: Global spacing scale. */
    fun space3(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 8.0f
        SlateTheme.Dark -> 8.0f
        SlateTheme.HighContrast -> 8.0f
        SlateTheme.Recording -> 8.0f
    }

    /** Twelve-pixel spacing step. Allowed use: Global spacing scale. */
    fun space4(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 12.0f
        SlateTheme.Dark -> 12.0f
        SlateTheme.HighContrast -> 12.0f
        SlateTheme.Recording -> 12.0f
    }

    /** Sixteen-pixel spacing step. Allowed use: Global spacing scale. */
    fun space5(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 16.0f
        SlateTheme.Dark -> 16.0f
        SlateTheme.HighContrast -> 16.0f
        SlateTheme.Recording -> 16.0f
    }

    /** Twenty-four-pixel spacing step. Allowed use: Global spacing scale. */
    fun space6(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 24.0f
        SlateTheme.Dark -> 24.0f
        SlateTheme.HighContrast -> 24.0f
        SlateTheme.Recording -> 24.0f
    }

    /** Thirty-two-pixel spacing step. Allowed use: Global spacing scale. */
    fun space7(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 32.0f
        SlateTheme.Dark -> 32.0f
        SlateTheme.HighContrast -> 32.0f
        SlateTheme.Recording -> 32.0f
    }

    /** Forty-eight-pixel spacing step. Allowed use: Global spacing scale. */
    fun space8(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 48.0f
        SlateTheme.Dark -> 48.0f
        SlateTheme.HighContrast -> 48.0f
        SlateTheme.Recording -> 48.0f
    }

    /** Sixty-four-pixel spacing step. Allowed use: Global spacing scale. */
    fun space9(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 64.0f
        SlateTheme.Dark -> 64.0f
        SlateTheme.HighContrast -> 64.0f
        SlateTheme.Recording -> 64.0f
    }

    /** Accessibility laboratory dialog content gap. Allowed use: Accessibility laboratory destructive dialog only. */
    fun spaceAccessibilityLabDialogGap(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 14.0f
        SlateTheme.Dark -> 14.0f
        SlateTheme.HighContrast -> 14.0f
        SlateTheme.Recording -> 14.0f
    }

    /** Accessibility laboratory dialog padding. Allowed use: Accessibility laboratory destructive dialog only. */
    fun spaceAccessibilityLabDialogPadding(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 22.0f
        SlateTheme.Dark -> 22.0f
        SlateTheme.HighContrast -> 22.0f
        SlateTheme.Recording -> 22.0f
    }

    /** Accessibility laboratory section content gap. Allowed use: Accessibility laboratory sections only. */
    fun spaceAccessibilityLabSectionGap(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 10.0f
        SlateTheme.Dark -> 10.0f
        SlateTheme.HighContrast -> 10.0f
        SlateTheme.Recording -> 10.0f
    }

    /** Accessibility laboratory section vertical padding. Allowed use: Accessibility laboratory sections only. */
    fun spaceAccessibilityLabSectionVertical(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 18.0f
        SlateTheme.Dark -> 18.0f
        SlateTheme.HighContrast -> 18.0f
        SlateTheme.Recording -> 18.0f
    }

    /** Accessibility laboratory status vertical padding. Allowed use: Accessibility laboratory status region only. */
    fun spaceAccessibilityLabStatusVertical(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 14.0f
        SlateTheme.Dark -> 14.0f
        SlateTheme.HighContrast -> 14.0f
        SlateTheme.Recording -> 14.0f
    }

    /** Compact ten-pixel layout spacing. Allowed use: Dense application controls and panels. */
    fun spaceCompact(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 10.0f
        SlateTheme.Dark -> 10.0f
        SlateTheme.HighContrast -> 10.0f
        SlateTheme.Recording -> 10.0f
    }

    /** Dense six-pixel layout spacing. Allowed use: Dense application controls and form rows. */
    fun spaceDense(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 6.0f
        SlateTheme.Dark -> 6.0f
        SlateTheme.HighContrast -> 6.0f
        SlateTheme.Recording -> 6.0f
    }

    /** Fine five-pixel layout spacing. Allowed use: Tightly coupled editor labels and controls. */
    fun spaceFine(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 5.0f
        SlateTheme.Dark -> 5.0f
        SlateTheme.HighContrast -> 5.0f
        SlateTheme.Recording -> 5.0f
    }

    /** Micro three-pixel layout spacing. Allowed use: Tightly coupled status marks and labels only. */
    fun spaceMicro(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 3.0f
        SlateTheme.Dark -> 3.0f
        SlateTheme.HighContrast -> 3.0f
        SlateTheme.Recording -> 3.0f
    }

    /** Horizontal padding for full-width shell banners. Allowed use: Desktop shell overlay banners only. */
    fun spaceShellBannerHorizontal(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 18.0f
        SlateTheme.Dark -> 18.0f
        SlateTheme.HighContrast -> 18.0f
        SlateTheme.Recording -> 18.0f
    }

    /** Compact shell control padding. Allowed use: Desktop shell controls and banners. */
    fun spaceShellCompact(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 10.0f
        SlateTheme.Dark -> 10.0f
        SlateTheme.HighContrast -> 10.0f
        SlateTheme.Recording -> 10.0f
    }

    /** Dense spacing inside desktop shell controls. Allowed use: Desktop shell controls and menus. */
    fun spaceShellDense(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 6.0f
        SlateTheme.Dark -> 6.0f
        SlateTheme.HighContrast -> 6.0f
        SlateTheme.Recording -> 6.0f
    }

    /** Tight horizontal spacing for compact shell rows. Allowed use: Desktop shell rows only. */
    fun spaceShellTight(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 9.0f
        SlateTheme.Dark -> 9.0f
        SlateTheme.HighContrast -> 9.0f
        SlateTheme.Recording -> 9.0f
    }

    /** Terminal viewport horizontal padding. Allowed use: Terminal viewport left and right padding only. */
    fun spaceTerminalInline(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 16.0f
        SlateTheme.Dark -> 16.0f
        SlateTheme.HighContrast -> 16.0f
        SlateTheme.Recording -> 16.0f
    }

    /** Terminal viewport padding. Allowed use: Terminal viewport padding only. */
    fun spaceTerminalPadding(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 10.0f
        SlateTheme.Dark -> 10.0f
        SlateTheme.HighContrast -> 10.0f
        SlateTheme.Recording -> 10.0f
    }

    /** Minimum desktop pointer target, WCAG 2.2 target size (minimum). Allowed use: Desktop interactive controls. Smaller glyphs get invisible padding up to this size. */
    fun targetPointerMinimum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 24.0f
        SlateTheme.Dark -> 24.0f
        SlateTheme.HighContrast -> 24.0f
        SlateTheme.Recording -> 24.0f
    }

    /** Minimum touch target. Allowed use: Touch-capable controls. */
    fun targetTouchMinimum(theme: SlateTheme): Float = when (theme) {
        SlateTheme.Light -> 44.0f
        SlateTheme.Dark -> 44.0f
        SlateTheme.HighContrast -> 44.0f
        SlateTheme.Recording -> 44.0f
    }

    /** Compact Activity Center page title typography. Allowed use: Activity Center title only. */
    fun typeActivityTitle(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(16.0f, 22.0f, 600)
        SlateTheme.Dark -> SlateTypography(16.0f, 22.0f, 600)
        SlateTheme.HighContrast -> SlateTypography(16.0f, 22.0f, 600)
        SlateTheme.Recording -> SlateTypography(16.0f, 22.0f, 600)
    }

    /** Default body typography. Allowed use: Application body copy. */
    fun typeBody(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(13.0f, 18.0f, 400)
        SlateTheme.Dark -> SlateTypography(13.0f, 18.0f, 400)
        SlateTheme.HighContrast -> SlateTypography(13.0f, 18.0f, 400)
        SlateTheme.Recording -> SlateTypography(13.0f, 18.0f, 400)
    }

    /** Large body typography. Allowed use: Palette query input and dialog lead copy. */
    fun typeBodyLarge(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(14.0f, 20.0f, 400)
        SlateTheme.Dark -> SlateTypography(14.0f, 20.0f, 400)
        SlateTheme.HighContrast -> SlateTypography(14.0f, 20.0f, 400)
        SlateTheme.Recording -> SlateTypography(14.0f, 20.0f, 400)
    }

    /** Relaxed body typography. Allowed use: Callout, banner, and empty-state copy. */
    fun typeBodyRelaxed(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(13.0f, 19.0f, 400)
        SlateTheme.Dark -> SlateTypography(13.0f, 19.0f, 400)
        SlateTheme.HighContrast -> SlateTypography(13.0f, 19.0f, 400)
        SlateTheme.Recording -> SlateTypography(13.0f, 19.0f, 400)
    }

    /** Small body typography. Allowed use: Dense supporting copy. */
    fun typeBodySmall(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(12.0f, 17.0f, 400)
        SlateTheme.Dark -> SlateTypography(12.0f, 17.0f, 400)
        SlateTheme.HighContrast -> SlateTypography(12.0f, 17.0f, 400)
        SlateTheme.Recording -> SlateTypography(12.0f, 17.0f, 400)
    }

    /** Caption typography. Allowed use: Compact metadata. */
    fun typeCaption(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(12.0f, 16.0f, 400)
        SlateTheme.Dark -> SlateTypography(12.0f, 16.0f, 400)
        SlateTheme.HighContrast -> SlateTypography(12.0f, 16.0f, 400)
        SlateTheme.Recording -> SlateTypography(12.0f, 16.0f, 400)
    }

    /** Heading typography. Allowed use: Primary section headings. */
    fun typeHeading(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(14.0f, 20.0f, 600)
        SlateTheme.Dark -> SlateTypography(14.0f, 20.0f, 600)
        SlateTheme.HighContrast -> SlateTypography(14.0f, 20.0f, 600)
        SlateTheme.Recording -> SlateTypography(14.0f, 20.0f, 600)
    }

    /** Small heading typography. Allowed use: Section headings. */
    fun typeHeadingSmall(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(13.0f, 18.0f, 600)
        SlateTheme.Dark -> SlateTypography(13.0f, 18.0f, 600)
        SlateTheme.HighContrast -> SlateTypography(13.0f, 18.0f, 600)
        SlateTheme.Recording -> SlateTypography(13.0f, 18.0f, 600)
    }

    /** Control label typography. Allowed use: Control and row labels. */
    fun typeLabel(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(12.0f, 16.0f, 500)
        SlateTheme.Dark -> SlateTypography(12.0f, 16.0f, 500)
        SlateTheme.HighContrast -> SlateTypography(12.0f, 16.0f, 500)
        SlateTheme.Recording -> SlateTypography(12.0f, 16.0f, 500)
    }

    /** Compact numeric metric typography. Allowed use: Prominent compact metrics and pairing codes. */
    fun typeMetric(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(20.0f, 24.0f, 600)
        SlateTheme.Dark -> SlateTypography(20.0f, 24.0f, 600)
        SlateTheme.HighContrast -> SlateTypography(20.0f, 24.0f, 600)
        SlateTheme.Recording -> SlateTypography(20.0f, 24.0f, 600)
    }

    /** Micro metadata typography. Allowed use: Space-constrained secondary metadata only. */
    fun typeMicro(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(11.0f, 14.0f, 400)
        SlateTheme.Dark -> SlateTypography(11.0f, 14.0f, 400)
        SlateTheme.HighContrast -> SlateTypography(11.0f, 14.0f, 400)
        SlateTheme.Recording -> SlateTypography(11.0f, 14.0f, 400)
    }

    /** Smallest supported metadata typography. Allowed use: Exceptional space-constrained metadata only. */
    fun typeNano(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(10.0f, 14.0f, 400)
        SlateTheme.Dark -> SlateTypography(10.0f, 14.0f, 400)
        SlateTheme.HighContrast -> SlateTypography(10.0f, 14.0f, 400)
        SlateTheme.Recording -> SlateTypography(10.0f, 14.0f, 400)
    }

    /** Default terminal typography before user scaling. Allowed use: Terminal viewport only; font size remains user-configurable. */
    fun typeTerminal(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(13.0f, 18.2f, 400)
        SlateTheme.Dark -> SlateTypography(13.0f, 18.2f, 400)
        SlateTheme.HighContrast -> SlateTypography(13.0f, 18.2f, 400)
        SlateTheme.Recording -> SlateTypography(13.0f, 18.2f, 400)
    }

    /** Page title typography. Allowed use: Top-level page titles. */
    fun typeTitle(theme: SlateTheme): SlateTypography = when (theme) {
        SlateTheme.Light -> SlateTypography(20.0f, 28.0f, 600)
        SlateTheme.Dark -> SlateTypography(20.0f, 28.0f, 600)
        SlateTheme.HighContrast -> SlateTypography(20.0f, 28.0f, 600)
        SlateTheme.Recording -> SlateTypography(20.0f, 28.0f, 600)
    }
}
